//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface _SCButton : UIButton
{
    unsigned long long _size;
    unsigned long long _style;
    unsigned long long _baseColor;
}

+ (double)_buttonHeightForSize:(unsigned long long)arg1;
- (id)_backgroundColorForSize:(unsigned long long)arg1 style:(unsigned long long)arg2 state:(unsigned long long)arg3;
- (id)_borderColorForSize:(unsigned long long)arg1 style:(unsigned long long)arg2 state:(unsigned long long)arg3;
- (id)_defaultTitleColorForSize:(unsigned long long)arg1 style:(unsigned long long)arg2;
- (id)_disabledColorForSize:(unsigned long long)arg1;
- (id)_highlightTitleColorForSize:(unsigned long long)arg1 style:(unsigned long long)arg2;
- (id)_titleFontForSize:(unsigned long long)arg1;
- (id)initWithSize:(unsigned long long)arg1 style:(unsigned long long)arg2 color:(unsigned long long)arg3;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (void)setEnabled:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

