//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AMPAppStateProvider, AMPDictionaryPersistor, AMPEventConfigurer, AMPEventSerializer, AMPExperimentProvider, AMPPropertyListPersistor, AMPTimerProvider, NSDictionary, NSMutableOrderedSet, NSOperationQueue, SCABlizzardConfig, SCLogger, SCTimeProvider;

@interface AMPEventLoggerConstructorV2 : NSObject
{
    SCABlizzardConfig *_config;
    NSOperationQueue *_loggingQueue;
    SCTimeProvider *_timeProvider;
    AMPEventConfigurer *_eventConfigurer;
    CDUnknownBlockType _userCheck;
    AMPTimerProvider *_timerProvider;
    CDUnknownBlockType _tokenProvider;
    AMPDictionaryPersistor *_dictPersistor;
    AMPPropertyListPersistor *_plistPersistor;
    AMPEventSerializer *_eventSerializer;
    AMPAppStateProvider *_appStateProvider;
    SCLogger *_scLogger;
    NSDictionary *_loggerIndex;
    NSMutableOrderedSet *_sortedLoggers;
    struct NSDictionary *_qosToLoggersDict;
    AMPExperimentProvider *_experimentProvider;
}

- (void).cxx_destruct;
- (id)_constructLoggerIndex;
- (id)_getCollectorUrl:(id)arg1;
- (struct NSDictionary *)_loggerDictFromQoSDict:(id)arg1;
- (id)_sortLoggers:(id)arg1;
- (id)_sortQosStrings:(id)arg1;
@property(retain, nonatomic) AMPAppStateProvider *appStateProvider; // @synthesize appStateProvider=_appStateProvider;
@property(retain, nonatomic) SCABlizzardConfig *config; // @synthesize config=_config;
- (void)constructLoggers;
@property(retain, nonatomic) AMPDictionaryPersistor *dictPersistor; // @synthesize dictPersistor=_dictPersistor;
@property(retain, nonatomic) AMPEventConfigurer *eventConfigurer; // @synthesize eventConfigurer=_eventConfigurer;
@property(retain, nonatomic) AMPEventSerializer *eventSerializer; // @synthesize eventSerializer=_eventSerializer;
@property(readonly, nonatomic) __weak AMPExperimentProvider *experimentProvider; // @synthesize experimentProvider=_experimentProvider;
- (struct NSArray *)getAllLoggers;
- (struct NSDictionary *)getQoSToLoggersDict;
- (id)initWithConfig:(id)arg1 loggingQueue:(id)arg2 timeProvider:(id)arg3 eventConfigurer:(id)arg4 userCheckBlock:(CDUnknownBlockType)arg5 timerProvider:(id)arg6 tokenProvider:(CDUnknownBlockType)arg7 dictionaryPersistor:(id)arg8 plistPersistor:(id)arg9 eventSerializer:(id)arg10 scLogger:(id)arg11 appStateProvider:(id)arg12 experimentProvider:(id)arg13;
@property(retain, nonatomic) NSDictionary *loggerIndex; // @synthesize loggerIndex=_loggerIndex;
@property(retain, nonatomic) NSOperationQueue *loggingQueue; // @synthesize loggingQueue=_loggingQueue;
@property(retain, nonatomic) AMPPropertyListPersistor *plistPersistor; // @synthesize plistPersistor=_plistPersistor;
@property(retain, nonatomic) NSDictionary *qosToLoggersDict; // @synthesize qosToLoggersDict=_qosToLoggersDict;
@property(retain, nonatomic) SCLogger *scLogger; // @synthesize scLogger=_scLogger;
@property(retain, nonatomic) NSMutableOrderedSet *sortedLoggers; // @synthesize sortedLoggers=_sortedLoggers;
@property(retain, nonatomic) SCTimeProvider *timeProvider; // @synthesize timeProvider=_timeProvider;
@property(retain, nonatomic) AMPTimerProvider *timerProvider; // @synthesize timerProvider=_timerProvider;
@property(copy, nonatomic) CDUnknownBlockType tokenProvider; // @synthesize tokenProvider=_tokenProvider;
@property(copy, nonatomic) CDUnknownBlockType userCheck; // @synthesize userCheck=_userCheck;

@end

