//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BTUICardExpiryFormat : NSObject
{
    _Bool _backspace;
    NSString *_value;
    unsigned long long _cursorLocation;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool backspace; // @synthesize backspace=_backspace;
@property(nonatomic) unsigned long long cursorLocation; // @synthesize cursorLocation=_cursorLocation;
- (void)formattedValue:(id *)arg1 cursorLocation:(unsigned long long *)arg2;
@property(copy, nonatomic) NSString *value; // @synthesize value=_value;

@end

