//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GRXForwardingWriter.h"

@interface GRXMappingWriter : GRXForwardingWriter
{
    CDUnknownBlockType _map;
}

- (void).cxx_destruct;
- (id)initWithWriter:(id)arg1;
- (id)initWithWriter:(id)arg1 map:(CDUnknownBlockType)arg2;
- (void)writeValue:(id)arg1;

@end

