//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface IMPBusinessSnapInsights_SectionStats_Viewer : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *bitmojiAvatarId; // @dynamic bitmojiAvatarId;
@property(copy, nonatomic) NSString *bitmojiSelfieId; // @dynamic bitmojiSelfieId;
@property(copy, nonatomic) NSString *displayName; // @dynamic displayName;
@property(nonatomic) _Bool isVerified; // @dynamic isVerified;
@property(readonly, nonatomic) int nameOneOfCase; // @dynamic nameOneOfCase;
@property(copy, nonatomic) NSString *userId; // @dynamic userId;
@property(copy, nonatomic) NSString *username; // @dynamic username;
@property(nonatomic) long long viewTimestamp; // @dynamic viewTimestamp;

@end

