//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class IMPCreateAccountRequest, NSData, NSString;

@interface IMPCreatePublisherAccountRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) IMPCreateAccountRequest *createAccountRequest; // @dynamic createAccountRequest;
@property(nonatomic) _Bool hasCreateAccountRequest; // @dynamic hasCreateAccountRequest;
@property(copy, nonatomic) NSString *publisherIconURL; // @dynamic publisherIconURL;
@property(nonatomic) long long publisherId; // @dynamic publisherId;
@property(copy, nonatomic) NSData *publisherMetadata; // @dynamic publisherMetadata;

@end

