//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class IMPBusiness;

@interface IMPGetBusinessResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) IMPBusiness *business; // @dynamic business;
@property(nonatomic) _Bool hasBusiness; // @dynamic hasBusiness;

@end

