//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface IMPMoveBusinessProfileResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *businessAccountId; // @dynamic businessAccountId;
@property(copy, nonatomic) NSString *organizationId; // @dynamic organizationId;
@property(copy, nonatomic) NSString *previousBusinessAccountId; // @dynamic previousBusinessAccountId;
@property(copy, nonatomic) NSString *previousOrganizationId; // @dynamic previousOrganizationId;

@end

