//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "LSATextInputUriDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class LSAQueuePerformer, LSAUriRequest, NSString, UITextView;

@interface LSATextInputController : NSObject <LSATextInputUriDelegate, UITextViewDelegate>
{
    LSAQueuePerformer *_uriServicePerformer;
    LSAUriRequest *_requestKeyboardUriRequest;
    CDUnknownBlockType _requestKeyboardUriCallback;
    _Bool _allowMultiLineInput;
    _Bool _returnKeyPressed;
    UITextView *_textView;
}

- (void).cxx_destruct;
- (void)_dismissKeyboard;
- (long long)_keyboardTypeStringToEnum:(id)arg1;
- (void)_notifyBadRequest:(id)arg1 description:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_notifyKeyboardIsOpen:(_Bool)arg1;
- (void)_notifyRequest:(id)arg1 description:(id)arg2 code:(long long)arg3 data:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)_provideTextInputDataFromTextView:(id)arg1;
- (void)_requestKeyboard:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (long long)_returnKeyTypeStringToEnum:(id)arg1;
- (void)_setSelectedTextRange:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_setSelectedTextRangeFrom:(long long)arg1 to:(long long)arg2;
- (void)dealloc;
- (void)handleTextInputRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithParentView:(id)arg1;
- (void)reset;
@property(readonly, nonatomic) UITextView *textView; // @synthesize textView=_textView;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

