//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface LSDepthDataTextureContainer : NSObject
{
    struct TrackerData {
        CDUnknownFunctionPointerType *_vptr$ISerializable;
        _Bool _isruntime;
        struct DepthFrame depthFrame;
        struct DepthFrame newportReferenceDepthFrame;
    } _depthTrackingData;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct TrackerData)depthTrackingData;
- (id)initWithDepthTrackingData:(struct TrackerData)arg1;

@end

