//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface LSFaceMeshARGeometryCaches : NSObject
{
    shared_ptr_cc71a7a2 _baseFaceMesh;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (shared_ptr_cc71a7a2)baseFaceMesh;
- (void)setBaseFaceMesh:(shared_ptr_cc71a7a2)arg1;

@end

