//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UIView;

@interface MASViewAttribute : NSObject
{
    UIView *_view;
    long long _layoutAttribute;
}

- (void).cxx_destruct;
- (unsigned long long)hash;
- (id)initWithView:(id)arg1 layoutAttribute:(long long)arg2;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isSizeAttribute;
@property(readonly, nonatomic) long long layoutAttribute; // @synthesize layoutAttribute=_layoutAttribute;
@property(readonly, nonatomic) __weak UIView *view; // @synthesize view=_view;

@end

