//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class Media, NSDictionary, NSError, NSHTTPURLResponse, SCRequest;

@protocol MediaDelegate <NSObject>
- (_Bool)isImage;
- (_Bool)isPsychomantis;
- (_Bool)isSpectaclesVideo;
- (_Bool)isVideo;
- (_Bool)isVideoStreaming;
- (_Bool)isVideoWithSound;

@optional
- (void)didFinishDownload:(Media *)arg1 success:(_Bool)arg2 numBytes:(unsigned long long)arg3;
- (void)didFinishDownload:(Media *)arg1 success:(_Bool)arg2 numBytes:(unsigned long long)arg3 additionalParams:(NSDictionary *)arg4;
- (void)didStartDownload:(Media *)arg1;
- (void)fetchMediaBadRequestForMedia:(Media *)arg1;
- (void)fetchMediaDidCancelForMedia:(Media *)arg1;
- (void)fetchMediaDidFailForMedia:(Media *)arg1 error:(NSError *)arg2;
- (void)fetchMediaDidSucceedForMedia:(Media *)arg1;
- (void)fetchMediaDidSucceedForMedia:(Media *)arg1 isFromCache:(_Bool)arg2;
- (void)fetchMediaIsGoneForMedia:(Media *)arg1;
- (void)fetchMediaIsLoadingForMedia:(Media *)arg1;
- (void)fetchMediaIsLoadingForMedia:(Media *)arg1 userInitiated:(_Bool)arg2;
- (void)fetchMediaNotFoundForMedia:(Media *)arg1;
- (void)fetchMediaResponseHandlerCustom:(Media *)arg1 request:(SCRequest *)arg2 response:(NSHTTPURLResponse *)arg3 error:(NSError *)arg4;
@end

