//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@interface MetaStoryFeatures : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool isCity; // @dynamic isCity;
@property(nonatomic) _Bool isNeighborhood; // @dynamic isNeighborhood;
@property(nonatomic) unsigned int numEvents; // @dynamic numEvents;
@property(nonatomic) unsigned int numPlaces; // @dynamic numPlaces;

@end

