//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;
@protocol MGLOfflineRegion;

@interface MGLOfflinePack : NSObject
{
    _Bool _isSuspending;
    long long _state;
    struct OfflineRegion *_mbglOfflineRegion;
    struct MGLOfflinePackProgress _progress;
}

@property(readonly, nonatomic) NSData *context;
- (void)dealloc;
- (void)didReceiveError:(id)arg1;
- (void)didReceiveMaximumAllowedMapboxTiles:(unsigned long long)arg1;
- (id)init;
- (id)initWithMBGLRegion:(struct OfflineRegion *)arg1;
- (void)invalidate;
@property(nonatomic) struct OfflineRegion *mbglOfflineRegion; // @synthesize mbglOfflineRegion=_mbglOfflineRegion;
- (void)offlineRegionStatusDidChange:(struct OfflineRegionStatus)arg1;
@property(nonatomic) struct MGLOfflinePackProgress progress; // @synthesize progress=_progress;
@property(readonly, nonatomic) id <MGLOfflineRegion> region;
- (void)requestProgress;
- (void)resume;
- (void)setState:(long long)arg1;
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
- (void)suspend;

@end

