//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSData;

@interface MLBSnapScanResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasSnapCodeData; // @dynamic hasSnapCodeData;
@property(nonatomic) _Bool hasSuccess; // @dynamic hasSuccess;
@property(copy, nonatomic) NSData *snapCodeData; // @dynamic snapCodeData;
@property(nonatomic) _Bool success; // @dynamic success;

@end

