//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@interface MLBVideoMetaFrame : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) unsigned int eofTs; // @dynamic eofTs;
@property(nonatomic) _Bool hasEofTs; // @dynamic hasEofTs;
@property(nonatomic) _Bool hasPts; // @dynamic hasPts;
@property(nonatomic) _Bool hasRawTs; // @dynamic hasRawTs;
@property(nonatomic) _Bool hasSofTs; // @dynamic hasSofTs;
@property(nonatomic) unsigned long long pts; // @dynamic pts;
@property(nonatomic) unsigned int rawTs; // @dynamic rawTs;
@property(nonatomic) unsigned int sofTs; // @dynamic sofTs;

@end

