//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class MLBTemperatureResponse;

@interface MLBWifiThrottlingReport : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool dutyCycleControl; // @dynamic dutyCycleControl;
@property(nonatomic) _Bool hasDutyCycleControl; // @dynamic hasDutyCycleControl;
@property(nonatomic) _Bool hasTemperatures; // @dynamic hasTemperatures;
@property(nonatomic) _Bool hasThrottling; // @dynamic hasThrottling;
@property(retain, nonatomic) MLBTemperatureResponse *temperatures; // @dynamic temperatures;
@property(nonatomic) unsigned int throttling; // @dynamic throttling;

@end

