//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@class UIImageView;

@interface NYTScalingImageView : UIScrollView
{
    UIImageView *_imageView;
}

- (void).cxx_destruct;
- (void)centerScrollViewContents;
- (void)commonInitWithImage:(id)arg1 imageData:(id)arg2;
- (void)didAddSubview:(id)arg1;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithImage:(id)arg1 frame:(struct CGRect)arg2;
- (id)initWithImageData:(id)arg1 frame:(struct CGRect)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (void)setupImageScrollView;
- (void)setupInternalImageViewWithImage:(id)arg1 imageData:(id)arg2;
- (void)updateImage:(id)arg1;
- (void)updateImage:(id)arg1 imageData:(id)arg2;
- (void)updateImageData:(id)arg1;
- (void)updateZoomScale;

@end

