//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Photos/PHAsset.h>

#import "SCGalleryItem-Protocol.h"
#import "SCGalleryViewingItem-Protocol.h"

@class NSDate, NSString;

@interface PHAsset (SCGalleryItem) <SCGalleryItem, SCGalleryViewingItem>
- (struct CGSize)contentSize;
@property(readonly, nonatomic) NSDate *galleryItemCreateTime;
@property(readonly, nonatomic) NSDate *galleryItemDuplicateTime;
@property(readonly, copy, nonatomic) NSString *galleryItemIdentifier;
@property(readonly, nonatomic) unsigned long long galleryItemType;
- (long long)orientation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

