//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RTCAudioSessionActivationDelegate-Protocol.h"

@class AVAudioSession, AVAudioSessionDataSourceDescription, AVAudioSessionRouteDescription, NSArray, NSRecursiveLock, NSString;

@interface RTCAudioSession : NSObject <RTCAudioSessionActivationDelegate>
{
    int _lockRecursionCount;
    int _webRTCSessionCount;
    _Bool _isAudioEnabled;
    _Bool _isInterrupted;
    _Bool _isCallKitInUse;
    NSRecursiveLock *_lock;
    vector_03b67401 _delegates;
}

+ (id)lockError;
+ (id)sharedInstance;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly) double IOBufferDuration;
@property(readonly, nonatomic) int activationCount;
- (void)addDelegate:(id)arg1;
- (void)audioSession:(id)arg1 didChangeVolume:(double)arg2;
- (void)audioSession:(id)arg1 didEndInterruption:(_Bool)arg2;
- (void)audioSessionDidActivate:(id)arg1;
- (void)audioSessionDidBeginInterruption:(id)arg1;
- (void)audioSessionDidDeactivate:(id)arg1;
- (void)audioSessionMediaServicesWereLost:(id)arg1;
- (void)audioSessionMediaServicesWereReset:(id)arg1;
- (_Bool)beginWebRTCSession:(id *)arg1;
@property(readonly) _Bool canPlayOrRecord;
@property(readonly) NSString *category;
@property(readonly) unsigned long long categoryOptions;
- (_Bool)checkLock:(id *)arg1;
- (id)configurationErrorWithDescription:(id)arg1;
- (_Bool)configureWebRTCSession:(id *)arg1;
@property(readonly) AVAudioSessionRouteDescription *currentRoute;
- (void)dealloc;
@property(readonly, nonatomic) vector_03b67401 delegates; // @synthesize delegates=_delegates;
@property(readonly, copy) NSString *description;
- (_Bool)endWebRTCSession:(id *)arg1;
- (void)handleCallKitActivate:(id)arg1;
- (void)handleCallKitDeactivate:(id)arg1;
- (void)handleRouteChangeNotification:(id)arg1;
- (id)init;
@property(readonly) _Bool inputAvailable;
@property(readonly) AVAudioSessionDataSourceDescription *inputDataSource;
@property(readonly) NSArray *inputDataSources;
@property(readonly) float inputGain;
@property(readonly) _Bool inputGainSettable;
@property(readonly) double inputLatency;
@property(readonly) long long inputNumberOfChannels;
@property(readonly, nonatomic) _Bool isActive;
@property(nonatomic) _Bool isAudioEnabled;
@property(nonatomic) _Bool isInterrupted;
@property(readonly, nonatomic) _Bool isLocked;
- (void)lockForConfiguration;
@property(readonly) long long maximumInputNumberOfChannels;
@property(readonly) long long maximumOutputNumberOfChannels;
@property(readonly) NSString *mode;
- (void)notifyDidBeginInterruption;
- (void)notifyDidChangeCanPlayOrRecord:(_Bool)arg1;
- (void)notifyDidChangeOutputVolume:(float)arg1;
- (void)notifyDidChangeRouteWithReason:(unsigned long long)arg1 previousRoute:(id)arg2;
- (void)notifyDidDetectPlayoutGlitch:(long long)arg1;
- (void)notifyDidEndInterruptionWithShouldResumeSession:(_Bool)arg1;
- (void)notifyDidStartPlayOrRecord;
- (void)notifyDidStopPlayOrRecord;
- (void)notifyMediaServicesWereLost;
- (void)notifyMediaServicesWereReset;
@property(readonly) AVAudioSessionDataSourceDescription *outputDataSource;
@property(readonly) NSArray *outputDataSources;
@property(readonly) double outputLatency;
@property(readonly) long long outputNumberOfChannels;
@property(readonly) float outputVolume;
- (_Bool)overrideOutputAudioPort:(unsigned long long)arg1 error:(id *)arg2;
@property(readonly) double preferredIOBufferDuration;
@property(readonly) double preferredSampleRate;
- (void)pushDelegate:(id)arg1;
- (void)removeDelegate:(id)arg1;
- (void)removeZeroedDelegates;
@property(readonly) double sampleRate;
@property(readonly) _Bool secondaryAudioShouldBeSilencedHint;
@property(readonly, nonatomic) AVAudioSession *session;
- (_Bool)setActive:(_Bool)arg1 error:(id *)arg2;
- (_Bool)setCategory:(id)arg1 withOptions:(unsigned long long)arg2 error:(id *)arg3;
- (_Bool)setConfiguration:(id)arg1 active:(_Bool)arg2 error:(id *)arg3;
- (_Bool)setConfiguration:(id)arg1 active:(_Bool)arg2 shouldSetActive:(_Bool)arg3 error:(id *)arg4;
- (_Bool)setConfiguration:(id)arg1 error:(id *)arg2;
- (_Bool)setInputDataSource:(id)arg1 error:(id *)arg2;
- (_Bool)setInputGain:(float)arg1 error:(id *)arg2;
- (void)setIsActive:(_Bool)arg1;
- (_Bool)setMode:(id)arg1 error:(id *)arg2;
- (_Bool)setOutputDataSource:(id)arg1 error:(id *)arg2;
- (_Bool)setPreferredIOBufferDuration:(double)arg1 error:(id *)arg2;
- (_Bool)setPreferredInput:(id)arg1 error:(id *)arg2;
- (_Bool)setPreferredInputNumberOfChannels:(long long)arg1 error:(id *)arg2;
- (_Bool)setPreferredOutputNumberOfChannels:(long long)arg1 error:(id *)arg2;
- (_Bool)setPreferredSampleRate:(double)arg1 error:(id *)arg2;
@property(nonatomic) _Bool useManualAudio;
- (_Bool)unconfigureWebRTCSession:(id *)arg1;
- (void)unlockForConfiguration;
@property(readonly, nonatomic) int webRTCSessionCount;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

