//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, SnapBrainResponse_Results_AudioFingerprint;

@interface SASTrack : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SnapBrainResponse_Results_AudioFingerprint *audioFingerprint; // @dynamic audioFingerprint;
@property(nonatomic) _Bool hasAudioFingerprint; // @dynamic hasAudioFingerprint;
@property(copy, nonatomic) NSString *trackId; // @dynamic trackId;

@end

