//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@class NSNumber, NSString;

@interface SCACommerceEventBase : SCAUserTrackedEvent
{
    NSNumber *lensPosition;
    NSNumber *hasInputSearchTerms;
    long long source;
    long long productItemType;
    long long primaryAvatarType;
    long long secondaryAvatarType;
    long long attachmentType;
    long long adProductSourceType;
    NSString *commerceSessionId;
    NSString *pageId;
    NSString *displayId;
    NSString *storeId;
    NSString *productId;
    NSString *cartId;
    NSString *jsonMetadata;
    NSString *discoverEditionId;
    NSString *sourceId;
    NSString *externalSessionId;
    NSString *snapId;
    NSString *discoverEditionSessionId;
    NSString *commerceProductType;
    NSString *commerceOriginType;
    NSString *contextSnapId;
    NSString *contextSnapType;
    NSString *contextAttachmentType;
    NSString *contextMediaType;
    NSString *contextFilterGeolensId;
    NSString *contextSessionId;
    NSString *discoverPublisherId;
    NSString *discoverSnapId;
    NSString *scannableId;
    NSString *scannableData;
    NSString *scanSessionId;
    NSString *lensCTALensId;
    NSString *lensSessionId;
    NSString *lensCameraSourceType;
    NSString *lensCameraType;
    NSString *comicId;
    NSString *adId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getAdId;
- (long long)getAdProductSourceType;
- (long long)getAttachmentType;
- (id)getCartId;
- (id)getComicId;
- (id)getCommerceOriginType;
- (id)getCommerceProductType;
- (id)getCommerceSessionId;
- (id)getContextAttachmentType;
- (id)getContextFilterGeolensId;
- (id)getContextMediaType;
- (id)getContextSessionId;
- (id)getContextSnapId;
- (id)getContextSnapType;
- (id)getDiscoverEditionId;
- (id)getDiscoverEditionSessionId;
- (id)getDiscoverPublisherId;
- (id)getDiscoverSnapId;
- (id)getDisplayId;
- (id)getEventName;
- (long long)getEventQoS;
- (id)getExternalSessionId;
- (_Bool)getHasInputSearchTerms;
- (id)getJsonMetadata;
- (id)getLensCTALensId;
- (id)getLensCameraSourceType;
- (id)getLensCameraType;
- (long long)getLensPosition;
- (id)getLensSessionId;
- (id)getPageId;
- (double)getPerUserSamplingRate;
- (long long)getPrimaryAvatarType;
- (id)getProductId;
- (long long)getProductItemType;
- (id)getScanSessionId;
- (id)getScannableData;
- (id)getScannableId;
- (long long)getSecondaryAvatarType;
- (id)getSnapId;
- (long long)getSource;
- (id)getSourceId;
- (id)getStoreId;
- (id)init;
- (void)setAdId:(id)arg1;
- (void)setAdProductSourceType:(long long)arg1;
- (void)setAttachmentType:(long long)arg1;
- (void)setCartId:(id)arg1;
- (void)setComicId:(id)arg1;
- (void)setCommerceOriginType:(id)arg1;
- (void)setCommerceProductType:(id)arg1;
- (void)setCommerceSessionId:(id)arg1;
- (void)setContextAttachmentType:(id)arg1;
- (void)setContextFilterGeolensId:(id)arg1;
- (void)setContextMediaType:(id)arg1;
- (void)setContextSessionId:(id)arg1;
- (void)setContextSnapId:(id)arg1;
- (void)setContextSnapType:(id)arg1;
- (void)setDiscoverEditionId:(id)arg1;
- (void)setDiscoverEditionSessionId:(id)arg1;
- (void)setDiscoverPublisherId:(id)arg1;
- (void)setDiscoverSnapId:(id)arg1;
- (void)setDisplayId:(id)arg1;
- (void)setExternalSessionId:(id)arg1;
- (void)setHasInputSearchTerms:(_Bool)arg1;
- (void)setJsonMetadata:(id)arg1;
- (void)setLensCTALensId:(id)arg1;
- (void)setLensCameraSourceType:(id)arg1;
- (void)setLensCameraType:(id)arg1;
- (void)setLensPosition:(long long)arg1;
- (void)setLensSessionId:(id)arg1;
- (void)setPageId:(id)arg1;
- (void)setPrimaryAvatarType:(long long)arg1;
- (void)setProductId:(id)arg1;
- (void)setProductItemType:(long long)arg1;
- (void)setScanSessionId:(id)arg1;
- (void)setScannableData:(id)arg1;
- (void)setScannableId:(id)arg1;
- (void)setSecondaryAvatarType:(long long)arg1;
- (void)setSnapId:(id)arg1;
- (void)setSource:(long long)arg1;
- (void)setSourceId:(id)arg1;
- (void)setStoreId:(id)arg1;

@end

