//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface SCACHUserAchievementCountInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *countsArray; // @dynamic countsArray;
@property(readonly, nonatomic) unsigned long long countsArray_Count; // @dynamic countsArray_Count;
@property(copy, nonatomic) NSString *userId; // @dynamic userId;

@end

