//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@class NSNumber;

@interface SCACognacSessionEnd : SCAUserTrackedEvent
{
    NSNumber *groupSize;
    NSNumber *presenceMaxCount;
    NSNumber *durationSec;
    NSNumber *presenceDuration2OrMoreUsers;
    NSNumber *presenceDuration3OrMoreUsers;
    NSNumber *presenceDuration4OrMoreUsers;
    NSNumber *presenceDuration5OrMoreUsers;
    NSNumber *presenceDuration6OrMoreUsers;
    NSNumber *presenceDuration7OrMoreUsers;
    NSNumber *presenceDuration8OrMoreUsers;
    NSNumber *presenceDuration9OrMoreUsers;
    NSNumber *presenceDuration10OrMoreUsers;
    NSNumber *presenceDuration11OrMoreUsers;
    NSNumber *presenceDuration12OrMoreUsers;
    NSNumber *presenceDuration13OrMoreUsers;
    NSNumber *presenceDuration14OrMoreUsers;
    NSNumber *presenceDuration15OrMoreUsers;
    NSNumber *audioDurationSec;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (double)getAudioDurationSec;
- (double)getDurationSec;
- (id)getEventName;
- (long long)getEventQoS;
- (long long)getGroupSize;
- (double)getPerUserSamplingRate;
- (double)getPresenceDuration10OrMoreUsers;
- (double)getPresenceDuration11OrMoreUsers;
- (double)getPresenceDuration12OrMoreUsers;
- (double)getPresenceDuration13OrMoreUsers;
- (double)getPresenceDuration14OrMoreUsers;
- (double)getPresenceDuration15OrMoreUsers;
- (double)getPresenceDuration2OrMoreUsers;
- (double)getPresenceDuration3OrMoreUsers;
- (double)getPresenceDuration4OrMoreUsers;
- (double)getPresenceDuration5OrMoreUsers;
- (double)getPresenceDuration6OrMoreUsers;
- (double)getPresenceDuration7OrMoreUsers;
- (double)getPresenceDuration8OrMoreUsers;
- (double)getPresenceDuration9OrMoreUsers;
- (long long)getPresenceMaxCount;
- (id)initWithIntParams:(id)arg1 floatParams:(id)arg2;
- (void)setAudioDurationSec:(double)arg1;
- (void)setDurationSec:(double)arg1;
- (void)setGroupSize:(long long)arg1;
- (void)setPresenceDuration10OrMoreUsers:(double)arg1;
- (void)setPresenceDuration11OrMoreUsers:(double)arg1;
- (void)setPresenceDuration12OrMoreUsers:(double)arg1;
- (void)setPresenceDuration13OrMoreUsers:(double)arg1;
- (void)setPresenceDuration14OrMoreUsers:(double)arg1;
- (void)setPresenceDuration15OrMoreUsers:(double)arg1;
- (void)setPresenceDuration2OrMoreUsers:(double)arg1;
- (void)setPresenceDuration3OrMoreUsers:(double)arg1;
- (void)setPresenceDuration4OrMoreUsers:(double)arg1;
- (void)setPresenceDuration5OrMoreUsers:(double)arg1;
- (void)setPresenceDuration6OrMoreUsers:(double)arg1;
- (void)setPresenceDuration7OrMoreUsers:(double)arg1;
- (void)setPresenceDuration8OrMoreUsers:(double)arg1;
- (void)setPresenceDuration9OrMoreUsers:(double)arg1;
- (void)setPresenceMaxCount:(long long)arg1;

@end

