//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCAdEnableAdRenderDataStoryAdsExperimentContext : SCExperimentContext
{
    _Bool _enableAdRenderDataStoryAds;
}

@property(readonly, nonatomic) _Bool enableAdRenderDataStoryAds; // @synthesize enableAdRenderDataStoryAds=_enableAdRenderDataStoryAds;
- (id)experimentName;
- (void)setupParameters;

@end

