//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDictionary, SCAdReportTrackInfo, SCAdSnapTrackInfo, SCStoryAdTrackInfo;

@interface SCAdTrackInfo : NSObject <NSCopying>
{
    _Bool _isUnskippableAd;
    long long _adType;
    NSDictionary *_viewContext;
    SCAdSnapTrackInfo *_singleSnapTrackInfo;
    SCStoryAdTrackInfo *_storyAdTrackInfo;
    SCAdReportTrackInfo *_adReportTrackInfo;
    struct CGSize _tileSize;
    struct CGSize _screenSize;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) SCAdReportTrackInfo *adReportTrackInfo; // @synthesize adReportTrackInfo=_adReportTrackInfo;
@property(readonly, nonatomic) long long adType; // @synthesize adType=_adType;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithAdType:(long long)arg1 isUnskippableAd:(_Bool)arg2 viewContext:(id)arg3 singleSnapTrackInfo:(id)arg4 storyAdTrackInfo:(id)arg5 adReportTrackInfo:(id)arg6 tileSize:(struct CGSize)arg7 screenSize:(struct CGSize)arg8;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) _Bool isUnskippableAd; // @synthesize isUnskippableAd=_isUnskippableAd;
@property(readonly, nonatomic) struct CGSize screenSize; // @synthesize screenSize=_screenSize;
@property(readonly, copy, nonatomic) SCAdSnapTrackInfo *singleSnapTrackInfo; // @synthesize singleSnapTrackInfo=_singleSnapTrackInfo;
@property(readonly, copy, nonatomic) SCStoryAdTrackInfo *storyAdTrackInfo; // @synthesize storyAdTrackInfo=_storyAdTrackInfo;
@property(readonly, nonatomic) struct CGSize tileSize; // @synthesize tileSize=_tileSize;
@property(readonly, copy, nonatomic) NSDictionary *viewContext; // @synthesize viewContext=_viewContext;

@end

