//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString, SCAdsSubsBrandSafety;

@interface SCAdsDiscoverPage : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *feedsArray; // @dynamic feedsArray;
@property(readonly, nonatomic) unsigned long long feedsArray_Count; // @dynamic feedsArray_Count;
@property(nonatomic) _Bool hasSubsBrandSafety; // @dynamic hasSubsBrandSafety;
@property(copy, nonatomic) NSString *mixerVersion; // @dynamic mixerVersion;
@property(retain, nonatomic) SCAdsSubsBrandSafety *subsBrandSafety; // @dynamic subsBrandSafety;

@end

