//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCCollectionViewListSectionViewMoreProviding-Protocol.h"

@class NSAttributedString, NSString, NSValue, SCSnapchatterBackgroundShadowViewModel, UIColor;
@protocol SCAddFriendsViewMoreBadgingDataProvider;

@interface SCAddFriendsCollectionViewListSectionViewMoreProvider : NSObject <SCCollectionViewListSectionViewMoreProviding>
{
    NSAttributedString *_viewMoreAttributedText;
    NSAttributedString *_viewLessAttributedText;
    UIColor *_backgroundColor;
    SCSnapchatterBackgroundShadowViewModel *_shadowViewModel;
    NSValue *_preferredSize;
    id <SCAddFriendsViewMoreBadgingDataProvider> _badgingDataProvider;
}

+ (Class)viewMoreCellClass;
+ (id)viewMoreCellReuseIdentifier;
- (void).cxx_destruct;
- (id)initWithViewMoreAttributedText:(id)arg1 viewLessAttributedText:(id)arg2 backgroundColor:(id)arg3 shadowViewModel:(id)arg4 preferredSize:(id)arg5 badgingDataProvider:(id)arg6;
- (_Bool)shouldRoundLastCellInList;
- (id)viewModelForNumberOfItemsCollapsed:(long long)arg1 numberOfItemsTotal:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

