//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCMediaChatViewModel.h"

@class SCBaseMediaThumbnailViewModel;
@protocol SCAdShareMediaThumbnailViewModel;

@interface SCAdMediaChatViewModel : SCMediaChatViewModel
{
    _Bool _circularThumbnailViewEnabled;
    SCBaseMediaThumbnailViewModel<SCAdShareMediaThumbnailViewModel> *_thumbnailViewModel;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool circularThumbnailViewEnabled; // @synthesize circularThumbnailViewEnabled=_circularThumbnailViewEnabled;
- (id)createChatCellWithParentVC:(id)arg1 delegate:(id)arg2;
- (id)initWithMessage:(id)arg1 messageMetadata:(id)arg2 props:(id)arg3;
- (_Bool)isEqual:(id)arg1;
- (double)payloadHeight;
- (id)reusableCellIdentifier;
@property(retain, nonatomic) SCBaseMediaThumbnailViewModel<SCAdShareMediaThumbnailViewModel> *thumbnailViewModel; // @synthesize thumbnailViewModel=_thumbnailViewModel;
- (id)updatedMediaCardViewModel;
- (id)updatedThumbnailViewModel;

@end

