//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class UIColor;

@interface SCAddFriendsHeaderScrollShadowViewModel : NSObject <NSCopying>
{
    double _radius;
    UIColor *_shadowColor;
    struct CGSize _offset;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned long long)hash;
- (id)initWithOffset:(struct CGSize)arg1 radius:(double)arg2 shadowColor:(id)arg3;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) struct CGSize offset; // @synthesize offset=_offset;
@property(readonly, nonatomic) double radius; // @synthesize radius=_radius;
@property(readonly, copy, nonatomic) UIColor *shadowColor; // @synthesize shadowColor=_shadowColor;

@end

