//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCADirectSnapSendBase.h"

@class NSNumber, NSString, SCACreativeKitSnapMetadata;

@interface SCADirectSnapSend : SCADirectSnapSendBase
{
    NSNumber *deviceScore;
    NSNumber *withZooming;
    NSNumber *zslCapture;
    NSNumber *lightSensorValue;
    NSNumber *isFromSendTo;
    long long lensSource;
    long long filterStreak;
    long long sendSource;
    long long captureSource;
    long long lowLightStatus;
    long long nightModeState;
    long long friendshipStatus;
    long long correspondentType;
    NSString *filterLensId;
    NSString *lensOptionId;
    NSString *sceneIntelligenceRequestId;
    NSString *snapSessionId;
    NSString *filterVenueId;
    NSString *cameraApi;
    NSString *cameraSdk;
    NSString *snapId;
    NSString *rankingModelId;
    NSString *rankingId;
    NSString *serverRankingId;
    NSString *snappableFunnelId;
    NSString *captureSessionId;
    SCACreativeKitSnapMetadata *creativeKitMetadata;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getCameraApi;
- (id)getCameraSdk;
- (id)getCaptureSessionId;
- (long long)getCaptureSource;
- (long long)getCorrespondentType;
- (id)getCreativeKitMetadata;
- (long long)getDeviceScore;
- (id)getEventName;
- (long long)getEventQoS;
- (id)getFilterLensId;
- (long long)getFilterStreak;
- (id)getFilterVenueId;
- (long long)getFriendshipStatus;
- (_Bool)getIsFromSendTo;
- (id)getLensOptionId;
- (long long)getLensSource;
- (double)getLightSensorValue;
- (long long)getLowLightStatus;
- (long long)getNightModeState;
- (double)getPerUserSamplingRate;
- (id)getRankingId;
- (id)getRankingModelId;
- (id)getSceneIntelligenceRequestId;
- (long long)getSendSource;
- (id)getServerRankingId;
- (id)getSnapId;
- (id)getSnapSessionId;
- (id)getSnappableFunnelId;
- (_Bool)getWithZooming;
- (_Bool)getZslCapture;
- (id)init;
- (void)setCameraApi:(id)arg1;
- (void)setCameraSdk:(id)arg1;
- (void)setCaptureSessionId:(id)arg1;
- (void)setCaptureSource:(long long)arg1;
- (void)setCorrespondentType:(long long)arg1;
- (void)setCreativeKitMetadata:(id)arg1;
- (void)setDeviceScore:(long long)arg1;
- (void)setFilterLensId:(id)arg1;
- (void)setFilterStreak:(long long)arg1;
- (void)setFilterVenueId:(id)arg1;
- (void)setFriendshipStatus:(long long)arg1;
- (void)setIsFromSendTo:(_Bool)arg1;
- (void)setLensOptionId:(id)arg1;
- (void)setLensSource:(long long)arg1;
- (void)setLightSensorValue:(double)arg1;
- (void)setLowLightStatus:(long long)arg1;
- (void)setNightModeState:(long long)arg1;
- (void)setRankingId:(id)arg1;
- (void)setRankingModelId:(id)arg1;
- (void)setSceneIntelligenceRequestId:(id)arg1;
- (void)setSendSource:(long long)arg1;
- (void)setServerRankingId:(id)arg1;
- (void)setSnapId:(id)arg1;
- (void)setSnapSessionId:(id)arg1;
- (void)setSnappableFunnelId:(id)arg1;
- (void)setWithZooming:(_Bool)arg1;
- (void)setZslCapture:(_Bool)arg1;

@end

