//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SCAdsBudgetAbStudy : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int budgetSegmentId; // @dynamic budgetSegmentId;
@property(copy, nonatomic) NSString *experimentId; // @dynamic experimentId;
@property(nonatomic) long long studyVersion; // @dynamic studyVersion;

@end

