//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCAdProtoServeLiveStoriesExperimentContext : SCExperimentContext
{
    _Bool _enableProtoServeLiveStories;
}

@property(readonly, nonatomic) _Bool enableProtoServeLiveStories; // @synthesize enableProtoServeLiveStories=_enableProtoServeLiveStories;
- (id)experimentName;
- (void)setupParameters;

@end

