//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCAdTrackPersistenceRequest-Protocol.h"
#import "SCPersistenceRequest-Protocol.h"

@class NSDictionary, NSString, SCSnapAdsIdentifier;

@interface SCAdTrackPersistenceRequest : NSObject <SCPersistenceRequest, SCAdTrackPersistenceRequest>
{
    NSString *_url;
    NSString *_userAgent;
    long long _type;
    NSDictionary *_overrideHeaders;
    id _body;
    NSString *_key;
    NSDictionary *_cookies;
    SCSnapAdsIdentifier *_snapAdsId;
    NSString *_adType;
    unsigned long long _requestType;
    unsigned long long _adProductType;
}

+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long adProductType; // @synthesize adProductType=_adProductType;
@property(readonly, copy, nonatomic) NSString *adType; // @synthesize adType=_adType;
@property(readonly, nonatomic) id body; // @synthesize body=_body;
@property(readonly, copy, nonatomic) NSDictionary *cookies; // @synthesize cookies=_cookies;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)decodeWithFasterDecoder:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithUrl:(id)arg1 userAgent:(id)arg2 type:(long long)arg3 overrideHeaders:(id)arg4 body:(id)arg5 key:(id)arg6 cookies:(id)arg7 snapAdsId:(id)arg8 adType:(id)arg9 requestType:(unsigned long long)arg10 adProductType:(unsigned long long)arg11;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *key; // @synthesize key=_key;
@property(readonly, copy, nonatomic) NSDictionary *overrideHeaders; // @synthesize overrideHeaders=_overrideHeaders;
- (_Bool)preferFasterCoding;
@property(readonly, nonatomic) unsigned long long requestType; // @synthesize requestType=_requestType;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)setSInt32:(int)arg1 forUInt64Key:(unsigned long long)arg2;
@property(readonly, copy, nonatomic) SCSnapAdsIdentifier *snapAdsId; // @synthesize snapAdsId=_snapAdsId;
- (id)toRetriableRequest:(id)arg1;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
@property(readonly, copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(readonly, copy, nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

