//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCAddFriendsSectionHeaderBadgeProviding-Protocol.h"

@class NSString, SCLazy, SCPreferences, SCQueuePerformer;

@interface SCAddFriendsSectionHeaderBadgeDataProvider : NSObject <SCAddFriendsSectionHeaderBadgeProviding>
{
    NSString *_sectionType;
    SCLazy *_snapchattersDataFetcher;
    SCQueuePerformer *_performer;
    SCPreferences *_preferences;
    double _addedFriendsLastViewedTimestamp;
}

- (void).cxx_destruct;
- (id)initWithSnapchattersDataFetcher:(id)arg1 preferences:(id)arg2 sectionType:(id)arg3 addedFriendsLastViewedTimestamp:(double)arg4;
- (void)updateBadgeCountWithCompletionHandler:(CDUnknownBlockType)arg1;

@end

