//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@class NSNumber;

@interface SCADiscoverSnapToggleSubtitles : SCAUserTrackedEvent
{
    NSNumber *areSubtitlesTurnedOn;
    NSNumber *isUserTriggered;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)getAreSubtitlesTurnedOn;
- (id)getEventName;
- (long long)getEventQoS;
- (_Bool)getIsUserTriggered;
- (double)getPerUserSamplingRate;
- (void)setAreSubtitlesTurnedOn:(_Bool)arg1;
- (void)setIsUserTriggered:(_Bool)arg1;

@end

