//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class UIColor;

@interface SCAddFriendsShadowViewModel : NSObject <NSCopying>
{
    float _opacity;
    double _radius;
    UIColor *_color;
    struct CGSize _offset;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) UIColor *color; // @synthesize color=_color;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithOffset:(struct CGSize)arg1 radius:(double)arg2 color:(id)arg3 opacity:(float)arg4;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) struct CGSize offset; // @synthesize offset=_offset;
@property(readonly, nonatomic) float opacity; // @synthesize opacity=_opacity;
@property(readonly, nonatomic) double radius; // @synthesize radius=_radius;

@end

