//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class SCAdsInitRequest, SCAdsThirdPartyProvidedInfo;

@interface SCAdsRegisterRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasInitRequest; // @dynamic hasInitRequest;
@property(nonatomic) _Bool hasThirdPartyProvidedInfo; // @dynamic hasThirdPartyProvidedInfo;
@property(retain, nonatomic) SCAdsInitRequest *initRequest; // @dynamic initRequest;
@property(retain, nonatomic) SCAdsThirdPartyProvidedInfo *thirdPartyProvidedInfo; // @dynamic thirdPartyProvidedInfo;
@property(nonatomic) long long timestampMillis; // @dynamic timestampMillis;

@end

