//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCAUserNotTrackedEvent.h"

@class NSString;

@interface SCAImageProcessError : SCAUserNotTrackedEvent
{
    long long deviceClass;
    NSString *type;
    NSString *reason;
    NSString *source;
    NSString *processor;
    NSString *additionalInfo;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getAdditionalInfo;
- (long long)getDeviceClass;
- (id)getEventName;
- (long long)getEventQoS;
- (double)getPerUserSamplingRate;
- (id)getProcessor;
- (id)getReason;
- (id)getSource;
- (id)getType;
- (id)init;
- (void)setAdditionalInfo:(id)arg1;
- (void)setDeviceClass:(long long)arg1;
- (void)setProcessor:(id)arg1;
- (void)setReason:(id)arg1;
- (void)setSource:(id)arg1;
- (void)setType:(id)arg1;

@end

