//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCAPIAuth : NSObject
{
}

+ (id)appName;
+ (id)appVersion;
+ (id)authenticationParametersForEndpoint:(id)arg1 authToken:(id)arg2 username:(id)arg3 parameters:(id)arg4 deviceIdManager:(id)arg5;
+ (id)authenticationParametersForUserWithToken:(id)arg1 username:(id)arg2 withDeviceInfo:(_Bool)arg3 deviceIdManager:(id)arg4;
+ (id)requestTokenForUserToken:(id)arg1 timestamp:(id)arg2;
+ (id)schemeName;
+ (id)staticFSNAuthToken;
+ (id)userAgentHeader;
+ (id)versionName;

@end

