//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NamedEvent-Protocol.h"

@class NSString;

@interface SCAPageInstanceInfo : NSObject <NamedEvent, NSCopying>
{
    long long pageType;
    NSString *pageId;
    NSString *pageTypeSpecific;
    NSString *pageSessionId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getEventName;
- (long long)getEventQoS;
- (id)getPageId;
- (id)getPageSessionId;
- (long long)getPageType;
- (id)getPageTypeSpecific;
- (double)getPerEventSamplingRate;
- (double)getPerUserSamplingRate;
- (id)init;
- (void)setPageId:(id)arg1;
- (void)setPageSessionId:(id)arg1;
- (void)setPageType:(long long)arg1;
- (void)setPageTypeSpecific:(id)arg1;

@end

