//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCARegistrationUserTrackedEvent.h"

@class NSString;

@interface SCARegistrationPageReach : SCARegistrationUserTrackedEvent
{
    long long page;
    NSString *longClientId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getEventName;
- (long long)getEventQoS;
- (id)getLongClientId;
- (long long)getPage;
- (double)getPerUserSamplingRate;
- (id)init;
- (void)setLongClientId:(id)arg1;
- (void)setPage:(long long)arg1;

@end

