//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SCSessionRequestManager;

@interface SCArcadiaFetcher : NSObject
{
    SCSessionRequestManager *_requestManager;
}

- (void).cxx_destruct;
- (id)_fetchForEndpoint:(id)arg1 params:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_parseObjectsData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)fetchAndParseCategoriesReturningEmpty:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)fetchAndParseObjectsForCategoryWithName:(id)arg1 limit:(unsigned long long)arg2 offset:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;
- (id)fetchCategoriesWithCompletion:(CDUnknownBlockType)arg1;
- (id)fetchObjectsForCategoryWithName:(id)arg1 limit:(unsigned long long)arg2 offset:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;
- (id)initWithRequestManager:(id)arg1;
@property(readonly, nonatomic) SCSessionRequestManager *requestManager; // @synthesize requestManager=_requestManager;
- (id)searchAndParseObjectsForQuery:(id)arg1 limit:(unsigned long long)arg2 cursor:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)searchForQuery:(id)arg1 limit:(unsigned long long)arg2 cursor:(id)arg3 completion:(CDUnknownBlockType)arg4;

@end

