//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCOverlayFilterView.h"

@class UIImageView;

@interface SCBatteryFilterView : SCOverlayFilterView
{
    UIImageView *_imageView;
    long long _orientation;
}

- (void).cxx_destruct;
- (id)displayName;
- (struct CGSize)imageSize;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1 config:(id)arg2 userSession:(id)arg3;
- (struct CGPoint)landscapeImageCenter;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (struct CGPoint)portraitImageCenter;

@end

