//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCMultiSnapV2PlayerHandler-Protocol.h"

@class NSArray, NSIndexPath;

@protocol SCBatchCapturePlayerHandler <SCMultiSnapV2PlayerHandler>
- (void)batchCaptureDidDeleteSnapAtIndexPath:(NSIndexPath *)arg1;
- (void)batchCaptureDidUpdateImageSegmentDuration:(CDStruct_1b6d18a9)arg1 atIndex:(long long)arg2;
- (void)batchCaptureSetSnapEnabled:(_Bool)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)batchCaptureStopPlayingSnapAtIndexPath:(NSIndexPath *)arg1 andSeekSmoothlyToTime:(CDStruct_1b6d18a9)arg2;
- (void)batchCaptureUpdateMultiSnapTimeRanges:(NSArray *)arg1 includesDeletion:(_Bool)arg2 forSegmentAtIndex:(long long)arg3;
@end

