//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCServicesExposer, SCSnapchatterServices;

@interface SCBitmojiFriendInfoServicesEntryPoint : SCEntryPoint
{
    SCSnapchatterServices *_snapchatterServices;
    SCServicesExposer *_bitmojiFriendInfoServicesExposer;
}

- (void).cxx_destruct;
- (id)_friendAvatarProvider;
- (void)begin;
@property(retain, nonatomic) SCServicesExposer *bitmojiFriendInfoServicesExposer; // @synthesize bitmojiFriendInfoServicesExposer=_bitmojiFriendInfoServicesExposer;
@property(nonatomic) __weak SCSnapchatterServices *snapchatterServices; // @synthesize snapchatterServices=_snapchatterServices;

@end

