//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@interface SCBitmojiImageMetadata : NSObject <NSCopying>
{
    _Bool _brandedOutfitReplaced;
}

@property(readonly, nonatomic) _Bool brandedOutfitReplaced; // @synthesize brandedOutfitReplaced=_brandedOutfitReplaced;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithBrandedOutfitReplaced:(_Bool)arg1;
- (_Bool)isEqual:(id)arg1;

@end

