//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "SCBloopsPickerCell-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class AVPlayerLooper, NSString, SCPlayerView, SCQueuePlayer, UIScrollView;
@protocol SCBloopsPreviewsEmptyCellDelegate;

@interface SCBloopsPreviewsEmptyCell : UICollectionViewCell <UIScrollViewDelegate, SCBloopsPickerCell>
{
    UIScrollView *_scrollView;
    SCPlayerView *_playerView;
    SCQueuePlayer *_player;
    AVPlayerLooper *_playerLooper;
    double _topMargin;
    id <SCBloopsPreviewsEmptyCellDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_createBloopViewClicked:(id)arg1;
- (void)_loadVideo;
- (void)_updateScrollViewFrame;
@property(nonatomic) __weak id <SCBloopsPreviewsEmptyCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)enterVisibleState;
- (void)exitVisibleState;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tuneViewDueToDrawerSizeChanged:(double)arg1 toolbarHeight:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

