//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIScrollView;
@protocol SCBloopsPreviewsViewInput;

@protocol SCBloopsPreviewsViewOutput <NSObject>
- (void)bloopsPreviews:(id <SCBloopsPreviewsViewInput>)arg1 didDoubleTapBloopAtIndex:(unsigned long long)arg2;
- (void)bloopsPreviews:(id <SCBloopsPreviewsViewInput>)arg1 didLongTapBloopAtIndex:(unsigned long long)arg2;
- (void)bloopsPreviews:(id <SCBloopsPreviewsViewInput>)arg1 didSecondTapOnBloopAtIndex:(unsigned long long)arg2;
- (void)bloopsPreviews:(id <SCBloopsPreviewsViewInput>)arg1 didTapOnBloopAtIndex:(unsigned long long)arg2;
- (void)bloopsPreviews:(id <SCBloopsPreviewsViewInput>)arg1 willBeginDragging:(UIScrollView *)arg2;
- (void)bloopsPreviewsDidCancelSelection:(id <SCBloopsPreviewsViewInput>)arg1;
- (void)bloopsPreviewsSelectedBloopDidEndDisplay:(id <SCBloopsPreviewsViewInput>)arg1;
@end

