//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class SCBorderOverlayCornerView;

@interface SCBorderOverlayView : UIView
{
    UIView *_topBorderView;
    UIView *_leftBorderView;
    UIView *_bottomBorderView;
    UIView *_rightBorderView;
    SCBorderOverlayCornerView *_topLeftCornerView;
    SCBorderOverlayCornerView *_topRightCornerView;
    SCBorderOverlayCornerView *_bottomLeftCornerView;
    SCBorderOverlayCornerView *_bottomRightCornerView;
    double _topBorderWidth;
    double _leftBorderWidth;
    double _bottomBorderWidth;
    double _rightBorderWidth;
    double _topLeftCornerRadius;
    double _topRightCornerRadius;
    double _bottomLeftCornerRadius;
    double _bottomRightCornerRadius;
}

- (void).cxx_destruct;
@property(nonatomic) double bottomBorderWidth; // @synthesize bottomBorderWidth=_bottomBorderWidth;
@property(nonatomic) double bottomLeftCornerRadius; // @synthesize bottomLeftCornerRadius=_bottomLeftCornerRadius;
@property(nonatomic) double bottomRightCornerRadius; // @synthesize bottomRightCornerRadius=_bottomRightCornerRadius;
@property(nonatomic) struct CGRect contentBounds;
- (void)layoutSubviews;
@property(nonatomic) double leftBorderWidth; // @synthesize leftBorderWidth=_leftBorderWidth;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(nonatomic) double rightBorderWidth; // @synthesize rightBorderWidth=_rightBorderWidth;
- (void)setAllCornerRadii:(double)arg1;
@property(nonatomic) double topBorderWidth; // @synthesize topBorderWidth=_topBorderWidth;
@property(nonatomic) double topLeftCornerRadius; // @synthesize topLeftCornerRadius=_topLeftCornerRadius;
@property(nonatomic) double topRightCornerRadius; // @synthesize topRightCornerRadius=_topRightCornerRadius;

@end

