//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCCacheRequestOptions : NSObject
{
    unsigned long long _deliveryMode;
    unsigned long long _imageVersion;
    struct CGSize _requestTargetSize;
}

+ (id)createRequestWithOptions:(unsigned long long)arg1 imageVersion:(unsigned long long)arg2;
@property(nonatomic) unsigned long long deliveryMode; // @synthesize deliveryMode=_deliveryMode;
@property(nonatomic) unsigned long long imageVersion; // @synthesize imageVersion=_imageVersion;
@property(nonatomic) struct CGSize requestTargetSize; // @synthesize requestTargetSize=_requestTargetSize;

@end

