//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class SCCameraOverlayView;

@interface SCCameraToolbarBackgroundView : UIView
{
    SCCameraOverlayView *_containerView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak SCCameraOverlayView *containerView; // @synthesize containerView=_containerView;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

