//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, FBKVOController, SCQueuePerformer;
@protocol SCCapturerBufferedVideoWriterDelegate;

@interface SCCapturerBufferedVideoWriter : NSObject
{
    SCQueuePerformer *_performer;
    id <SCCapturerBufferedVideoWriterDelegate> _delegate;
    FBKVOController *_observeController;
    AVAssetWriter *_assetWriter;
    AVAssetWriterInput *_audioWriterInput;
    AVAssetWriterInput *_videoWriterInput;
    AVAssetWriterInputPixelBufferAdaptor *_pixelBufferAdaptor;
    struct __CVPixelBufferPool *_currentPixelBufferPool;
    struct CGSize _currentPixelBufferSize;
    struct opaqueCMBufferQueue *_videoBufferQueue;
    struct opaqueCMBufferQueue *_audioBufferQueue;
}

+ (void)warmupInputsWithOutputSettings:(id)arg1;
- (void).cxx_destruct;
- (void)_appendVideoSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (struct __CVBuffer *)_croppedPixelBufferWithInputPixelBuffer:(struct __CVBuffer *)arg1;
- (struct __CVPixelBufferPool *)_pixelBufferPoolWithPixelBufferSize:(struct CGSize)arg1;
- (void)appendAudioSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)appendVideoSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)assetWriterStatusChanged:(id)arg1;
- (void)cancelWriting;
- (void)cleanUp;
- (void)dealloc;
- (void)finishWritingAtSourceTime:(CDStruct_1b6d18a9)arg1 withCompletionHanlder:(CDUnknownBlockType)arg2;
- (id)initWithPerformer:(id)arg1 outputURL:(id)arg2 delegate:(id)arg3 error:(id *)arg4;
- (_Bool)prepareWritingWithOutputSettings:(id)arg1;
- (_Bool)startWritingAtSourceTime:(CDStruct_1b6d18a9)arg1;

@end

