//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCStateTransitionPayload.h"

@class NSString, NSURL, SCAudioConfiguration, SCManagedVideoCapturerOutputSettings;

@interface SCCapturePrepareRecordingStateTransitionPayload : SCStateTransitionPayload
{
    SCManagedVideoCapturerOutputSettings *_outputSettings;
    SCAudioConfiguration *_configuration;
    double _maxDuration;
    NSURL *_fileURL;
    NSString *_captureSessionID;
    CDUnknownBlockType _block;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(readonly, nonatomic) NSString *captureSessionID; // @synthesize captureSessionID=_captureSessionID;
@property(readonly, nonatomic) SCAudioConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
- (id)initWithFromState:(unsigned long long)arg1 toState:(unsigned long long)arg2 outputSettings:(id)arg3 audioConfiguration:(id)arg4 maxDuration:(double)arg5 fileURL:(id)arg6 captureSessionID:(id)arg7 completionHandler:(CDUnknownBlockType)arg8;
@property(readonly, nonatomic) double maxDuration; // @synthesize maxDuration=_maxDuration;
@property(readonly, nonatomic) SCManagedVideoCapturerOutputSettings *outputSettings; // @synthesize outputSettings=_outputSettings;

@end

