//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIGestureRecognizer, UIPanGestureRecognizer, UIPinchGestureRecognizer;

@protocol SCCameraGestureResponder <NSObject>

@optional
- (void)forwardCameraOverlayTapGesture:(UIGestureRecognizer *)arg1;
- (void)forwardCameraTimerGesture:(UIGestureRecognizer *)arg1;
- (void)forwardLongPressGesture:(UIGestureRecognizer *)arg1;
- (void)forwardPanGesture:(UIPanGestureRecognizer *)arg1;
- (void)forwardPinchGesture:(UIPinchGestureRecognizer *)arg1;
- (_Bool)shouldBlockTouchAtPoint:(struct CGPoint)arg1;
@end

