//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCCaptureWorkflowPageRouter-Protocol.h"

@class NSString, SCCameraViewController, SCCaptureWorkflowSwipeTransitionCoordinatorDelegate, SCSwipeTransitionCoordinator, UINavigationController;
@protocol SCCameraViewContaining;

@interface SCCaptureWorkflowNavigationPageRouter : NSObject <SCCaptureWorkflowPageRouter>
{
    id <SCCameraViewContaining> _cameraViewContainer;
    SCCameraViewController *_cameraViewController;
    UINavigationController *_navigationController;
    SCSwipeTransitionCoordinator *_cameraTransitionCoordinator;
    SCCaptureWorkflowSwipeTransitionCoordinatorDelegate *_coordinatorDelegate;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SCCameraViewController *cameraViewController; // @synthesize cameraViewController=_cameraViewController;
- (void)dismissCameraWithCompletion:(CDUnknownBlockType)arg1;
- (void)dismissPreview:(id)arg1;
- (id)initWithCameraViewContainer:(id)arg1 featureProvider:(struct SCFeatureProvider *)arg2 lensDataProvider:(id)arg3;
- (_Bool)shouldDismissWorkflowOnBackground;
- (void)showCameraWithDelegate:(id)arg1 cameraViewConfigurationController:(id)arg2 completion:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

