//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCCertificateTrust : NSObject
{
}

+ (CDUnknownBlockType)authChallengeBlock;
+ (id)certsExpirationDate;
+ (id)def1;
+ (void)didReceiveChallenge:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (id)pinnedCertsPublicKeyHashes;

@end

