//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString, SCFriendsFeedFetchContext;
@protocol SOJUMessage;

@protocol SCChatMessageReceiveListener <NSObject>
- (void)didReceiveMischiefs:(NSDictionary *)arg1 conversations:(NSDictionary *)arg2 username:(NSString *)arg3 fetchContext:(SCFriendsFeedFetchContext *)arg4;
- (void)didReceiveWireMessage:(id <SOJUMessage>)arg1;
@end

