//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSString;

@protocol SCChatURLMediaCardContent <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSString *cacheId;
@property(readonly, nonatomic) long long metadataLoadState;
@property(readonly, copy, nonatomic) NSString *subtitle;
@property(readonly, nonatomic) long long thumbnailLoadState;
@property(readonly, copy, nonatomic) NSString *thumbnailUrl;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, copy, nonatomic) NSString *urlString;
@end

