//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCTraceEnabled-Protocol.h"

@class NSArray, NSMutableDictionary, NSString, SCLazy, UITextInputMode, UIView;
@protocol SCChatKeyboardManagerDataSource;

@interface SCChatKeyboardManager : NSObject <SCTraceEnabled>
{
    NSMutableDictionary *_inputModesSnapshotMapping;
    NSArray *_inputModes;
    SCLazy *_flattenedRenderStrategy;
    _Bool _isShowingKeyboard;
    id <SCChatKeyboardManagerDataSource> _dataSource;
    double _keyboardHeight;
    UIView *_keyboardSnapshotView;
    UITextInputMode *_lastKnownInputMode;
}

- (void).cxx_destruct;
- (id)_getCurrentInputModeForTextField:(id)arg1;
- (id)_snapshotForCurrentInputModeIfAvailableAllowsEmoji:(_Bool)arg1 textInputView:(id)arg2 inputMode:(id)arg3;
- (void)_snapshotKeyboardIfNeededForInputView:(id)arg1 inputMode:(id)arg2;
- (id)_snapshottedKeyboardView:(id)arg1;
- (_Bool)addKeyboardSnapshotToView:(id)arg1 isExiting:(_Bool)arg2;
- (_Bool)canSnapshotTextInputView:(id)arg1;
@property(nonatomic) __weak id <SCChatKeyboardManagerDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (id)initWithFlattenedRenderStrategy:(id)arg1;
@property(readonly, nonatomic, getter=isKeyboardSnapshotVisible) _Bool keyboardSnapshotVisible;
@property(nonatomic) _Bool isShowingKeyboard; // @synthesize isShowingKeyboard=_isShowingKeyboard;
@property(readonly, nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(readonly, nonatomic) double keyboardSnapshotHeight;
@property(retain, nonatomic) UIView *keyboardSnapshotView; // @synthesize keyboardSnapshotView=_keyboardSnapshotView;
- (void)keyboardWillShow:(id)arg1;
@property(retain, nonatomic) UITextInputMode *lastKnownInputMode; // @synthesize lastKnownInputMode=_lastKnownInputMode;
- (void)removeKeyboardSnapshot;
- (void)snapshotKeyboardIfNeeded;
- (void)textInputCurrentInputModeDidChange:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

