//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, SCChatSDKActionContext, UIView;

@protocol SCChatMessageRenderer
@property(nonatomic) __weak SCChatSDKActionContext *actionContext;
- (UIView *)createContentView;
- (void)didEndDisplayingContentView:(UIView *)arg1;
- (void)prepareContentViewForReuse:(UIView *)arg1;
- (NSString *)reuseIdentifier;
- (void)setupContentView:(UIView *)arg1;
- (struct CGSize)sizeThatFits:(double)arg1;
- (void)willDisplayContentView:(UIView *)arg1;
@end

