//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDictionary, NSSet;

@interface SCChatSendBlockInfo : NSObject <NSCopying>
{
    NSDictionary *_sendingBlockIds;
    NSSet *_failedAtLeastOnceMessages;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy, nonatomic) NSSet *failedAtLeastOnceMessages; // @synthesize failedAtLeastOnceMessages=_failedAtLeastOnceMessages;
- (unsigned long long)hash;
- (id)initWithSendingBlockIds:(id)arg1 failedAtLeastOnceMessages:(id)arg2;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *sendingBlockIds; // @synthesize sendingBlockIds=_sendingBlockIds;

@end

