//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SCAlertView, SCChatEraseMessageController;

@protocol SCChatEraseMessageControllerDelegate
- (void)eraseMessageController:(SCChatEraseMessageController *)arg1 didDismissAlertView:(SCAlertView *)arg2;
- (void)eraseMessageControllerWillDisplayAlertView:(SCChatEraseMessageController *)arg1;
@end

