//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, SCCognacAppInstancesAppInstanceScope;

@interface SCCognacAppInstancesAppInstance : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *appId; // @dynamic appId;
@property(nonatomic) _Bool hasScope; // @dynamic hasScope;
@property(copy, nonatomic) NSString *id_p; // @dynamic id_p;
@property(retain, nonatomic) SCCognacAppInstancesAppInstanceScope *scope; // @dynamic scope;

@end

