//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class SCCognacAppInstancesAppInstanceScope;

@interface SCCognacAppInstancesGetChatDockRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCCognacAppInstancesAppInstanceScope *appInstanceScope; // @dynamic appInstanceScope;
@property(nonatomic) _Bool hasAppInstanceScope; // @dynamic hasAppInstanceScope;

@end

