//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface SCCognacOperaSessionParticipantInfoBuilder : NSObject
{
    NSArray *_participantHistory;
    _Bool _hasCurrentParticipants;
}

+ (id)cognacOperaSessionParticipantInfo;
+ (id)cognacOperaSessionParticipantInfoFromExistingCognacOperaSessionParticipantInfo:(id)arg1;
- (void).cxx_destruct;
- (id)build;
- (id)withHasCurrentParticipants:(_Bool)arg1;
- (id)withParticipantHistory:(id)arg1;

@end

