//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSAttributedString, SCCognacScoreShareMessageCardActionContainerViewModel, SCNetworkImage;

@interface SCCognacScoreShareMessageCardViewModel : NSObject <NSCopying>
{
    _Bool _isPreview;
    SCNetworkImage *_iconImage;
    SCNetworkImage *_coverImage;
    NSAttributedString *_titleText;
    SCCognacScoreShareMessageCardActionContainerViewModel *_actionContainerViewModel;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) SCCognacScoreShareMessageCardActionContainerViewModel *actionContainerViewModel; // @synthesize actionContainerViewModel=_actionContainerViewModel;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy, nonatomic) SCNetworkImage *coverImage; // @synthesize coverImage=_coverImage;
- (unsigned long long)hash;
@property(readonly, copy, nonatomic) SCNetworkImage *iconImage; // @synthesize iconImage=_iconImage;
- (id)initWithIconImage:(id)arg1 coverImage:(id)arg2 titleText:(id)arg3 actionContainerViewModel:(id)arg4 isPreview:(_Bool)arg5;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) _Bool isPreview; // @synthesize isPreview=_isPreview;
@property(readonly, copy, nonatomic) NSAttributedString *titleText; // @synthesize titleText=_titleText;

@end

