//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCComposerView.h"

@class NSString;

@interface SCComposerComponentContainerView : SCComposerView
{
    NSString *_componentPath;
}

- (void).cxx_destruct;
- (id)componentPath;
- (id)initWithComponentPath:(id)arg1 owner:(id)arg2;

@end

