//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SCCustomStickerDeletionBuilder : NSObject
{
    NSString *_objectID;
    int _numSyncFailed;
    NSString *_stickerId;
}

+ (id)withCustomStickerDeletion:(id)arg1;
- (void).cxx_destruct;
- (id)build;
- (id)setNumSyncFailed:(int)arg1;
- (id)setObjectID:(id)arg1;
- (id)setStickerId:(id)arg1;

@end

