//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface SCDDMLTokenBuilder : NSObject
{
    NSString *_token;
    NSDate *_expiration;
}

+ (id)withDDMLToken:(id)arg1;
- (void).cxx_destruct;
- (id)build;
- (id)setExpiration:(id)arg1;
- (id)setToken:(id)arg1;

@end

