//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIViewControllerAnimatedTransitioning-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSString, UIPercentDrivenInteractiveTransition;
@protocol SCDelegatedPresentedDelegate, SCDelegatedPresentingDelegate;

@interface SCDelegatedTransitioningDelegate : NSObject <UIViewControllerAnimatedTransitioning, UIViewControllerTransitioningDelegate>
{
    CDUnknownBlockType _onCancelledBlock;
    CDUnknownBlockType _onFinishedBlock;
    double _latestPercentComplete;
    _Bool _sendsAppearanceMethods;
    _Bool _ensurePresentingViewControllerAnimation;
    double _duration;
    id <SCDelegatedPresentingDelegate> _presentingDelegate;
    id <SCDelegatedPresentedDelegate> _presentedDelegate;
    UIPercentDrivenInteractiveTransition *_interactiveTransition;
}

- (void).cxx_destruct;
- (void)_continueAnimation:(id)arg1 forKey:(id)arg2 inLayer:(id)arg3;
- (id)_implicitAnimationModels;
- (void)_performDismissalAnimations;
- (void)_performPresentationAnimations;
- (void)_reverseAnimation:(id)arg1 forKey:(id)arg2 inLayer:(id)arg3;
- (void)animateTransition:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)cancelInteractiveTransition;
- (void)cancelInteractiveTransitionWithCompletion:(CDUnknownBlockType)arg1;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) _Bool ensurePresentingViewControllerAnimation; // @synthesize ensurePresentingViewControllerAnimation=_ensurePresentingViewControllerAnimation;
- (void)finishInteractiveTransition;
- (void)finishInteractiveTransitionWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)interactionControllerForPresentation:(id)arg1;
@property(retain, nonatomic) UIPercentDrivenInteractiveTransition *interactiveTransition; // @synthesize interactiveTransition=_interactiveTransition;
@property(nonatomic) __weak id <SCDelegatedPresentedDelegate> presentedDelegate; // @synthesize presentedDelegate=_presentedDelegate;
@property(nonatomic) __weak id <SCDelegatedPresentingDelegate> presentingDelegate; // @synthesize presentingDelegate=_presentingDelegate;
@property(nonatomic) _Bool sendsAppearanceMethods; // @synthesize sendsAppearanceMethods=_sendsAppearanceMethods;
- (double)transitionDuration:(id)arg1;
- (void)updateInteractiveTransition:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

