//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, SCDiscoverFeedPublisherSnapTileBadge;

@interface SCDiscoverFeedPublisherSnapTile : NSObject <NSCopying>
{
    NSString *_titleId;
    NSString *_headline;
    NSString *_imageURL;
    NSString *_logoURL;
    NSString *_videoThumbnailURL;
    NSString *_videoThumbnailFirstFrameURL;
    long long _logoLocationType;
    NSString *_logoReadStateOverlayColor;
    NSString *_showSubtitle;
    long long _showProgress;
    NSString *_bitmojiTileTemplateId;
    SCDiscoverFeedPublisherSnapTileBadge *_tileBadge;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *bitmojiTileTemplateId; // @synthesize bitmojiTileTemplateId=_bitmojiTileTemplateId;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
@property(readonly, copy, nonatomic) NSString *headline; // @synthesize headline=_headline;
@property(readonly, copy, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
- (id)initWithTitleId:(id)arg1 headline:(id)arg2 imageURL:(id)arg3 logoURL:(id)arg4 videoThumbnailURL:(id)arg5 videoThumbnailFirstFrameURL:(id)arg6 logoLocationType:(long long)arg7 logoReadStateOverlayColor:(id)arg8 showSubtitle:(id)arg9 showProgress:(long long)arg10 bitmojiTileTemplateId:(id)arg11 tileBadge:(id)arg12;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) long long logoLocationType; // @synthesize logoLocationType=_logoLocationType;
@property(readonly, copy, nonatomic) NSString *logoReadStateOverlayColor; // @synthesize logoReadStateOverlayColor=_logoReadStateOverlayColor;
@property(readonly, copy, nonatomic) NSString *logoURL; // @synthesize logoURL=_logoURL;
@property(readonly, nonatomic) long long showProgress; // @synthesize showProgress=_showProgress;
@property(readonly, copy, nonatomic) NSString *showSubtitle; // @synthesize showSubtitle=_showSubtitle;
@property(readonly, copy, nonatomic) SCDiscoverFeedPublisherSnapTileBadge *tileBadge; // @synthesize tileBadge=_tileBadge;
@property(readonly, copy, nonatomic) NSString *titleId; // @synthesize titleId=_titleId;
@property(readonly, copy, nonatomic) NSString *videoThumbnailFirstFrameURL; // @synthesize videoThumbnailFirstFrameURL=_videoThumbnailFirstFrameURL;
@property(readonly, copy, nonatomic) NSString *videoThumbnailURL; // @synthesize videoThumbnailURL=_videoThumbnailURL;
- (id)xLogObjectInfo;

@end

