//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString, SCDiscoverFeedPublisherStoryProgressBarViewModel, SCDiscoverFeedTileBadgeViewModel;

@interface SCDiscoverFeedPublisherStoryLabelOverlayViewModelBuilder : NSObject
{
    NSAttributedString *_title;
    NSAttributedString *_subtitle;
    SCDiscoverFeedPublisherStoryProgressBarViewModel *_progressBarViewModel;
    SCDiscoverFeedTileBadgeViewModel *_tileBadge;
    long long _tileBadgePosition;
}

+ (id)discoverFeedPublisherStoryLabelOverlayViewModel;
+ (id)discoverFeedPublisherStoryLabelOverlayViewModelFromExistingDiscoverFeedPublisherStoryLabelOverlayViewModel:(id)arg1;
- (void).cxx_destruct;
- (id)build;
- (id)withProgressBarViewModel:(id)arg1;
- (id)withSubtitle:(id)arg1;
- (id)withTileBadge:(id)arg1;
- (id)withTileBadgePosition:(long long)arg1;
- (id)withTitle:(id)arg1;

@end

