//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSAttributedString, NSString, SCActionModel, UIColor;

@interface SCDiscoverFeedGamesViewMoreViewModel : NSObject <NSCopying>
{
    _Bool _isLoading;
    NSAttributedString *_viewMoreAttributedString;
    UIColor *_backgroundColor;
    SCActionModel *_tapActionModel;
    NSString *_accessibilityLabel;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *accessibilityLabel; // @synthesize accessibilityLabel=_accessibilityLabel;
@property(readonly, copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithViewMoreAttributedString:(id)arg1 backgroundColor:(id)arg2 isLoading:(_Bool)arg3 tapActionModel:(id)arg4 accessibilityLabel:(id)arg5;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(readonly, copy, nonatomic) SCActionModel *tapActionModel; // @synthesize tapActionModel=_tapActionModel;
@property(readonly, copy, nonatomic) NSAttributedString *viewMoreAttributedString; // @synthesize viewMoreAttributedString=_viewMoreAttributedString;

@end

