//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCObserver-Protocol.h"

@protocol NSObject, SCObserver;

@interface SCDistinctUntilChangedObserver : NSObject <SCObserver>
{
    id <SCObserver> _observer;
    id <NSObject> _lastValue;
    struct mutex _mutex;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)complete;
- (id)initWithObserver:(id)arg1;
- (void)next:(id)arg1;

@end

