//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCOperaSubscribeButtonLayerViewControllerSubscribeStatusHandler-Protocol.h"
#import "SCUpdateListener-Protocol.h"

@class NSString, SCDiscoverFeedStory, SCUserSession;

@interface SCDiscoverFeedStorySubscribeStatusHandler : NSObject <SCUpdateListener, SCOperaSubscribeButtonLayerViewControllerSubscribeStatusHandler>
{
    SCUserSession *_userSession;
    SCDiscoverFeedStory *_cheetahStory;
    CDUnknownBlockType _subscriptionUpdateCallback;
}

- (void).cxx_destruct;
- (void)_callUpdateCallback:(_Bool)arg1;
- (void)didUpdateWithAnnouncerIdentifier:(id)arg1;
- (id)initWithUserSession:(id)arg1 cheetahStory:(id)arg2;
- (_Bool)isSubscribed;
- (void)setCallbackForSubscriptionUpdate:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

