//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SCLazy;
@protocol SCEventAnnouncing;

@interface SCDiscoverFeedBaseServices : NSObject
{
    SCLazy *_collapseManager;
    id <SCEventAnnouncing> _eventsAnnouncer;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SCLazy *collapseManager; // @synthesize collapseManager=_collapseManager;
@property(readonly, nonatomic) id <SCEventAnnouncing> eventsAnnouncer; // @synthesize eventsAnnouncer=_eventsAnnouncer;
- (id)initWithCollapseManager:(id)arg1 eventAnnouncer:(id)arg2;

@end

