//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView;
@protocol SCDrawingViewCommon;

@protocol SCDrawingViewCommonDelegate <NSObject>
- (void)drawingView:(UIView<SCDrawingViewCommon> *)arg1 didEndDrawingWithStrokeSize:(double)arg2 isResized:(_Bool)arg3;
- (void)drawingView:(UIView<SCDrawingViewCommon> *)arg1 didMoveToPoint:(struct CGPoint)arg2;
- (void)drawingViewDidFinishPinchResize:(UIView<SCDrawingViewCommon> *)arg1;
- (void)drawingViewDidStartDrawing:(UIView<SCDrawingViewCommon> *)arg1;
- (void)drawingViewDidStartPinchResize:(UIView<SCDrawingViewCommon> *)arg1;
@end

