//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SCViewModelConfigurable-Protocol.h"

@class NSString, SCBottomBorderedView, SCButton, SIGActivityIndicatorView, SIGPullToRefreshView, UICollectionView, UILabel;
@protocol SCDynamicLayoutDelegate;

@interface SCDynamicLayoutView : UIView <SCViewModelConfigurable>
{
    SIGPullToRefreshView *_pullToRefreshView;
    SIGActivityIndicatorView *_pullToRefreshActivityIndicatorView;
    SCBottomBorderedView *_header;
    UILabel *_titleLabel;
    SCButton *_backButton;
    id _viewModel;
    id <SCDynamicLayoutDelegate> _delegate;
    UICollectionView *_contentCollectionView;
}

- (void).cxx_destruct;
- (void)_didTapBackButton;
@property(readonly, nonatomic) UICollectionView *contentCollectionView; // @synthesize contentCollectionView=_contentCollectionView;
@property(nonatomic) __weak id <SCDynamicLayoutDelegate> delegate; // @synthesize delegate=_delegate;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithDefaultCollectionViewLayout:(id)arg1;
- (void)layoutSubviews;
- (id)pullToRefreshActivityIndicatorView;
- (id)pullToRefreshView;
@property(retain, nonatomic) id viewModel; // @synthesize viewModel=_viewModel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

