//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCAnnouncing-Protocol.h"

@protocol SCEventListener;

@protocol SCEventAnnouncing <SCAnnouncing>
- (void)addListener:(id <SCEventListener>)arg1;
- (void)removeListener:(id <SCEventListener>)arg1;
@end

