//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITapGestureRecognizer.h>

@class NSTimer;

@interface SCFastDoubleTapGestureRecognizer : UITapGestureRecognizer
{
    NSTimer *_timer;
    struct CGPoint _beginTouchLocation;
}

- (void).cxx_destruct;
- (double)_maximumIntervalBetweenSuccessiveTaps;
- (double)_maximumIntervalForCancellingDoubleTap;
- (void)_setGestureRecognizerStateCancelled;
- (_Bool)canBePreventedByGestureRecognizer:(id)arg1;
- (_Bool)canPreventGestureRecognizer:(id)arg1;
- (void)dealloc;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;

@end

