//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCFeedHeaderPromptViewModelProviding-Protocol.h"

@class SCLazy;
@protocol SCPerforming;

@interface SCFeedHeaderPromptViewModelProvider : NSObject <SCFeedHeaderPromptViewModelProviding>
{
    SCLazy *_lazyPromptQualificationProvider;
    SCLazy *_lazyPromptDataCoordinator;
    id <SCPerforming> _performer;
}

- (void).cxx_destruct;
- (void)_fetchAvailablePromptViewModelWithCompletionQueue:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)_firstAvailablePromptWithSettingsEntity:(id)arg1 rankedPromptV2ProtoSettings:(id)arg2 syncStatesEntity:(id)arg3 promptV2ProtoSyncStates:(id)arg4 completionQueue:(id)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (_Bool)_isWithinCooldownWithPromptSetting:(id)arg1 promptSyncState:(id)arg2 settingsEntity:(id)arg3 syncStatesEntity:(id)arg4;
- (_Bool)_qualifiedForBirthdayPartyPrompt;
- (_Bool)_qualifiedForEmailVerificationPrompt;
- (_Bool)_qualifiedForNotificationPermissionPrompt;
- (_Bool)_qualifiedForPhoneVerificationPrompt;
- (_Bool)_shouldShowPromptWithPromptSetting:(id)arg1 promptSyncState:(id)arg2 settingsEntity:(id)arg3 syncStatesEntity:(id)arg4;
- (void)fetchAvailablePromptViewModelWithCompletionQueue:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)initWithLazyPromptQualificationProvider:(id)arg1 lazyPromptDataCoordinator:(id)arg2;

@end

