//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCFideliusBatchExecutor.h"

@class NSMutableSet;

@interface SCFideliusBatchInitRetryExecutor : SCFideliusBatchExecutor
{
    NSMutableSet *pendingMessageIds;
}

- (void).cxx_destruct;
- (id)_endpoint;
- (void)_onRequestMade;
- (_Bool)_shouldDedup:(id)arg1;
- (id)_toSubmitToJson:(id)arg1;
- (id)initWithUserSession:(id)arg1 useFakePerformer:(_Bool)arg2;
- (const char *)queueLabel;

@end

