//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SCFriendUnifiedProfileMessageNotificationActionHandler;

@protocol SCFriendUnifiedProfileMessageNotificationActionHandlerDelegate
- (void)messageNotificationActionHandler:(SCFriendUnifiedProfileMessageNotificationActionHandler *)arg1 didChangeNotificationStatusWithSuccess:(_Bool)arg2 isDotNotDisturb:(_Bool)arg3;
- (void)messageNotificationActionHandler:(SCFriendUnifiedProfileMessageNotificationActionHandler *)arg1 didStartChangeNotificationStatus:(_Bool)arg2;
@end

