//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCDocObjectChangeRequest-Protocol.h"

@class NSString;

@interface SCFriendsFeedItemInfoChangeRequest : NSObject <SCDocObjectChangeRequest>
{
    long long _rowid;
    int _requestType;
    NSString *_feedId;
    long long _type;
}

+ (id)changeRequestForFriendsFeedItemInfo:(id)arg1;
+ (id)creationRequestWithFriendsFeedItemInfo:(id)arg1;
+ (id)deletionRequestForFriendsFeedItemInfo:(id)arg1;
- (void).cxx_destruct;
- (id)_friendsFeedItemInfo;
- (void)createTableWithSQLite:(struct sqlite3 *)arg1;
@property(copy, nonatomic) NSString *feedId; // @synthesize feedId=_feedId;
- (id)initWithRowid:(long long)arg1 feedId:(id)arg2 type:(long long)arg3;
@property(nonatomic) long long type; // @synthesize type=_type;
- (const char *)table;
- (id)transactWithSQLite:(struct SQLiteConnection *)arg1 flatbuffers:(struct FlatBufferBuilder *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

