//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SCFriendsFeedFetchContext, SCFriendsFeedPaginationToken;

@protocol SCFriendsFeedFetching
- (_Bool)hasMoreFeedEntries;
- (void)paginateFeedForToken:(SCFriendsFeedPaginationToken *)arg1 fetchContext:(SCFriendsFeedFetchContext *)arg2 completion:(void (^)(long long))arg3;
- (void)updateAppStateChange:(_Bool)arg1;
- (void)updateFriendsFeedForFetchContext:(SCFriendsFeedFetchContext *)arg1 previousUpdateSucceeded:(_Bool)arg2 completion:(void (^)(long long))arg3;
@end

