//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SCFriendBloopsPolicySettingsViewController;

@protocol SCFriendBloopsPolicySettingsViewControllerDelegate <NSObject>
- (void)friendBloopsPolicySettingsViewController:(SCFriendBloopsPolicySettingsViewController *)arg1 didSelectPolicyType:(long long)arg2;
@end

