//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCFriendsFeedArroyoUpdatesProcessing-Protocol.h"

@class NSString;

@interface SCFriendsFeedArroyoMessagingUpdatesProcessor : NSObject <SCFriendsFeedArroyoUpdatesProcessing>
{
    NSString *_currentUserId;
}

+ (id)_chatsStateFromMessage:(id)arg1 chatsStateFromDocObject:(id)arg2 currentUserId:(id)arg3;
+ (id)_conversationStateForConversation:(id)arg1 messages:(id)arg2 conversationId:(id)arg3 conversationStateFromDocObject:(id)arg4 currentUserId:(id)arg5;
+ (id)_snapsStateFromMessage:(id)arg1 snapsStateFromDocObject:(id)arg2 currentUserId:(id)arg3;
- (void).cxx_destruct;
- (id)initWithUserId:(id)arg1;
- (void)processUpsertConversation:(id)arg1 messages:(id)arg2 conversationId:(id)arg3 transactionContext:(id)arg4;

@end

