//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCGalleryCollectionViewHelperDataSource-Protocol.h"
#import "SCGalleryCollectionViewSelectionHelperDataSource-Protocol.h"
#import "SCGalleryCollectionViewSelectionHelperDelegate-Protocol.h"
#import "SCTraceEnabled-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSMutableSet, NSString, SCGalleryCollectionViewHelper, SCGalleryCollectionViewLayoutCalculator, SCGalleryCollectionViewSelectionHelper, SCGalleryDebugSyncStatusChecker, SCGallerySharedFolderViewModel, SCGalleryTabCollectionViewFlowLayout, SCUserSession, UICollectionView;
@protocol SCGalleryBaseSnapTabControllerDelegate;

@interface SCGalleryBaseSnapTabController : NSObject <UICollectionViewDataSource, UICollectionViewDelegate, SCGalleryCollectionViewSelectionHelperDataSource, SCGalleryCollectionViewSelectionHelperDelegate, SCTraceEnabled, UICollectionViewDelegateFlowLayout, SCGalleryCollectionViewHelperDataSource>
{
    SCGalleryTabCollectionViewFlowLayout *_collectionViewLayout;
    SCGalleryCollectionViewLayoutCalculator *_collectionViewLayoutCalculator;
    SCGalleryCollectionViewSelectionHelper *_collectionViewSelectionHelper;
    SCGalleryCollectionViewHelper *_collectionViewHelper;
    NSMutableSet *_selectedGalleryEntries;
    SCGalleryDebugSyncStatusChecker *_debugSyncStatusChecker;
    _Bool _selectMode;
    UICollectionView *_collectionView;
    SCGallerySharedFolderViewModel *_viewModel;
    SCUserSession *_userSession;
    id <SCGalleryBaseSnapTabControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (id)_entryWithIndexPath:(id)arg1;
- (CDStruct_bac8f6e9)_mediaScenePathWithIndexPath:(id)arg1;
- (void)changeSelected:(_Bool)arg1 forGalleryEntry:(id)arg2;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)dealloc;
@property(nonatomic) __weak id <SCGalleryBaseSnapTabControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)entriesInCurrentTab;
- (id)galleryCollectionViewHelper:(id)arg1 itemAtIndexPath:(id)arg2;
- (_Bool)galleryCollectionViewIsFullyVisible:(id)arg1;
- (void)galleryCollectionViewSelectionHelper:(id)arg1 didChangeSelected:(_Bool)arg2 forItem:(id)arg3;
- (void)galleryCollectionViewSelectionHelper:(id)arg1 didTapItemAtIndexPath:(id)arg2;
- (id)galleryCollectionViewSelectionHelper:(id)arg1 galleryItemAtIndexPath:(id)arg2;
- (void)galleryCollectionViewSelectionHelper:(id)arg1 handleLongPress:(id)arg2 itemAtIndexPath:(id)arg3;
- (_Bool)galleryCollectionViewSelectionHelper:(id)arg1 overrideTapHandlingAtIndexPath:(id)arg2;
- (_Bool)galleryCollectionViewSelectionHelper:(id)arg1 shouldChangeSelectedAtIndexPath:(id)arg2;
- (id)initWithWithUserSession:(id)arg1 viewModel:(id)arg2 delegate:(id)arg3;
- (_Bool)isViewLoaded;
- (void)loadViewIfNeeded;
- (void)presentEntry:(id)arg1;
- (void)reloadDataWithViewModel:(id)arg1;
@property(nonatomic) _Bool selectMode; // @synthesize selectMode=_selectMode;
- (id)selectedGalleryEntries;
@property(retain, nonatomic) SCUserSession *userSession; // @synthesize userSession=_userSession;
@property(nonatomic) __weak SCGallerySharedFolderViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (_Bool)shouldDisplay;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

