//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGListDiffable-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSArray;

@interface SCGallerySnapFeaturedStoriesSectionViewModel : NSObject <IGListDiffable, NSCopying>
{
    NSArray *_featuredEntries;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)diffIdentifier;
@property(readonly, copy, nonatomic) NSArray *featuredEntries; // @synthesize featuredEntries=_featuredEntries;
- (unsigned long long)hash;
- (id)initWithFeaturedEntries:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToDiffableObject:(id)arg1;

@end

