//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SCGalleryWifiAlertContentView : UIView
{
    double _preferredHeight;
}

- (void)_fillContentWithDeeplink:(id)arg1;
- (void)_fillContentWithoutDeeplink:(id)arg1;
- (void)fillContent:(id)arg1 wifiDeeplinkEnabled:(_Bool)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

