//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCGalleryOperaMediaManagerHelper : NSObject
{
}

+ (id)animatedStickerImageKeyForSticker:(id)arg1 snapId:(id)arg2;
+ (id)audioProcessorMixKeyForSnap:(id)arg1;
+ (id)displayDateTitleForMonthlySnap:(id)arg1;
+ (id)firstFrameImageForContent:(id)arg1;
+ (id)intermediateGLCommandsKeyForSnap:(id)arg1;
+ (id)loadingBackgroundImageKeyForSnap:(id)arg1;
+ (id)loadingErrorPropertiesWithError:(id)arg1;
+ (id)magicMomentGLCommandKeyForSnap:(id)arg1;
+ (id)malibuPositionProperties;
+ (id)mediaOverlayImageKeyForSnap:(id)arg1;
+ (id)midOutputGLCommandsKeyForSnap:(id)arg1;
+ (id)newportPositionProperties;
+ (id)operaPresentAnimationFrameKeyForSnap:(id)arg1;
+ (id)outputGLCommandsKeyForSnap:(id)arg1;
+ (id)publisherLogoKeyForSnap:(id)arg1;
+ (id)rawImageKeyForCameraRoll:(id)arg1 seqNum:(unsigned long long)arg2;
+ (id)rawImageKeyForSnap:(id)arg1 seqNum:(unsigned long long)arg2;
+ (id)rawVideoAssetKeyForSnap:(id)arg1;
+ (id)rawVideoKeyForCameraRoll:(id)arg1;
+ (id)renderedImageKeyForSnap:(id)arg1;
+ (id)reverseAudioDataKeyForSnap:(id)arg1;
+ (id)screamingmantisPositionProperties;
+ (id)screenOverlayImageKeyForSnap:(id)arg1;
+ (_Bool)shouldLoadFirstFrameForSnap:(id)arg1;

@end

