//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class SCShapeView, UIButton, UIImageView;
@protocol SCGroupMapRequestLocationViewDelegate;

@interface SCGroupMapRequestLocationView : UIView
{
    UIImageView *_backgroundView;
    UIImageView *_bitmojiImageView;
    SCShapeView *_calloutBackground;
    UIButton *_calloutButton;
    id <SCGroupMapRequestLocationViewDelegate> _delegate;
    struct UIEdgeInsets _contentInsets;
}

- (void).cxx_destruct;
- (void)_tappedCallout;
@property(nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
@property(nonatomic) __weak id <SCGroupMapRequestLocationViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setBitmojiImage:(id)arg1 calloutText:(id)arg2 calloutDisabled:(_Bool)arg3 animated:(_Bool)arg4;

@end

