//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCCharmsServices, SCConversationServices, SCFriendsFeedServices, SCGroupServices, SCLegacySnapchatterServices, SCLegacyStoriesServices, SCNativeMessagingServices, SCPinnedConversationsServices, SCServicesExposer, SCSnapchatterServices, SCStoriesServices, SCUserSessionScope, SCUserStorageServices;

@interface SCGroupUnifiedProfileEntryPoint : SCEntryPoint
{
    SCUserSessionScope *_userSessionScope;
    SCUserStorageServices *_userStorageServices;
    SCStoriesServices *_storiesServices;
    SCLegacyStoriesServices *_legacyStoriesServices;
    SCSnapchatterServices *_snapchatterServices;
    SCLegacySnapchatterServices *_legacySnapchatterServices;
    SCFriendsFeedServices *_friendsFeedServices;
    SCConversationServices *_conversationServices;
    SCGroupServices *_groupServices;
    SCNativeMessagingServices *_nativeMessagingServices;
    SCCharmsServices *_charmsServices;
    SCPinnedConversationsServices *_pinnedConversationsServices;
    SCServicesExposer *_groupUnifiedProfileServicesExposer;
}

- (void).cxx_destruct;
- (void)begin;
@property(nonatomic) __weak SCCharmsServices *charmsServices; // @synthesize charmsServices=_charmsServices;
@property(nonatomic) __weak SCConversationServices *conversationServices; // @synthesize conversationServices=_conversationServices;
@property(nonatomic) __weak SCFriendsFeedServices *friendsFeedServices; // @synthesize friendsFeedServices=_friendsFeedServices;
@property(nonatomic) __weak SCGroupServices *groupServices; // @synthesize groupServices=_groupServices;
@property(retain, nonatomic) SCServicesExposer *groupUnifiedProfileServicesExposer; // @synthesize groupUnifiedProfileServicesExposer=_groupUnifiedProfileServicesExposer;
@property(nonatomic) __weak SCLegacySnapchatterServices *legacySnapchatterServices; // @synthesize legacySnapchatterServices=_legacySnapchatterServices;
@property(nonatomic) __weak SCLegacyStoriesServices *legacyStoriesServices; // @synthesize legacyStoriesServices=_legacyStoriesServices;
@property(nonatomic) __weak SCNativeMessagingServices *nativeMessagingServices; // @synthesize nativeMessagingServices=_nativeMessagingServices;
@property(nonatomic) __weak SCPinnedConversationsServices *pinnedConversationsServices; // @synthesize pinnedConversationsServices=_pinnedConversationsServices;
@property(nonatomic) __weak SCSnapchatterServices *snapchatterServices; // @synthesize snapchatterServices=_snapchatterServices;
@property(nonatomic) __weak SCStoriesServices *storiesServices; // @synthesize storiesServices=_storiesServices;
@property(nonatomic) __weak SCUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
@property(nonatomic) __weak SCUserStorageServices *userStorageServices; // @synthesize userStorageServices=_userStorageServices;

@end

