//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol SCPerforming;

@interface SCGroupSyncStateTracker : NSObject
{
    id <SCPerforming> _performer;
    long long _syncState;
    NSMutableArray *_syncGroupsCallbacks;
}

- (void).cxx_destruct;
- (void)didLoadGroupsFromDisk;
- (void)didSyncGroups;
- (id)init;
- (void)waitUntilGroupsHaveSynced:(CDUnknownBlockType)arg1;

@end

