//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCGenericSettingsViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, SCSearchContainerView, UITableView;
@protocol SCGroupStoryGeoPrivacySettingsViewController;

@interface SCGroupStoryGeoPrivacySettingsViewController : SCGenericSettingsViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tableView;
    long long _privacyType;
    SCSearchContainerView *_containerView;
    id <SCGroupStoryGeoPrivacySettingsViewController> _delegate;
}

- (void).cxx_destruct;
- (id)backgroundColorForHeader;
@property(nonatomic) __weak id <SCGroupStoryGeoPrivacySettingsViewController> delegate; // @synthesize delegate=_delegate;
- (id)getTitle;
- (id)imageForLeftButtonInState:(unsigned long long)arg1;
- (id)initWithPrivacyType:(long long)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)textColorForHeader:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

