//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSThread.h>

@class NSDateFormatter;

@interface SCHeartbeatThread : NSThread
{
    NSDateFormatter *_dateFormatter;
    _Bool _hasAsyncTimerTrace;
    unsigned long long _timeBucket;
}

+ (id)shared;
- (void).cxx_destruct;
- (void)main;

@end

