//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCEntryPoint.h"

#import "SCInAppRatingSubWorkflowDelegate-Protocol.h"

@class SCInAppRatingTrigger, SCScopeExposer, SCSnapServices, SCSystemScope, SCUserSegmentServices, SCUserSessionScope, SCUserStorageServices;

@interface SCInAppRatingTriggerEntryPoint : SCEntryPoint <SCInAppRatingSubWorkflowDelegate>
{
    SCInAppRatingTrigger *_inAppRatingTrigger;
    SCUserSessionScope *_userSessionScope;
    SCSnapServices *_snapServices;
    SCUserStorageServices *_userStorageServices;
    SCSystemScope *_systemScope;
    SCUserSegmentServices *_userSegmentServices;
    SCScopeExposer *_inAppRatingScopeExposer;
}

- (void).cxx_destruct;
- (void)begin;
- (void)beginInAppRatingWorkflowWithDelegate:(id)arg1;
- (void)endInAppRatingWorkflow;
@property(retain, nonatomic) SCScopeExposer *inAppRatingScopeExposer; // @synthesize inAppRatingScopeExposer=_inAppRatingScopeExposer;
@property(nonatomic) __weak SCSnapServices *snapServices; // @synthesize snapServices=_snapServices;
@property(nonatomic) __weak SCSystemScope *systemScope; // @synthesize systemScope=_systemScope;
@property(nonatomic) __weak SCUserSegmentServices *userSegmentServices; // @synthesize userSegmentServices=_userSegmentServices;
@property(nonatomic) __weak SCUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
@property(nonatomic) __weak SCUserStorageServices *userStorageServices; // @synthesize userStorageServices=_userStorageServices;

@end

