//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCLabelMaker : NSObject
{
}

+ (id)_colorWithShading:(unsigned long long)arg1;
+ (id)_fontNameWithAttribute:(unsigned long long)arg1;
+ (double)_sizeWithTextSize:(unsigned long long)arg1;
+ (id)attributedStringWithText:(id)arg1 textSize:(unsigned long long)arg2 shading:(unsigned long long)arg3 format:(unsigned long long)arg4;
+ (id)attributedStringWithText:(id)arg1 textSize:(unsigned long long)arg2 shading:(unsigned long long)arg3 format:(unsigned long long)arg4 additionalAttributes:(id)arg5;
+ (id)attributesWithTextSize:(unsigned long long)arg1 shading:(unsigned long long)arg2 format:(unsigned long long)arg3;
+ (id)attributesWithTextSize:(unsigned long long)arg1 shading:(unsigned long long)arg2 format:(unsigned long long)arg3 additionalAttributes:(id)arg4;
+ (id)fontWithTextSize:(unsigned long long)arg1 format:(unsigned long long)arg2;

@end

