//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCSpectaclesEventListener-Protocol.h"

@class NSString, SCSessionRequestManager, SCSpectaclesDevice, SCSpectaclesManager, SCWeakTimer;

@interface SCLagunaUsageRecorder : NSObject <SCSpectaclesEventListener>
{
    _Bool _isBleConnectedSinceRecentContentTransferred;
    _Bool _wasDeviceConnectedOverBLE;
    long long _mostRecentContentTimeCaptured;
    SCSpectaclesDevice *_mostRecentContentDevice;
    SCSpectaclesManager *_spectaclesManager;
    SCSessionRequestManager *_requestManager;
    SCSpectaclesDevice *_mostRecentConnectedBLEDevice;
    SCWeakTimer *_analyticsLogsUploadTimer;
}

- (void).cxx_destruct;
- (void)_checkUploadAnalyticsLogs:(id)arg1;
- (_Bool)_didTransferRecentContent;
- (void)_startAnalyticsLogsUploadTimer;
- (void)_stopAnalyticsLogsUploadTimer;
@property(retain, nonatomic) SCWeakTimer *analyticsLogsUploadTimer; // @synthesize analyticsLogsUploadTimer=_analyticsLogsUploadTimer;
- (id)initWithRequestManager:(id)arg1 spectaclesManager:(id)arg2;
@property(nonatomic) _Bool isBleConnectedSinceRecentContentTransferred; // @synthesize isBleConnectedSinceRecentContentTransferred=_isBleConnectedSinceRecentContentTransferred;
@property(nonatomic) __weak SCSpectaclesDevice *mostRecentConnectedBLEDevice; // @synthesize mostRecentConnectedBLEDevice=_mostRecentConnectedBLEDevice;
@property(nonatomic) __weak SCSpectaclesDevice *mostRecentContentDevice; // @synthesize mostRecentContentDevice=_mostRecentContentDevice;
@property(nonatomic) long long mostRecentContentTimeCaptured; // @synthesize mostRecentContentTimeCaptured=_mostRecentContentTimeCaptured;
@property(retain, nonatomic) SCSessionRequestManager *requestManager; // @synthesize requestManager=_requestManager;
@property(nonatomic) __weak SCSpectaclesManager *spectaclesManager; // @synthesize spectaclesManager=_spectaclesManager;
@property(nonatomic) _Bool wasDeviceConnectedOverBLE; // @synthesize wasDeviceConnectedOverBLE=_wasDeviceConnectedOverBLE;
- (void)spectaclesDeviceDidUpdateState:(id)arg1;
- (void)spectaclesTransferSession:(id)arg1 onTransferUpdate:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

