//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCLEHalfHeightExperimentContext : SCExperimentContext
{
    _Bool _lensExplorerHalfHeightEnabled;
    _Bool _lensExplorerHalfHeightCategoriesEnabled;
    _Bool _lensExplorerHalfHeightOverlyButtonEnabled;
    _Bool _lensExplorerHalfHeightTrendingCategoryEnabled;
}

- (id)experimentName;
@property(nonatomic) _Bool lensExplorerHalfHeightCategoriesEnabled; // @synthesize lensExplorerHalfHeightCategoriesEnabled=_lensExplorerHalfHeightCategoriesEnabled;
@property(nonatomic) _Bool lensExplorerHalfHeightEnabled; // @synthesize lensExplorerHalfHeightEnabled=_lensExplorerHalfHeightEnabled;
@property(nonatomic) _Bool lensExplorerHalfHeightOverlyButtonEnabled; // @synthesize lensExplorerHalfHeightOverlyButtonEnabled=_lensExplorerHalfHeightOverlyButtonEnabled;
@property(nonatomic) _Bool lensExplorerHalfHeightTrendingCategoryEnabled; // @synthesize lensExplorerHalfHeightTrendingCategoryEnabled=_lensExplorerHalfHeightTrendingCategoryEnabled;
- (void)setupParameters;

@end

