//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCLensExplorerError : NSObject
{
}

+ (long long)cacheErrorCode;
+ (id)errorDomain;
+ (long long)invalidInteractionHistoryErrorCode;
+ (long long)invalidParameterErrorCode;
+ (long long)invalidQueryErrorCode;
+ (long long)nilSelfInBlockErrorCode;

@end

