//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLensFrameRateProviderProtocol-Protocol.h"
#import "SCTraceEnabled-Protocol.h"

@class NSString, SCFrameRateLogger, SCLensFrameRateCounterListenerAnnouncer;

@interface SCLensLegacyFrameRateCounter : NSObject <SCTraceEnabled, SCLensFrameRateProviderProtocol>
{
    SCFrameRateLogger *_frameRateLogger;
    double _frameProcessingStartTime;
    double _frameProcessingTime;
    double _fps;
    SCLensFrameRateCounterListenerAnnouncer *_listenerAnnouncer;
}

- (void).cxx_destruct;
- (void)_updateFrameRate;
- (_Bool)addListener:(id)arg1;
@property(readonly, nonatomic) double fps; // @synthesize fps=_fps;
- (id)init;
@property(retain, nonatomic) SCLensFrameRateCounterListenerAnnouncer *listenerAnnouncer; // @synthesize listenerAnnouncer=_listenerAnnouncer;
- (void)onFrameProcessingFinished;
- (void)onFrameProcessingStarted;
- (void)removeListener:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

