//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString, UIPanGestureRecognizer, UIPercentDrivenInteractiveTransition;

@interface SCLeftSwipableViewController : UIViewController <UIGestureRecognizerDelegate, UINavigationControllerDelegate>
{
    double _leftSwipeStartX;
    long long _leftSwipeStyle;
    UIPanGestureRecognizer *_leftSwipeRecognizer;
    UIPercentDrivenInteractiveTransition *_interactivePopTransition;
}

- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)disableLeftSwipe;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)handlePopRecognizer:(id)arg1;
- (_Bool)inValidView:(id)arg1;
@property(retain, nonatomic) UIPercentDrivenInteractiveTransition *interactivePopTransition; // @synthesize interactivePopTransition=_interactivePopTransition;
- (void)leftSwipeCancelled;
- (void)leftSwipePrepare;
@property(retain, nonatomic) UIPanGestureRecognizer *leftSwipeRecognizer; // @synthesize leftSwipeRecognizer=_leftSwipeRecognizer;
@property(nonatomic) long long leftSwipeStyle; // @synthesize leftSwipeStyle=_leftSwipeStyle;
- (void)leftSwipeSucceed;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (long long)navigationControllerPreferredInterfaceOrientationForPresentation:(id)arg1;
- (unsigned long long)navigationControllerSupportedInterfaceOrientations:(id)arg1;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shadowEnabled;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

