//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLensExplorerImpressionManagerDelegate-Protocol.h"
#import "SCLensExplorerImpressionMangerProtocol-Protocol.h"

@class NSDictionary, NSString, SCLensExplorerImpressionManagerFactory, SCQueuePerformer;
@protocol SCLensExplorerImpressionControllerDelegate;

@interface SCLensExplorerImpressionController : NSObject <SCLensExplorerImpressionManagerDelegate, SCLensExplorerImpressionMangerProtocol>
{
    SCLensExplorerImpressionManagerFactory *_impressionManagerFactory;
    NSDictionary *_impressionManagers;
    SCQueuePerformer *_performer;
    id <SCLensExplorerImpressionControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <SCLensExplorerImpressionControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)impressionManagerWithType:(id)arg1;
- (void)impressionManger:(id)arg1 didReachThresholdForItems:(id)arg2;
- (id)initWithImpressionManagerFactory:(id)arg1 performer:(id)arg2;
- (void)reset;
- (void)trackTapOnViewItem:(id)arg1;
- (void)trackViewItems:(id)arg1 date:(id)arg2 viewPort:(struct CGRect)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

