//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface SCLensExplorerDebugModelBuilder : NSObject
{
    NSString *_debugHTML;
    NSString *_storyId;
    NSData *_lastStreamToken;
}

+ (id)lensExplorerDebugModel;
+ (id)lensExplorerDebugModelFromExistingLensExplorerDebugModel:(id)arg1;
- (void).cxx_destruct;
- (id)build;
- (id)withDebugHTML:(id)arg1;
- (id)withLastStreamToken:(id)arg1;
- (id)withStoryId:(id)arg1;

@end

