//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SCLensTooltipUser <NSObject>
- (_Bool)lensTooltipShownAfterDismiss;
- (_Bool)seenOpenLensTooltip;
- (void)setDisplayedLensesActivationTooltipWithSuccess:(_Bool)arg1;
- (void)setDisplayedReplyOnStoryTooltip;
- (void)setDisplayedReplyToSnapTooltip;
- (void)setLensTooltipShownAfterDismiss;
- (void)setSeenOpenLensTooltip;
- (void)setUsedReplyOnStoryTooltip;
- (void)setUsedReplyToSnapTooltip;
- (void)setUserClickedToTurnOffLens;
- (_Bool)shouldDisplayReplyOnStoryTooltip;
- (_Bool)shouldDisplayReplyToSnapTooltip;
- (_Bool)userClickedToTurnOffLens;
@end

