//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, SCSearchQuery;

@protocol SCLensExplorerQueryFactoryProtocol <NSObject>
- (SCSearchQuery *)fetchLensChallenges;
- (SCSearchQuery *)fetchLensChallengesStoriesForSection:(NSString *)arg1 challengeName:(NSString *)arg2;
- (SCSearchQuery *)fetchLensesWithCategory:(unsigned long long)arg1;
- (SCSearchQuery *)fetchSubscriptionLenses;
- (SCSearchQuery *)fetchSubscriptionTailLenses;
- (SCSearchQuery *)fetchTailLensChallenges;
- (SCSearchQuery *)fetchTailLensChallengesStoriesForSection:(NSString *)arg1 challengeName:(NSString *)arg2;
- (SCSearchQuery *)fetchTailLensesWithCategory:(unsigned long long)arg1;
- (SCSearchQuery *)refreshLensesWithCategory:(unsigned long long)arg1;
- (SCSearchQuery *)refreshSubscriptionLenses;
@end

