//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCLowpassFilter : NSObject
{
    double _filterConstant;
    double _x;
    double _y;
    double _z;
}

- (void)addAcceleration:(CDStruct_31142d93)arg1;
- (id)initWithSampleRate:(double)arg1 cutoffFrequency:(double)arg2;
- (void)updateSampleRate:(double)arg1 cutoffFrequency:(double)arg2;
@property(readonly, nonatomic) double x; // @synthesize x=_x;
@property(readonly, nonatomic) double y; // @synthesize y=_y;
@property(readonly, nonatomic) double z; // @synthesize z=_z;

@end

