//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "SCLocationDataControllerDelegate-Protocol.h"
#import "SCLocationDataFetcherDelegate-Protocol.h"
#import "SCLocationObserver-Protocol.h"
#import "SCTraceEnabled-Protocol.h"
#import "SCUserSessionScoped-Protocol.h"

@class CLLocation, NSDate, NSMutableDictionary, NSMutableSet, NSString, SCLocationDataFetcher, SCLocationManager, SCLocationServicesListenerAnnouncer, SCLocationWeatherController, SCUserSession;

@interface SCLocationServicesDataStore : NSObject <NSCoding, SCLocationDataFetcherDelegate, SCLocationDataControllerDelegate, SCTraceEnabled, SCLocationObserver, SCUserSessionScoped>
{
    CLLocation *_lastFetchLocation;
    _Bool _isDebouncing;
    SCUserSession *_userSession;
    _Bool _forceUseNextLocation;
    _Bool _fetchingLocationData;
    long long _state;
    long long _requestContext;
    SCLocationManager *_locationManager;
    SCLocationDataFetcher *_locationDataFetcher;
    SCLocationWeatherController *_weatherController;
    SCLocationServicesListenerAnnouncer *_locationServicesAnnouncer;
    NSMutableDictionary *_datastore;
    CLLocation *_location;
    CLLocation *_dataLocation;
    NSDate *_lastIpRequestTime;
    NSDate *_updateUntil;
    NSMutableSet *_updateLocationCallers;
}

+ (_Bool)_isRecentValidLocation:(id)arg1;
+ (_Bool)_legacyShouldFetchLocDataForNewLocation:(id)arg1 comparedToOldLocation:(id)arg2;
+ (_Bool)_shouldUseNewLocation:(id)arg1 oldLocation:(id)arg2;
+ (id)path;
+ (void)removeSavedState;
+ (id)stringWithLocationDataState:(long long)arg1;
- (void).cxx_destruct;
- (void)_didStartLocationUpdatingWithCaller:(id)arg1;
- (void)_didStopLocationUpdating;
- (void)_ensureNonNilObjects;
- (void)_fetchIpBasedLocationDataWithContext:(long long)arg1;
- (void)_onLocationAltitudeChange:(double)arg1;
- (void)_onLocationSpeedChange:(double)arg1;
- (void)_prepareLocationDataUpdate;
- (void)_setObject:(id)arg1 forKey:(id)arg2;
- (void)_setState:(long long)arg1;
- (void)_setUserSessionIfValid:(id)arg1;
- (void)_startUpdatingLocationDataWithLocationServices:(_Bool)arg1 context:(long long)arg2 caller:(id)arg3;
- (void)_stopUpdatingLocationDataIfNecessary;
- (void)addListener:(id)arg1;
- (void)clear;
- (double)currentLocationDataAccuracy;
@property(retain, nonatomic) CLLocation *dataLocation; // @synthesize dataLocation=_dataLocation;
@property(retain, nonatomic) NSMutableDictionary *datastore; // @synthesize datastore=_datastore;
- (void)debounceFetchDataWithLatestLocation:(id)arg1 context:(long long)arg2 trigger:(long long)arg3;
- (void)encodeWithCoder:(id)arg1;
- (void)fetchDataForLocation:(id)arg1 context:(long long)arg2 trigger:(long long)arg3;
@property(nonatomic) _Bool fetchingLocationData; // @synthesize fetchingLocationData=_fetchingLocationData;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)invalidate;
@property(retain, nonatomic) NSDate *lastIpRequestTime; // @synthesize lastIpRequestTime=_lastIpRequestTime;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
- (void)locationDataController:(id)arg1 didUpdateData:(id)arg2 forKey:(id)arg3;
@property(retain, nonatomic) SCLocationDataFetcher *locationDataFetcher; // @synthesize locationDataFetcher=_locationDataFetcher;
- (void)locationDataFetcherFailedToFetchLocationDataWithError:(id)arg1;
- (void)locationDataFetcherFetchedLocationData:(id)arg1 forLocation:(id)arg2;
@property(retain, nonatomic) SCLocationManager *locationManager; // @synthesize locationManager=_locationManager;
- (double)locationObserverDesiredAccuracy;
- (id)locationObserverDispatchQueue;
- (id)locationObserverIdentifier;
- (_Bool)locationObserverWantsActiveLocationMonitoring;
@property(retain, nonatomic) SCLocationServicesListenerAnnouncer *locationServicesAnnouncer; // @synthesize locationServicesAnnouncer=_locationServicesAnnouncer;
- (id)objectForKey:(id)arg1;
- (void)onLocationError:(id)arg1;
- (void)onLocationUpdate:(id)arg1;
- (void)removeListener:(id)arg1;
@property(nonatomic) long long requestContext; // @synthesize requestContext=_requestContext;
- (void)saveState;
@property(retain) NSMutableSet *updateLocationCallers; // @synthesize updateLocationCallers=_updateLocationCallers;
@property(retain, nonatomic) NSDate *updateUntil; // @synthesize updateUntil=_updateUntil;
@property(retain, nonatomic) SCLocationWeatherController *weatherController; // @synthesize weatherController=_weatherController;
- (_Bool)shouldProcessResponseWithNewLocation:(id)arg1 oldLocation:(id)arg2;
- (void)startUpdatingLocationDataWithContext:(long long)arg1 caller:(id)arg2;
- (void)startUpdatingLocationServicesIfNecessaryWithContext:(long long)arg1 caller:(id)arg2;
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
- (void)stopUpdatingLocation;
- (void)stopUpdatingLocationData;
- (void)updateLocationDataOnceWithContext:(long long)arg1 caller:(id)arg2;
- (void)updateLocationDataOnceWithLocationServices:(_Bool)arg1 context:(long long)arg2 caller:(id)arg3;
- (id)userSession;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

