//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate;

@interface SCLocationUpdateRequestItem : NSObject
{
    NSDate *_startTime;
    long long _appStateWhenRequestStart;
}

- (void).cxx_destruct;
@property(nonatomic) long long appStateWhenRequestStart; // @synthesize appStateWhenRequestStart=_appStateWhenRequestStart;
- (id)initWithStartTimestamp:(id)arg1 appState:(long long)arg2;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;

@end

