//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCGrapheneInstanceProviding-Protocol.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, SCCounters, SCEventUploader, SCStartupContext;
@protocol SCLoggerAmplitudeProtocol, SCPerforming;

@interface SCLogger : NSObject <SCGrapheneInstanceProviding>
{
    SCCounters *_counters;
    id <SCLoggerAmplitudeProtocol> _blizzardLogger;
    SCEventUploader *_eventUploader;
    NSMutableSet *_uniqueEvents;
    NSMutableDictionary *_timers;
    NSMutableDictionary *_timedEvents;
    SCStartupContext *_startupContext;
    CDUnknownBlockType _userProvider;
    CDUnknownBlockType _sendEventsBlock;
    CDUnknownBlockType _didLogBlizzardEventCallback;
    CDUnknownBlockType _didLogOpsDataPipelineEventCallback;
    CDUnknownBlockType _didEndPerfEventCallback;
    CDUnknownBlockType _didCancelTimerEventsCallback;
    CDUnknownBlockType _grapheneProvider;
    CDUnknownBlockType _reachabilityProvider;
    CDUnknownBlockType _isLowPowerModeEnabledCallback;
    CDUnknownBlockType _isTravelModeEnabledCallback;
    CDUnknownBlockType _isProtectedDataAvailable;
    CDUnknownBlockType _mainThreadDelaysProvider;
    CDUnknownBlockType _currentHostProvider;
    CDUnknownBlockType _frameRatesProvider;
    NSArray *_performanceEvents;
    NSMutableArray *_savedEvents;
    id <SCPerforming> _performer;
}

+ (id)_getTotalAndSubfolderSizesMBInDirectory:(id)arg1 cancelationToken:(id)arg2;
+ (double)cpuUsage;
+ (unsigned long long)currentThreadCount;
+ (id)diskUsageParams_DEPRECATED:(id)arg1;
+ (unsigned long long)diskspaceFreeMB;
+ (unsigned long long)diskspaceUsedMB;
+ (id)networkTrafficDataStatistic;
+ (id)perfMetrics;
+ (id)perfMetricsAsString;
+ (id)sharedInstance;
+ (_Bool)shouldReport;
+ (_Bool)shouldReportForPercentage:(double)arg1;
+ (_Bool)shouldUnsample;
- (void).cxx_destruct;
- (void)_setStartParameters:(id)arg1 parameters:(id)arg2;
- (void)addSplitPoint:(id)arg1 atTime:(double)arg2 toEvent:(id)arg3;
- (void)appDidReceivePrefetchTriggerByAppleWithState:(long long)arg1;
- (void)appDidReceivePushNotificationWithSource:(long long)arg1 appState:(long long)arg2;
- (double)appStartupCompleteTime;
- (void)attemptResumeBlizzardSession:(long long)arg1;
@property(retain, nonatomic) id <SCLoggerAmplitudeProtocol> blizzardLogger; // @synthesize blizzardLogger=_blizzardLogger;
- (void)cancelAllLogTimedEvents;
- (void)cancelLogTimedEvent:(id)arg1 uniqueId:(id)arg2;
- (void)cancelLogTimedEvents:(id)arg1;
- (void)cancelLogTimedEventsWithName:(id)arg1;
- (void)cancelPerfEventsForStartupToAllViews;
- (void)cancelPerfEventsForStartupToFeedStoryView;
- (void)cancelPerfEventsWhenChatViewAppear;
- (void)cancelPerfEventsWhenDiscoverEditionViewAppear;
- (void)cancelPerfEventsWhenLoggedOut;
- (void)cancelPerfEventsWhenMyFriendsViewFullyDisappear;
- (void)cancelPerfEventsWhenOpenAppFromDeepLink;
- (void)cancelPerfEventsWhenOpenAppFromQuickAction;
- (void)cancelPerfEventsWhenPreviewViewAppear;
- (void)cancelPerfEventsWhenVisibleVCIsNotMainVC;
- (void)conditionallyLogTimedEventEnd:(id)arg1 uniqueId:(id)arg2 parameters:(id)arg3 shouldLog:(CDUnknownBlockType)arg4;
@property(readonly, nonatomic) SCCounters *counters; // @synthesize counters=_counters;
@property(copy, nonatomic) CDUnknownBlockType currentHostProvider; // @synthesize currentHostProvider=_currentHostProvider;
@property(copy, nonatomic) CDUnknownBlockType didCancelTimerEventsCallback; // @synthesize didCancelTimerEventsCallback=_didCancelTimerEventsCallback;
@property(copy, nonatomic) CDUnknownBlockType didEndPerfEventCallback; // @synthesize didEndPerfEventCallback=_didEndPerfEventCallback;
@property(copy, nonatomic) CDUnknownBlockType didLogBlizzardEventCallback; // @synthesize didLogBlizzardEventCallback=_didLogBlizzardEventCallback;
@property(copy, nonatomic) CDUnknownBlockType didLogOpsDataPipelineEventCallback; // @synthesize didLogOpsDataPipelineEventCallback=_didLogOpsDataPipelineEventCallback;
- (void)disableResetForEvent:(id)arg1 uniqueId:(id)arg2;
- (void)endOrCancelTimedEvent:(id)arg1 uniqueId:(id)arg2 parameters:(id)arg3 shouldEnd:(_Bool)arg4;
@property(retain, nonatomic) SCEventUploader *eventUploader; // @synthesize eventUploader=_eventUploader;
- (id)eventsWithDelaysAttached;
- (void)forceUploadEvents;
@property(copy, nonatomic) CDUnknownBlockType frameRatesProvider; // @synthesize frameRatesProvider=_frameRatesProvider;
- (void)getAndClearEventsWithBlock:(CDUnknownBlockType)arg1;
- (id)graphene;
- (id)grapheneFlusher;
@property(copy, nonatomic) CDUnknownBlockType grapheneProvider; // @synthesize grapheneProvider=_grapheneProvider;
- (id)histogramBucketForTimeLapsed:(double)arg1 bucketSize:(double)arg2 numberBuckets:(int)arg3;
- (id)init;
@property(copy, nonatomic) CDUnknownBlockType isLowPowerModeEnabledCallback; // @synthesize isLowPowerModeEnabledCallback=_isLowPowerModeEnabledCallback;
@property(copy, nonatomic) CDUnknownBlockType isProtectedDataAvailable; // @synthesize isProtectedDataAvailable=_isProtectedDataAvailable;
@property(copy, nonatomic) CDUnknownBlockType isTravelModeEnabledCallback; // @synthesize isTravelModeEnabledCallback=_isTravelModeEnabledCallback;
- (void)logCancellationPerfEventsForStartupToCameraView;
- (void)logCounterEvent:(id)arg1 count:(unsigned long long)arg2 parameters:(id)arg3;
- (void)logCounterEvent:(id)arg1 count:(unsigned long long)arg2 parameters:(id)arg3 samplePercentage:(double)arg4;
- (void)logEndSessionForType:(id)arg1;
- (void)logEvent:(id)arg1;
- (void)logEvent:(id)arg1 parameters:(id)arg2;
- (void)logEvent:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3;
- (void)logEvent:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3 metrics:(id)arg4;
- (void)logEvent:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3 metrics:(id)arg4 samplePercentage:(double)arg5;
- (void)logEventToEventLogger:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3;
- (void)logEventToEventLogger:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3 metrics:(id)arg4;
- (void)logEventToEventLogger:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3 metrics:(id)arg4 samplePercentage:(double)arg5;
- (void)logEventWithAttachedDelays:(id)arg1;
- (void)logJSONSerializationError:(id)arg1 endpoint:(id)arg2 parameters:(id)arg3;
- (void)logLocationMessageResponseWithMessageType:(id)arg1 didShareBack:(_Bool)arg2;
- (void)logLocationMessageSeenWithMessageType:(id)arg1 canShareBack:(_Bool)arg2 wasAlreadySharing:(_Bool)arg3 messageId:(id)arg4;
- (void)logLocationShareDialogChooseMoreWithSource:(long long)arg1 didChooseMore:(_Bool)arg2 numberOfFriendsChosen:(long long)arg3;
- (void)logLocationShareDialogWithSource:(long long)arg1 dialogType:(id)arg2 isGroup:(_Bool)arg3 resultingSharingAudience:(id)arg4 didCompleteFlow:(_Bool)arg5;
- (void)logNetworkStepToEvent:(id)arg1 uniqueId:(id)arg2 stepName:(id)arg3;
- (void)logSavedEvents;
- (void)logSerializedEvent:(id)arg1;
- (void)logStartSessionForType:(id)arg1;
- (void)logStepEndForEvent:(id)arg1 uniqueId:(id)arg2 stepName:(id)arg3 sampled:(_Bool)arg4;
- (void)logStepToEvent:(id)arg1 uniqueId:(id)arg2 stepName:(id)arg3;
- (void)logTimedEvent:(id)arg1 interval:(double)arg2;
- (void)logTimedEvent:(id)arg1 interval:(double)arg2 parameters:(id)arg3;
- (void)logTimedEvent:(id)arg1 interval:(double)arg2 parameters:(id)arg3 samplePercentage:(double)arg4;
- (void)logTimedEventEnd:(id)arg1 uniqueId:(id)arg2 parameters:(id)arg3;
- (void)logTimedEventEnd:(id)arg1 uniqueId:(id)arg2 parameters:(id)arg3 endTime:(id)arg4;
- (void)logTimedEventEnd:(id)arg1 uniqueId:(id)arg2 parameters:(id)arg3 samplePercentage:(double)arg4;
- (void)logTimedEventEnd:(id)arg1 uniqueId:(id)arg2 parameters:(id)arg3 samplePercentage:(double)arg4 endTime:(id)arg5;
- (void)logTimedEventEnd:(id)arg1 uniqueId:(id)arg2 parameters:(id)arg3 shouldLog:(CDUnknownBlockType)arg4 samplePercentage:(double)arg5 endTime:(id)arg6;
- (void)logTimedEventEnd:(id)arg1 uniqueId:(id)arg2 update:(CDUnknownBlockType)arg3;
- (void)logTimedEventEnd:(id)arg1 uniqueId:(id)arg2 update:(CDUnknownBlockType)arg3 shouldLog:(CDUnknownBlockType)arg4 samplePercentage:(double)arg5 endTime:(id)arg6;
- (void)logTimedEventStart:(id)arg1 uniqueId:(id)arg2 isUniqueEvent:(_Bool)arg3;
- (void)logTimedEventStart:(id)arg1 uniqueId:(id)arg2 isUniqueEvent:(_Bool)arg3 parameters:(id)arg4;
- (void)logTimedEventStart:(id)arg1 uniqueId:(id)arg2 isUniqueEvent:(_Bool)arg3 parameters:(id)arg4 shouldLogStartTime:(_Bool)arg5;
- (void)logTimedEventStart:(id)arg1 uniqueId:(id)arg2 isUniqueEvent:(_Bool)arg3 parameters:(id)arg4 shouldLogStartTime:(_Bool)arg5 sampled:(_Bool)arg6;
- (void)logUnsampledEvent:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3 metrics:(id)arg4;
- (void)logUnsampledEventToEventLogger:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3 metrics:(id)arg4;
- (void)logUnsampledTimedEventStart:(id)arg1 uniqueId:(id)arg2 isUniqueEvent:(_Bool)arg3 parameters:(id)arg4;
- (void)logUserNotTrackedEvent:(id)arg1;
- (void)logUserTrackedEvent:(id)arg1;
- (void)logViewedLocationSharingButtonWithType:(id)arg1 source:(long long)arg2 isGroup:(_Bool)arg3;
@property(copy, nonatomic) CDUnknownBlockType mainThreadDelaysProvider; // @synthesize mainThreadDelaysProvider=_mainThreadDelaysProvider;
- (id)markEndSessionForType:(id)arg1;
- (_Bool)markStartSessionForType:(id)arg1 withStartTime:(double)arg2;
@property(retain, nonatomic) NSArray *performanceEvents; // @synthesize performanceEvents=_performanceEvents;
@property(retain, nonatomic) id <SCPerforming> performer; // @synthesize performer=_performer;
@property(copy, nonatomic) CDUnknownBlockType reachabilityProvider; // @synthesize reachabilityProvider=_reachabilityProvider;
- (void)removeUniqueEvents;
@property(retain, nonatomic) NSMutableArray *savedEvents; // @synthesize savedEvents=_savedEvents;
@property(copy, nonatomic) CDUnknownBlockType sendEventsBlock; // @synthesize sendEventsBlock=_sendEventsBlock;
- (void)setAppStartupCompleteTime:(double)arg1;
- (void)setEventUploaderBatchSizeLimit:(unsigned long long)arg1;
@property(retain, nonatomic) SCStartupContext *startupContext; // @synthesize startupContext=_startupContext;
@property(retain, nonatomic) NSMutableDictionary *timedEvents; // @synthesize timedEvents=_timedEvents;
@property(retain, nonatomic) NSMutableDictionary *timers; // @synthesize timers=_timers;
@property(retain, nonatomic) NSMutableSet *uniqueEvents; // @synthesize uniqueEvents=_uniqueEvents;
@property(copy, nonatomic) CDUnknownBlockType userProvider; // @synthesize userProvider=_userProvider;
- (void)startPerfEventsWhenAppStartupFromBackgroundWithNotification;
- (void)startPerfEventsWhenAppStartupFromBackgroundWithProtectedDataUnavailable;
- (void)startPerfEventsWhenAppStartupFromBackgroundWithTimeLapse:(double)arg1;
- (void)startPerfEventsWhenAppStartupFromKilledState;
- (void)startPerfEventsWhenAppStartupFromKilledStateEarlyWithTimeLapse:(double)arg1 preOpenLatency:(double)arg2;
- (void)startPerfEventsWhenAppStartupFromKilledStateWithNotification;
- (void)startServicesWithBlizzardLogger:(id)arg1 userProvider:(CDUnknownBlockType)arg2 sendEventsBlock:(CDUnknownBlockType)arg3 didLogOpsDataPipelineEventCallback:(CDUnknownBlockType)arg4 didEndPerfEventCallback:(CDUnknownBlockType)arg5 didCancelTimerEventsCallback:(CDUnknownBlockType)arg6 reachabilityProvider:(CDUnknownBlockType)arg7 isLowPowerModeEnabledCallBack:(CDUnknownBlockType)arg8 isTravelModeEnabledCallBack:(CDUnknownBlockType)arg9 isProtectedDataAvailable:(CDUnknownBlockType)arg10 mainThreadDelaysProvider:(CDUnknownBlockType)arg11 currentHostProvider:(CDUnknownBlockType)arg12 grapheneProvider:(CDUnknownBlockType)arg13 frameRateProvider:(CDUnknownBlockType)arg14;
- (void)syncLogEventToEventLogger:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3 metrics:(id)arg4 samplePercentage:(double)arg5;
- (void)synchronouslyLogEvent:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3 metrics:(id)arg4 samplePercentage:(double)arg5;
- (void)updateBlizzardValidationServerUrl:(id)arg1;
- (void)updateContentReadyAndFirstItemReadyEventswithNetworkStepName:(id)arg1;
- (void)updateContentReadyAndFirstItemReadyEventswithParameters:(id)arg1;
- (void)updateLogTimedEvent:(id)arg1 uniqueId:(id)arg2 parameters:(id)arg3;
- (void)updateLogTimedEvent:(id)arg1 uniqueId:(id)arg2 splitPoint:(id)arg3;
- (void)updateLogTimedEvent:(id)arg1 uniqueId:(id)arg2 splitPoint:(id)arg3 time:(double)arg4;
- (void)updateLogTimedEvent:(id)arg1 uniqueId:(id)arg2 update:(CDUnknownBlockType)arg3;
- (void)updateLogTimedEventStart:(id)arg1 uniqueId:(id)arg2;
- (void)updateLogTimedEventStart:(id)arg1 uniqueId:(id)arg2 parameters:(id)arg3;
- (void)useT0ForEvent:(id)arg1 uniqueId:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

