//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SOJULoginResponse;

@interface SCLoginRegisterFlowContext : NSObject
{
    NSString *_deviceId;
    long long _pageSource;
    SOJULoginResponse *_loginResponse;
}

+ (id)configWithDeviceId:(id)arg1 pageSource:(long long)arg2 loginResponse:(id)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
- (id)initWithDeviceId:(id)arg1 pageSource:(long long)arg2 loginResponse:(id)arg3;
@property(readonly, nonatomic) SOJULoginResponse *loginResponse; // @synthesize loginResponse=_loginResponse;
@property(readonly, nonatomic) long long pageSource; // @synthesize pageSource=_pageSource;

@end

