//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SCLSIScanDataState;

@protocol SCLSIScanDataStateDelegate <NSObject>
- (void)scanDataState:(SCLSIScanDataState *)arg1 didChangeToState:(unsigned long long)arg2;
@end

