//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SCMapCarouselContainerView;

@protocol SCMapCarouselContainerViewDelegate <NSObject>

@optional
- (void)mapCarouselContainer:(SCMapCarouselContainerView *)arg1 didScrollToIndex:(long long)arg2 action:(unsigned long long)arg3;
- (void)mapCarouselContainerWantsDismissal:(SCMapCarouselContainerView *)arg1;
@end

