//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@protocol SCManagedLensProcessorState <NSObject, NSCoding, NSCopying>
@property(readonly, nonatomic) long long aspectRatioDenominator;
@property(readonly, nonatomic) long long aspectRatioNumerator;
@property(readonly, nonatomic) _Bool audioSessionActive;
@property(readonly, nonatomic) _Bool audioSessionModeVideoRecording;
@property(readonly, nonatomic) unsigned long long coreState;
@property(readonly, nonatomic) _Bool detectingCategory;
@property(readonly, nonatomic) unsigned long long devicePosition;
@property(readonly, nonatomic) float fieldOfView;
@property(readonly, nonatomic) long long inputOrientation;
@property(readonly, nonatomic) _Bool lensesActive;
@property(readonly, nonatomic) long long processingMode;
@property(readonly, nonatomic) long long secretFeatureMode;
@property(readonly, nonatomic) _Bool shouldMuteAllSounds;
@property(readonly, nonatomic) _Bool shouldProcessARFrames;
@end

