//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, SCDeepLinkURL;
@protocol SCMapActionSheetPresenter;

@protocol SCMapActionSheetPresenterDelegate <NSObject>
- (void)mapActionSheetPresenter:(id <SCMapActionSheetPresenter>)arg1 wantsChatForUsername:(NSString *)arg2 deeplinkURL:(SCDeepLinkURL *)arg3;
@end

