//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SCMainSortStrategyFeatureStateProvider <NSObject>
@property(readonly, nonatomic, getter=areSnappablesEnabled) _Bool snappablesEnabled;
@property(readonly, nonatomic, getter=isArcadiaForceEnabled) _Bool arcadiaForceEnabled;
@property(readonly, nonatomic, getter=isCreateYourOwnLensCarouselButtonPresent) _Bool createYourOwnLensCarouselButtonPresent;
@end

