//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCMapFriendFinderPerson-Protocol.h"

@class NSNumber, NSString, SCCUser, SCMapPerson, SCScopedAccess;

@interface SCMapFriendFinderPerson : NSObject <SCMapFriendFinderPerson>
{
    SCMapPerson *_mapPerson;
    SCScopedAccess *_snapchattersSynchronousDataAccess;
    SCCUser *_user;
    NSNumber *dateLastOnMap;
}

- (void).cxx_destruct;
- (id)_snapchatterForUserId:(id)arg1;
@property(retain, nonatomic) NSNumber *dateLastOnMap; // @synthesize dateLastOnMap;
- (id)initWithMapPerson:(id)arg1;
- (long long)pushToComposerMarshaller:(struct SCComposerMarshaller *)arg1;
@property(retain, nonatomic) SCCUser *user; // @synthesize user=_user;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

