//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCIdentityUserAdaptor-Protocol.h"

@class NSString;

@interface SCMainAppIdentityUserAdaptor : NSObject <SCIdentityUserAdaptor>
{
}

@property(readonly, nonatomic) NSString *email;
@property(nonatomic) _Bool emailUpdating;
- (_Bool)hasVerifiedNumber;
@property(nonatomic) _Bool needsCaptchaVerification;
- (_Bool)needsContactSync;
@property(retain, nonatomic) NSString *pendingEmail;
@property(readonly, nonatomic) NSString *phoneNumber;

@end

