//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSString, NSURL, SCMapExploreItem, SCMapExploreViewController, SCMapPerson, UIView;
@protocol SCMapReplyScreenshotGenerating;

@protocol SCMapExploreViewControllerDelegate
- (id <SCMapReplyScreenshotGenerating>)mapExploreViewController:(SCMapExploreViewController *)arg1 screenshotGeneratorForUserId:(NSString *)arg2;
- (void)mapExploreViewController:(SCMapExploreViewController *)arg1 wantsToBeDismissedFromItem:(SCMapExploreItem *)arg2 exitEvent:(long long)arg3;
- (void)mapExploreViewController:(SCMapExploreViewController *)arg1 wantsToDisplayChatForPeople:(NSArray *)arg2 subpageName:(NSString *)arg3;
- (void)mapExploreViewController:(SCMapExploreViewController *)arg1 wantsToNavigateToURL:(NSURL *)arg2;
- (void)mapExploreViewController:(SCMapExploreViewController *)arg1 wantsToPlayMapStoryWithPoiId:(NSString *)arg2 fromSourceView:(UIView *)arg3;
- (void)mapExploreViewController:(SCMapExploreViewController *)arg1 wantsToPresentStoryForPerson:(SCMapPerson *)arg2 fromBaseView:(UIView *)arg3;
- (void)mapExploreViewController:(SCMapExploreViewController *)arg1 wantsToShowAllSprites:(_Bool)arg2 animated:(_Bool)arg3;
- (void)mapExploreViewController:(SCMapExploreViewController *)arg1 wantsToShowMiniProfileForPerson:(SCMapPerson *)arg2;
- (void)mapExploreViewController:(SCMapExploreViewController *)arg1 willShowItem:(SCMapExploreItem *)arg2;
- (UIView *)mapExploreViewControllerExternalHeaderView:(SCMapExploreViewController *)arg1;
- (void)mapExploreViewControllerWantsToPresentLocationSettings:(SCMapExploreViewController *)arg1;
@end

