//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCComposerView.h"

@class SCComposerScrollView, SCMapPassportPlacesViewModel;

@interface SCMapPassportPlacesView : SCComposerView
{
}

@property(readonly, nonatomic) SCComposerView *backgroundGradient;
- (id)bundleName;
@property(readonly, nonatomic) SCComposerView *dismissButton;
- (id)init;
- (id)initWithViewModel:(id)arg1 componentContext:(id)arg2;
@property(readonly, nonatomic) SCComposerView *pageHeader;
@property(readonly, nonatomic) SCMapPassportPlacesView *root;
@property(readonly, nonatomic) SCComposerScrollView *scrollView;
@property(retain, nonatomic) SCMapPassportPlacesViewModel *viewModel;
- (id)viewName;

@end

