//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface SCMEBatchExplorerViewsRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *viewedStatusIdsArray; // @dynamic viewedStatusIdsArray;
@property(readonly, nonatomic) unsigned long long viewedStatusIdsArray_Count; // @dynamic viewedStatusIdsArray_Count;
@property(copy, nonatomic) NSString *viewerId; // @dynamic viewerId;

@end

