//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSArray, NSDate, NSDictionary, NSNumber, NSString, SCACreativeKitSnapMetadata, SOJUMultiSnapMetadata, SOJUSnapCreatorAttribution, SOJUStoryFrame;
@protocol SCSnapSendPreparer;

@interface SCMediaSendTaskConfiguration : NSObject <NSCoding>
{
    _Bool _postToMyStory;
    _Bool _isForwarded;
    _Bool _shouldShowStatusMessageWhenPostComplete;
    id <SCSnapSendPreparer> _snapSendPreparer;
    NSArray *_userRecipientUsernames;
    NSArray *_ourStoriesMetadata;
    NSArray *_appStoryMetadatas;
    NSArray *_businessIds;
    NSArray *_mischiefs;
    NSArray *_customStoryIds;
    NSNumber *_postToMyStoryPrivacyOverride;
    NSDate *_storyUserPostedTimestamp;
    NSDate *_storyStartRecordingTimestamp;
    SOJUStoryFrame *_storyFraming;
    NSDictionary *_messageMetadata;
    NSArray *_blizzardEventsOnSuccess;
    NSString *_additionalText;
    SOJUMultiSnapMetadata *_multiSnapMetadata;
    SCACreativeKitSnapMetadata *_creativeKitMetadata;
    SOJUSnapCreatorAttribution *_storyRepostAttribution;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *additionalText; // @synthesize additionalText=_additionalText;
@property(readonly, copy, nonatomic) NSArray *appStoryMetadatas; // @synthesize appStoryMetadatas=_appStoryMetadatas;
@property(readonly, copy, nonatomic) NSArray *blizzardEventsOnSuccess; // @synthesize blizzardEventsOnSuccess=_blizzardEventsOnSuccess;
@property(readonly, copy, nonatomic) NSArray *businessIds; // @synthesize businessIds=_businessIds;
- (void)clearBlizzardEventsOnSuccess;
@property(readonly, copy, nonatomic) SCACreativeKitSnapMetadata *creativeKitMetadata; // @synthesize creativeKitMetadata=_creativeKitMetadata;
@property(readonly, copy, nonatomic) NSArray *customStoryIds; // @synthesize customStoryIds=_customStoryIds;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUserRecipientUsernames:(id)arg1 storiesPostingConfig:(id)arg2 businessIds:(id)arg3 mischiefs:(id)arg4 appStoryMetadatas:(id)arg5 storyFraming:(id)arg6 messageMetadata:(id)arg7 blizzardEventsOnSuccess:(id)arg8 additionalText:(id)arg9 multiSnapMetadata:(id)arg10 snapSendPreparer:(id)arg11 isForwarded:(_Bool)arg12;
- (id)initWithUserRecipientUsernames:(id)arg1 storiesPostingConfig:(id)arg2 businessIds:(id)arg3 mischiefs:(id)arg4 appStoryMetadatas:(id)arg5 storyFraming:(id)arg6 messageMetadata:(id)arg7 blizzardEventsOnSuccess:(id)arg8 additionalText:(id)arg9 multiSnapMetadata:(id)arg10 snapSendPreparer:(id)arg11 isForwarded:(_Bool)arg12 creativeKitSnapMetadata:(id)arg13;
@property(readonly, nonatomic) _Bool isForwarded; // @synthesize isForwarded=_isForwarded;
- (_Bool)isSingleGroupRecipient;
- (_Bool)isSingleUserRecipient;
@property(readonly, copy, nonatomic) NSDictionary *messageMetadata; // @synthesize messageMetadata=_messageMetadata;
@property(readonly, copy, nonatomic) NSArray *mischiefs; // @synthesize mischiefs=_mischiefs;
@property(readonly, nonatomic) SOJUMultiSnapMetadata *multiSnapMetadata; // @synthesize multiSnapMetadata=_multiSnapMetadata;
@property(readonly, copy, nonatomic) NSArray *ourStoriesMetadata; // @synthesize ourStoriesMetadata=_ourStoriesMetadata;
@property(readonly, nonatomic) _Bool postToMyStory; // @synthesize postToMyStory=_postToMyStory;
@property(readonly, nonatomic) NSNumber *postToMyStoryPrivacyOverride; // @synthesize postToMyStoryPrivacyOverride=_postToMyStoryPrivacyOverride;
- (void)removeStory;
@property(readonly, nonatomic) _Bool shouldShowStatusMessageWhenPostComplete; // @synthesize shouldShowStatusMessageWhenPostComplete=_shouldShowStatusMessageWhenPostComplete;
@property(readonly, nonatomic) id <SCSnapSendPreparer> snapSendPreparer; // @synthesize snapSendPreparer=_snapSendPreparer;
@property(readonly, nonatomic) SOJUStoryFrame *storyFraming; // @synthesize storyFraming=_storyFraming;
@property(readonly, nonatomic) SOJUSnapCreatorAttribution *storyRepostAttribution; // @synthesize storyRepostAttribution=_storyRepostAttribution;
@property(readonly, nonatomic) NSDate *storyStartRecordingTimestamp; // @synthesize storyStartRecordingTimestamp=_storyStartRecordingTimestamp;
@property(readonly, nonatomic) NSDate *storyUserPostedTimestamp; // @synthesize storyUserPostedTimestamp=_storyUserPostedTimestamp;
- (void)updateGroupRecipientsWithGroupIds:(id)arg1;
- (void)updateUserRecipientsWithUsernames:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *userRecipientUsernames; // @synthesize userRecipientUsernames=_userRecipientUsernames;

@end

