//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSString;

@protocol SCMediaPackageDataEncrypting <NSObject>
- (NSData *)encryptData:(NSData *)arg1 key:(NSString *)arg2 iv:(NSString *)arg3;
@end

