//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, SCMECheckinOptionRankingSignals;

@interface SCMEGetCheckinOptionsRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *experimentValue; // @dynamic experimentValue;
@property(nonatomic) _Bool ghostMode; // @dynamic ghostMode;
@property(nonatomic) _Bool hasRankingSignals; // @dynamic hasRankingSignals;
@property(nonatomic) double lat; // @dynamic lat;
@property(nonatomic) double lng; // @dynamic lng;
@property(nonatomic) double radiusMeters; // @dynamic radiusMeters;
@property(retain, nonatomic) SCMECheckinOptionRankingSignals *rankingSignals; // @dynamic rankingSignals;

@end

