//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface SCMediaPackageOrchestrationSessionBuilder : NSObject
{
    NSString *_userEditedPackageId;
    NSArray *_transcodeOutputPackageIds;
    NSArray *_keysOfEncryptedDataToUpload;
}

+ (id)mediaPackageOrchestrationSession;
+ (id)mediaPackageOrchestrationSessionFromExistingMediaPackageOrchestrationSession:(id)arg1;
- (void).cxx_destruct;
- (id)build;
- (id)withKeysOfEncryptedDataToUpload:(id)arg1;
- (id)withTranscodeOutputPackageIds:(id)arg1;
- (id)withUserEditedPackageId:(id)arg1;

@end

