//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCTraceEnabled-Protocol.h"

@class NSOperationQueue, NSString, SCDisposableObserverLifecycle, SCLazy;

@interface SCMemoryPageViewReporter : NSObject <SCTraceEnabled>
{
    SCLazy *_grapheneLogger;
    SCLazy *_blizzardLogger;
    NSOperationQueue *_memoryPageViewReportQueue;
    SCDisposableObserverLifecycle *_disposableObserverLifecycle;
    long long _maxMemoryUsageInBytes;
    long long _reportedEventCount;
}

- (void).cxx_destruct;
- (void)_didChangeCurrentPageEvent:(id)arg1;
- (void)_reportBlizzardMetricWithFinishedPageName:(id)arg1 prevPageName:(id)arg2 startTimestamp:(double)arg3 endTimestamp:(double)arg4;
- (void)_reportGrapheneMetricWithFinishedPageName:(id)arg1 prevPageName:(id)arg2 startTimestamp:(double)arg3 endTimestamp:(double)arg4;
- (void)_reportMetricWithFinishedPageName:(id)arg1 prevPageName:(id)arg2 startTimestamp:(double)arg3 endTimestamp:(double)arg4;
- (void)_reset;
- (void)_updateMemoryUsageStatus:(id)arg1;
- (id)initWithGrapheneLogger:(id)arg1 blizzardLogger:(id)arg2 reportQueue:(id)arg3;
- (void)subscribeOnMemoryUsageSnapshot:(id)arg1 currentPageEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

