//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SCMessagingSearchShareSnap : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *dynamicStoryId; // @dynamic dynamicStoryId;
@property(copy, nonatomic) NSString *mediaType; // @dynamic mediaType;
@property(copy, nonatomic) NSString *snapId; // @dynamic snapId;

@end

