//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCMiniProfileRowController.h"

@class NSString;

@interface SCMiniProfileTitleRowController : SCMiniProfileRowController
{
    NSString *_title;
}

- (void).cxx_destruct;
- (Class)cellClass;
- (double)cellHeight;
- (void)didSelectCell;
- (void)setTitle:(id)arg1;
- (void)willDisplayCell:(id)arg1;

@end

