//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SCMockCaptureConnection : NSObject
{
    _Bool _videoMirrored;
    NSString *_mediaType;
    long long _videoOrientation;
    long long _preferredVideoStabilizationMode;
}

- (void).cxx_destruct;
- (id)initWithMediaType:(id)arg1;
- (id)inputDevice;
- (id)inputPorts;
@property(nonatomic, getter=isVideoMirrored) _Bool videoMirrored; // @synthesize videoMirrored=_videoMirrored;
@property(readonly, nonatomic) NSString *mediaType; // @synthesize mediaType=_mediaType;
@property(nonatomic) long long preferredVideoStabilizationMode; // @synthesize preferredVideoStabilizationMode=_preferredVideoStabilizationMode;
@property(nonatomic) long long videoOrientation; // @synthesize videoOrientation=_videoOrientation;

@end

