//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SCMTMapboxGeocodeResponse_Property : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *address; // @dynamic address;
@property(copy, nonatomic) NSString *category; // @dynamic category;
@property(nonatomic) _Bool landmark; // @dynamic landmark;
@property(copy, nonatomic) NSString *maki; // @dynamic maki;
@property(copy, nonatomic) NSString *tel; // @dynamic tel;
@property(copy, nonatomic) NSString *wikidata; // @dynamic wikidata;

@end

