//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface SCMTGetMapTilesRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *tileCollectionsArray; // @dynamic tileCollectionsArray;
@property(readonly, nonatomic) unsigned long long tileCollectionsArray_Count; // @dynamic tileCollectionsArray_Count;

@end

