//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface SCMTPoiTile : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLocalizedPois; // @dynamic hasLocalizedPois;
@property(retain, nonatomic) NSMutableArray *poisArray; // @dynamic poisArray;
@property(readonly, nonatomic) unsigned long long poisArray_Count; // @dynamic poisArray_Count;

@end

