//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, SCMTGeoBox, SCMTPoint;

@interface SCMTGetOnboardingViewStateRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLocation; // @dynamic hasLocation;
@property(nonatomic) _Bool hasViewport; // @dynamic hasViewport;
@property(retain, nonatomic) SCMTPoint *location; // @dynamic location;
@property(retain, nonatomic) NSMutableArray *reservedBoundingBoxArray; // @dynamic reservedBoundingBoxArray;
@property(readonly, nonatomic) unsigned long long reservedBoundingBoxArray_Count; // @dynamic reservedBoundingBoxArray_Count;
@property(retain, nonatomic) SCMTGeoBox *viewport; // @dynamic viewport;
@property(nonatomic) double zoom; // @dynamic zoom;

@end

