//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCDisposableObserver.h"

@class NSArray;

@interface SCMultiDisposable : SCDisposableObserver
{
    NSArray *_disposables;
}

- (void).cxx_destruct;
- (void)dispose;
- (id)initWithDisposables:(id)arg1;

@end

