//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SCMyUnifiedProfileSnapProPlayStoryActionDataModel : NSObject <NSCopying>
{
    _Bool _useCircleTransition;
    NSString *_businessId;
    NSString *_startingSnapId;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *businessId; // @synthesize businessId=_businessId;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithBusinessId:(id)arg1 startingSnapId:(id)arg2 useCircleTransition:(_Bool)arg3;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *startingSnapId; // @synthesize startingSnapId=_startingSnapId;
@property(readonly, nonatomic) _Bool useCircleTransition; // @synthesize useCircleTransition=_useCircleTransition;

@end

