//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableOrderedSet;
@protocol SCPerforming;

@interface SCNetworkObservationBuffer : NSObject
{
    unsigned long long _capacity;
    double _weightMultiplierPerSecond;
    id <SCPerforming> _queuePerformer;
    NSMutableOrderedSet *_orderedObservationsByValue;
}

- (void).cxx_destruct;
- (void)addObservation:(id)arg1;
- (unsigned long long)capacity;
- (void)clear;
- (double)getPercentileFromTimestamp:(double)arg1 percentile:(unsigned long long)arg2;
- (id)initWithBufferCapacity:(unsigned long long)arg1 weightMultiplierPerSecond:(double)arg2;
- (unsigned long long)size;

@end

