//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray;

@protocol SCNMessagingFeedManagerDelegate
- (void)onFeedEntriesUpdated:(NSArray *)arg1 feedEntriesDeleted:(NSArray *)arg2;
@end

