//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCNNetworkTypesNetworkManagerNotifier : NSObject
{
    struct Handle<std::__1::shared_ptr<snap::network_types::NetworkManagerNotifier>, std::__1::shared_ptr<snap::network_types::NetworkManagerNotifier>> _cppRefHandle;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithCpp:(const shared_ptr_5b252241 *)arg1;
- (void)read;

@end

