//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSObject;
@protocol OS_dispatch_queue;

@protocol SCNonSnapchattersDataFetching
- (NSArray *)contactNonSnapchatters;
- (void)contactNonSnapchattersWithCompletionQueue:(NSObject<OS_dispatch_queue> *)arg1 completionHandler:(void (^)(NSArray *, NSError *))arg2;
@end

