//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCScopeExposer.h"

@interface SCOptionalScopeExposer : SCScopeExposer
{
    _Bool _isEnabled;
}

@property(readonly, nonatomic) _Bool isEnabled; // @synthesize isEnabled=_isEnabled;

@end

