//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SCOperaViewersCellViewModelListenerAnnouncer;

@interface SCOperaViewersCellBaseViewModel : NSObject
{
    SCOperaViewersCellViewModelListenerAnnouncer *_announcer;
    double _textAlpha;
}

- (void).cxx_destruct;
- (void)addListener:(id)arg1;
- (id)init;
- (void)reloadCell;
- (void)removeListener:(id)arg1;
@property(nonatomic) double textAlpha; // @synthesize textAlpha=_textAlpha;

@end

