//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCOperaLayerViewController.h"

#import "SCOperaEventListener-Protocol.h"
#import "SCOperaUpNextLayerViewDelegate-Protocol.h"
#import "SCUpNextGroupViewModelProviderListener-Protocol.h"

@class NSString, NSTimer, SCOperaUpNextLayerView;
@protocol SCImageDownloading, SCUpNextGroupViewModelProvider;

@interface SCOperaUpNextLayerViewController : SCOperaLayerViewController <SCOperaEventListener, SCUpNextGroupViewModelProviderListener, SCOperaUpNextLayerViewDelegate>
{
    SCOperaUpNextLayerView *_layerView;
    id <SCUpNextGroupViewModelProvider> _upNextGroupViewModelProvider;
    NSTimer *_inactiveStateTimer;
    id <SCImageDownloading> _imageDownloader;
}

- (void).cxx_destruct;
- (void)_cancelInactiveStateTimer;
- (void)_sendActiveStatePropertyUpdates:(long long)arg1 animated:(_Bool)arg2;
- (void)_startInactiveStateTimer;
- (void)didReceiveUpdateProperties:(id)arg1;
- (id)initWithConfiguration:(id)arg1 eventAnnouncer:(id)arg2 sharedResourceManager:(id)arg3;
- (void)loadView;
- (void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3;
- (void)setPropertyUpdateModerator:(id)arg1;
- (void)teardown;
- (void)upNextGroupViewModelProviderDidUpdate:(id)arg1;
- (void)upNextLayerView:(id)arg1 didAwakeWithAction:(long long)arg2;
- (void)upNextLayerView:(id)arg1 didNavigateToItemWithItemId:(id)arg2 orderedVisibleItemIds:(id)arg3 action:(long long)arg4;
- (void)upNextLayerView:(id)arg1 didTapOnGroupWithId:(id)arg2;
- (void)upNextLayerView:(id)arg1 didUpdateActiveState:(long long)arg2;
- (void)upNextLayerView:(id)arg1 didUpdateItemsWithOrderedVisibleItemIds:(id)arg2;
- (void)upNextLayerViewWantsToBeActive:(id)arg1;
- (void)updateViewWithPreviousLayer:(id)arg1 currentLayer:(id)arg2;
- (void)updateViewWithRelativeHorizontalContentOffset:(double)arg1;
- (void)viewDidFullyAppear;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

