//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SCOperaLayerView-Protocol.h"

@class NSString, SCAudioStitchControlsView, SCAudioStitchViewport, SCLoadingIndicatorView, SCOperaPlayerView, SCOperaVideoControlsView, SCOperaVideoProgressViewV2;

@interface SCOperaVideoLayerView : UIView <SCOperaLayerView>
{
    SCOperaVideoProgressViewV2 *_videoProgressViewV2;
    SCOperaVideoControlsView *_playbackControlsView;
    SCAudioStitchControlsView *_audioStitchControlsView;
    SCLoadingIndicatorView *_loadingIndicatorView;
    SCOperaPlayerView *_playerView;
    SCAudioStitchViewport *_viewport;
}

+ (id)layerViewWithFrame:(struct CGRect)arg1;
- (void).cxx_destruct;
- (id)_createPlaybackControlsViewForType:(long long)arg1;
@property(readonly, nonatomic) SCAudioStitchControlsView *audioStitchControlsView; // @synthesize audioStitchControlsView=_audioStitchControlsView;
- (_Bool)collapseVideoProgressViewV2;
- (void)enableAudioStitchControls:(_Bool)arg1;
- (void)enableControls:(_Bool)arg1 forType:(long long)arg2;
- (void)enableLoadingIndicator:(_Bool)arg1;
- (void)enableVideoProgress:(_Bool)arg1;
- (_Bool)expandVideoProgressViewV2;
- (void)fadeAudioStitchControlsToHidden:(_Bool)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) SCLoadingIndicatorView *loadingIndicatorView; // @synthesize loadingIndicatorView=_loadingIndicatorView;
@property(readonly, nonatomic) SCOperaVideoControlsView *playbackControlsView; // @synthesize playbackControlsView=_playbackControlsView;
@property(retain, nonatomic) SCOperaPlayerView *playerView; // @synthesize playerView=_playerView;
- (void)setProgressViewWithVideoLayer:(id)arg1;
@property(retain, nonatomic) SCAudioStitchViewport *viewport; // @synthesize viewport=_viewport;
@property(readonly, nonatomic) SCOperaVideoProgressViewV2 *videoProgressViewV2; // @synthesize videoProgressViewV2=_videoProgressViewV2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

