//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SCOperaInlineVideo, UIGestureRecognizer;

@protocol SCOperaWebLayerVideoGestureRecognizer
- (void)didTapToOpenInlineVideo:(UIGestureRecognizer *)arg1;
- (void)didTapVideo:(SCOperaInlineVideo *)arg1;
@end

