//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, SCOperaViewModel;

@protocol SCOperaViewModelFactoryProtocol <NSObject>
- (SCOperaViewModel *)ctaViewModel;
- (SCOperaViewModel *)viewModelWithWebUrl:(NSString *)arg1 browsingContext:(long long)arg2;
@end

