//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CLLocation, NSString;

@interface SCOperaUserInfoProvider : NSObject
{
    NSString *_email;
    NSString *_phone;
    NSString *_name;
    NSString *_zipCode;
    CLLocation *_location;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *email; // @synthesize email=_email;
- (id)initWithDisplayName:(id)arg1 phone:(id)arg2 email:(id)arg3;
@property(readonly, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
- (void)setLocation:(id)arg1;
- (void)setZipCode:(id)arg1;
@property(readonly, copy, nonatomic) NSString *zipCode; // @synthesize zipCode=_zipCode;

@end

