//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SCOperaBlockingViewControllerDelegate-Protocol.h"
#import "SCOperaFadeTransitionCompatibleViewController-Protocol.h"
#import "SCOperaLayerViewControllerMediaContainer-Protocol.h"
#import "SCOperaPageableViewController-Protocol.h"
#import "SCOperaPageableViewControllerDelegate-Protocol.h"
#import "SCOperaPropertyUpdateModerator-Protocol.h"
#import "SCTraceEnabled-Protocol.h"
#import "SCViewControllerTransitionAnimatorMaskable-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class FBKVOController, NSDictionary, NSHashTable, NSMutableArray, NSNumber, NSString, NSTimer, SCOperaConfiguration, SCOperaEventListenerAnnouncer, SCOperaPage, SCOperaPageBackdropView, SCOperaSharedResourceManager, SCStopwatch, UILongPressGestureRecognizer, UIScrollView, UIView;
@protocol SCOperaPageableViewControllerDelegate;

@interface SCOperaPageViewController : UIViewController <SCOperaPageableViewControllerDelegate, UIGestureRecognizerDelegate, SCOperaBlockingViewControllerDelegate, UIScrollViewDelegate, SCTraceEnabled, SCOperaPageableViewController, SCOperaPropertyUpdateModerator, SCOperaFadeTransitionCompatibleViewController, SCOperaLayerViewControllerMediaContainer, SCViewControllerTransitionAnimatorMaskable>
{
    SCOperaSharedResourceManager *_sharedResourceManager;
    FBKVOController *_observeController;
    UIScrollView *_scrollView;
    NSMutableArray *_blockingLayerVCs;
    NSTimer *_autoAdvanceTimer;
    double _autoAdvanceTimerTimeLeft;
    NSDictionary *_lastUpdatedLayerViewProperties;
    _Bool _didSendOpenViewLoadedEvent;
    _Bool _didSendOpenViewEvent;
    NSHashTable *_layersNotifiedOfViewWillFullyAppear;
    NSHashTable *_layersNotifiedOfViewDidFullyAppear;
    _Bool _longPressEnabled;
    _Bool _ignoreLayoutForZoom;
    NSNumber *_fullyViewed;
    UIView *_actionMenuMaskLayerView;
    _Bool _pausedForAttachment;
    double _calculatedContainerViewYOffset;
    double _extraContainerViewYOffset;
    UIView *_attachmentBackgroundView;
    double _currentZoomInScaleForContextMenu;
    struct CGRect _currentContainerViewFrame;
    SCStopwatch *_pauseStopwatch;
    NSTimer *_skipDisabledTimer;
    struct UIEdgeInsets _safeAreaInsets;
    UIView *_blurOverlayView;
    SCOperaPageBackdropView *_backdropView;
    _Bool _didSendCloseViewEvent;
    _Bool _shouldNotReloadLayers;
    _Bool _hasRoundedCorners;
    SCOperaPage *_page;
    SCOperaConfiguration *_configuration;
    SCOperaEventListenerAnnouncer *_eventAnnouncer;
    id <SCOperaPageableViewControllerDelegate> _pageableViewControllerDelegate;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    NSDictionary *_layerTypeToFloatingLayerVCs;
    UIView *_containerView;
}

+ (id)pageViewControllerWithConfiguration:(id)arg1 eventAnnouncer:(id)arg2 sharedResourceManager:(id)arg3 page:(id)arg4;
- (void).cxx_destruct;
- (struct CGSize)_actionMenuContentSize;
- (long long)_actionMenuOptionsNumber;
- (void)_addChildLayerVC:(id)arg1;
- (void)_addCriticalModeContext;
- (void)_announceDidFullyAppearEventIfNeeded;
- (void)_attachActionMenuMaskViewIfNeeded;
- (void)_buildLayerVCs;
- (void)_cleanupSkipDisabledTimer;
- (void)_clearLayerViewControllers:(id)arg1;
- (struct CGRect)_contentRectForMediaAspectRatio:(double)arg1 inBounds:(struct CGRect)arg2;
- (_Bool)_isRotationMediaContent;
- (id)_layerVCForLayerType:(unsigned long long)arg1 inLayerVCs:(id)arg2;
- (id)_layerVCsOnPage;
- (void)_loadContainerView;
- (void)_loadPage;
- (void)_loadScrollView;
- (double)_mediaContentScaleWithPercentInActionMenu:(double)arg1;
- (void)_notifyLayerOfViewDidFullyAppearIfNeeded:(id)arg1;
- (void)_notifyLayerOfViewWillFullyAppearIfNeeded:(id)arg1;
- (void)_pauseAutoAdvanceTimer;
- (void)_removeActionMenuMaskViewIfNeeded;
- (void)_removeCriticalModeContext;
- (void)_removeFloatingLayerWithType:(id)arg1;
- (void)_resizeSwipeUpViewLayerWithRespectToContentHeight:(double)arg1;
- (void)_resumeAutoAdvanceTimer;
- (void)_setupScrollViewForZoomIfNeededWithPercent:(double)arg1;
- (void)_setupSkipDisabledTimer;
- (_Bool)_shouldSetPinchGestureTargetForLayer:(id)arg1 viewController:(id)arg2;
- (_Bool)_shouldSetupAutoAdvanceTimer;
- (_Bool)_shouldUpdateActionMenuStyleVersion;
- (void)_toggleCriticalMode;
- (void)_toggleUserBlocking;
- (id)_topMostBlockingLayerVC;
- (void)_updateFloatingLayer:(id)arg1;
- (void)_updateFloatingLayersForCurrentDisplayingPage;
- (void)_updateNeighborFloatingLayers;
- (void)_updatePropertiesWithPageDidShrink:(_Bool)arg1;
- (void)_viewDidFullyAppearWithLayerVCs:(id)arg1;
- (void)_zoomScrollViewWithPercent:(double)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_zoomToActionMenuV2WithPercent:(double)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) UIView *attachmentBackgroundView;
- (void)autoAdvanceTimerDidFire;
- (_Bool)blockingLayerIsBlocking;
- (_Bool)blockingLayerIsBlockingOtherLayersFromDisplaying;
- (void)blockingViewDidStartHiding:(id)arg1;
- (void)blockingViewWasHidden:(id)arg1;
- (_Bool)canHandleRoundCorner;
- (void)cancelViewWillFullyAppearAtTime;
@property(retain, nonatomic) SCOperaConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (id)currentViewParameters;
- (void)didLongPress:(id)arg1;
@property(nonatomic) _Bool didSendCloseViewEvent; // @synthesize didSendCloseViewEvent=_didSendCloseViewEvent;
- (void)didTryPagingWhenPagingDisabled;
- (void)didUpdateBottomPageViewProperties:(id)arg1;
- (void)didUpdateViewProperties:(id)arg1;
- (void)displayMediaLogIfAvailable;
@property(retain, nonatomic) SCOperaEventListenerAnnouncer *eventAnnouncer; // @synthesize eventAnnouncer=_eventAnnouncer;
- (id)fadingViewsForFadeTransition;
- (id)gestureDescription;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
@property(nonatomic) _Bool hasRoundedCorners; // @synthesize hasRoundedCorners=_hasRoundedCorners;
- (id)initWithConfiguration:(id)arg1 eventAnnouncer:(id)arg2 sharedResourceManager:(id)arg3 page:(id)arg4 observeController:(id)arg5;
- (_Bool)isOverlay;
- (_Bool)isPausedForAttachment;
@property(nonatomic) __weak NSDictionary *layerTypeToFloatingLayerVCs; // @synthesize layerTypeToFloatingLayerVCs=_layerTypeToFloatingLayerVCs;
- (void)loadView;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
- (struct CGRect)maskableFrame;
- (double)mediaHeightToWidthAspectRatio;
- (_Bool)mediaIsBeingPreparedForDisplay;
- (struct CGRect)mediaViewFrame;
- (id)movingViewsForFadeTransition;
- (void)neighborViewDidFullyAppearWithCurrentViewRelativePosition:(unsigned long long)arg1;
@property(retain, nonatomic) SCOperaPage *page; // @synthesize page=_page;
- (void)pageDidScrollToHorizontalOffset:(double)arg1 isCurrentPage:(_Bool)arg2;
- (_Bool)pageIsFullyVisible:(id)arg1;
- (_Bool)pageIsPartiallyVisible:(id)arg1;
- (long long)pageabilityForRelativePosition:(unsigned long long)arg1 gestureRecognizer:(id)arg2;
@property(nonatomic) __weak id <SCOperaPageableViewControllerDelegate> pageableViewControllerDelegate; // @synthesize pageableViewControllerDelegate=_pageableViewControllerDelegate;
- (void)pause;
- (unsigned long long)relativePositionForPageId:(id)arg1;
- (void)reloadLayers:(id)arg1;
- (void)removeLongPressGestureRecognizer;
- (void)restartTimer;
- (void)resume;
- (void)rotateBasedOnOrientation;
- (void)scrollViewDidZoom:(id)arg1;
- (void)sendViewCloseEvent;
- (void)setContainerViewYOffset:(double)arg1;
- (void)setImageForBackdrop:(id)arg1;
- (void)setPausedForAttachment:(_Bool)arg1;
@property(nonatomic) _Bool shouldNotReloadLayers; // @synthesize shouldNotReloadLayers=_shouldNotReloadLayers;
- (void)setSubtitlesEnabled:(_Bool)arg1;
- (void)setVolume:(double)arg1;
- (void)setupLongPressGestureRecognizer;
- (id)shareableMediaSnapshotsWithPerformer:(id)arg1;
- (id)shareableMedias;
- (void)start;
- (void)stop;
- (void)teardown;
- (void)updatePropertiesWithLooping:(_Bool)arg1;
- (void)updatePropertiesWithViewerIsDismissing:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidFullyAppear;
- (void)viewDidFullyDisappear;
- (void)viewDidLayoutSubviews;
- (void)viewDidPartiallyAppearWithCurrentViewRelativePosition:(unsigned long long)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)viewWillFullyAppear;
- (void)viewWillFullyAppearAtTime:(CDStruct_1b6d18a9)arg1;
- (void)zoomScrollView:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

