//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCUpdateAnnouncing-Protocol.h"

@class NSArray, NSString, SCSessionRequestManager, SCUpdateListenerAnnouncer;
@protocol OS_dispatch_queue, SCOurStorySettingsDataSourceDelegate;

@interface SCOurStorySettingsDataSource : NSObject <SCUpdateAnnouncing>
{
    SCUpdateListenerAnnouncer *_updateAnnouncer;
    NSArray *_snapDataModels;
    NSObject<OS_dispatch_queue> *_ourStorySettingsQueue;
    NSObject<OS_dispatch_queue> *_announceQueue;
    SCSessionRequestManager *_requestManager;
    id <SCOurStorySettingsDataSourceDelegate> _delegate;
}

+ (id)announcerIdentifier;
- (void).cxx_destruct;
- (void)_updateWithOurStory:(id)arg1;
- (void)addUpdateListener:(id)arg1;
@property(nonatomic) __weak id <SCOurStorySettingsDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)fetchData;
- (id)initWithRequestManager:(id)arg1;
- (void)removeStory:(id)arg1;
- (void)removeUpdateListener:(id)arg1;
- (id)snapDataModels;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

