//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class SCPBUnlockablesTextColor;

@interface SCPBUnlockablesTextShadow : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCPBUnlockablesTextColor *color; // @dynamic color;
@property(nonatomic) _Bool hasColor; // @dynamic hasColor;
@property(nonatomic) double radius; // @dynamic radius;
@property(nonatomic) double x; // @dynamic x;
@property(nonatomic) double y; // @dynamic y;

@end

