//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, SCPBGeofilterDisplayParameters, SCPBGeofilterLayoutParameters, SCPBLocalDateTimeInterval, SCPBUnlockablesCompanionCreativeProperties;

@interface SCPBGeofilterMarkup : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCPBUnlockablesCompanionCreativeProperties *companionCreativeProperties; // @dynamic companionCreativeProperties;
@property(retain, nonatomic) SCPBGeofilterDisplayParameters *displayParameters; // @dynamic displayParameters;
@property(retain, nonatomic) SCPBLocalDateTimeInterval *displaySchedule; // @dynamic displaySchedule;
@property(nonatomic) _Bool hasCompanionCreativeProperties; // @dynamic hasCompanionCreativeProperties;
@property(nonatomic) _Bool hasDisplayParameters; // @dynamic hasDisplayParameters;
@property(nonatomic) _Bool hasDisplaySchedule; // @dynamic hasDisplaySchedule;
@property(nonatomic) _Bool hasLayoutParameters; // @dynamic hasLayoutParameters;
@property(retain, nonatomic) SCPBGeofilterLayoutParameters *layoutParameters; // @dynamic layoutParameters;
@property(nonatomic) long long refreshRate; // @dynamic refreshRate;
@property(copy, nonatomic) NSString *source; // @dynamic source;
@property(copy, nonatomic) NSString *type; // @dynamic type;

@end

