//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GRPCProtoCall, SCPNSceneIntRequest;

@protocol SCPNSceneIntService <NSObject>
- (GRPCProtoCall *)RPCToSceneIntStreamWithRequest:(SCPNSceneIntRequest *)arg1 eventHandler:(void (^)(_Bool, SCPNSceneIntResponse *, NSError *))arg2;
- (GRPCProtoCall *)RPCToSceneIntWithRequest:(SCPNSceneIntRequest *)arg1 handler:(void (^)(SCPNSceneIntResponse *, NSError *))arg2;
- (void)sceneIntStreamWithRequest:(SCPNSceneIntRequest *)arg1 eventHandler:(void (^)(_Bool, SCPNSceneIntResponse *, NSError *))arg2;
- (void)sceneIntWithRequest:(SCPNSceneIntRequest *)arg1 handler:(void (^)(SCPNSceneIntResponse *, NSError *))arg2;
@end

