//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SCDocObjectContext, SCQueuePerformer;

@interface SCProfileChatMediaDataStore : NSObject
{
    SCDocObjectContext *_docObjectContext;
    SCQueuePerformer *_performer;
}

- (void).cxx_destruct;
- (void)_deleteExpiredDataModels;
- (void)_fetchChatMediaDataModelsForOwnerId:(id)arg1 completionQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)_fetchMetadataForOwnerId:(id)arg1 completionQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)_updateChatMediaDataModels:(id)arg1 fetchMetadata:(id)arg2 ownerId:(id)arg3;
- (void)_updateFetchMetadataChecksumForOwner:(id)arg1 checksum:(id)arg2;
- (void)chatMediaDataModelsForOwnerId:(id)arg1 completionQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)fetchMetadataForOwnerId:(id)arg1 completionQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)initWithDocObjectContext:(id)arg1;
- (void)updateChatMediaDataModelForOwnerId:(id)arg1 chatMediaDataModels:(id)arg2 fetchMetadata:(id)arg3;
- (void)updateFetchMetadataChecksumForOwner:(id)arg1 checksum:(id)arg2;

@end

