//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol SCPreviewFeatureCommerceAttachmentAttachingDelegate, SCPreviewFeatureParentViewControllerAccessing;

@protocol SCPreviewFeatureCommerceAttachment
@property(nonatomic) __weak id <SCPreviewFeatureCommerceAttachmentAttachingDelegate> attachingDelegate;
- (void)clearAttachments;
- (_Bool)hasAttachment;
- (void)prepareStoreInfoWithCompletion:(void (^)(SOJUCommerceStoreInfo *))arg1;
- (void)presentAttachmentTool;
@property(nonatomic) __weak id <SCPreviewFeatureParentViewControllerAccessing> presentingDelegate;
- (_Bool)shouldShowStoreButton;
- (void)trackAttachmentPostedToStory:(_Bool)arg1 toGroup:(_Bool)arg2 toFriend:(_Bool)arg3;
@end

