//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCPreviewContextImageUtils : NSObject
{
}

+ (id)_NSDataFromCvMat:(struct Mat)arg1 bitmapByteCount:(unsigned long long)arg2;
+ (void)_applyMirroringToContext:(struct CGContext *)arg1 imageOrientation:(long long)arg2 unorientedScaledImageSize:(struct CGSize)arg3;
+ (void)_centerImageAtDeviceSpacePoint:(struct CGPoint)arg1 forContext:(struct CGContext *)arg2 unorientedScaledImageSize:(struct CGSize)arg3;
+ (void)_orientContext:(struct CGContext *)arg1 imageOrientation:(long long)arg2 unorientedScaledImageSize:(struct CGSize)arg3;
+ (id)correctlyOrientedFromImage:(id)arg1 snappedOrientation:(long long)arg2 isFrontCamera:(_Bool)arg3;
+ (struct Mat)preprocessImage:(id)arg1 outputSize:(struct CGSize)arg2 crop:(_Bool)arg3;

@end

