//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SCImageProcessLensCommand, SCLens, UIGestureRecognizer;
@protocol UIGestureRecognizerDelegate;

@protocol SCPreviewFeatureLensProcessing
@property(nonatomic) __weak id <UIGestureRecognizerDelegate> gestureRecognizerDelegate;
- (_Bool)isAnyLensTouchProcessingGestureRecognizer:(UIGestureRecognizer *)arg1;
- (_Bool)isLensActive;
- (_Bool)lensHitAreaContainGesture:(UIGestureRecognizer *)arg1;
- (void)setLens:(SCLens *)arg1 withCommand:(SCImageProcessLensCommand *)arg2;
@end

