//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@interface SCSCOREABFeatureLoggingEntry_StudyCRInfo_TriggerReasons : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool experimentTriggered; // @dynamic experimentTriggered;
@property(nonatomic) _Bool impactSampled; // @dynamic impactSampled;

@end

