//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCSearchCollectionViewCell.h"

#import "SCAvatarViewDelegate-Protocol.h"

@class SCActionModel, SCAvatarView, SCLazy, SCSearchGroupViewModel, SCUserSession, UILabel;

@interface SCSearchGroupChatCollectionViewCell : SCSearchCollectionViewCell <SCAvatarViewDelegate>
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    SCLazy *_friendmojiLabel;
    SCSearchGroupViewModel *_viewModel;
    SCActionModel *_tapActionModel;
    SCActionModel *_longPressActionModel;
    SCActionModel *_avatarTapActionModel;
    SCAvatarView *_avatarView;
    SCUserSession *_userSession;
}

+ (struct CGSize)sizeWithViewModel:(id)arg1 constrainedToSize:(struct CGSize)arg2;
- (void).cxx_destruct;
- (void)_createFriendmojiLabelIfNecessary;
- (void)handleLongPressAction;
- (void)handleLongPressOnStoryIconFromAvatarView:(id)arg1;
- (void)handleTapAction;
- (void)handleTapOnBitmojiFromAvatarView:(id)arg1;
- (void)handleTapOnStoryIconFromAvatarView:(id)arg1;
- (_Bool)hasOverridedLongPressAction;
- (_Bool)hasOverridedTapAction;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) SCUserSession *userSession; // @synthesize userSession=_userSession;
- (void)setViewModel:(id)arg1;
- (id)viewModel;

@end

