//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCSendPreviewLogger : NSObject
{
}

+ (void)_logForPreviewShareType:(long long)arg1 mediaView:(id)arg2 recipientCount:(unsigned long long)arg3 additionalText:(id)arg4;
+ (void)_logForShareType:(long long)arg1 mediaType:(long long)arg2 recipientCount:(unsigned long long)arg3 additionalText:(id)arg4;
+ (long long)blizzardShareType:(long long)arg1;
+ (long long)shareTypeFromBroadcastViewLocation:(long long)arg1;
+ (long long)shareTypeFromPreviewConfiguration:(id)arg1;

@end

