//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class SCLoadingIndicatorView;

@interface SCSearchLoadingView : UIView
{
    SCLoadingIndicatorView *_loadingImage;
}

- (void).cxx_destruct;
- (id)initWithSize:(unsigned long long)arg1;
- (void)setHidden:(_Bool)arg1;
- (void)setHidden:(_Bool)arg1 animated:(_Bool)arg2;

@end

