//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDate;

@interface SCSearchFriendActivity : NSObject <NSCopying>
{
    _Bool _isActive;
    NSDate *_interactionTime;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned long long)hash;
- (id)initWithIsActive:(_Bool)arg1 interactionTime:(id)arg2;
@property(readonly, copy, nonatomic) NSDate *interactionTime; // @synthesize interactionTime=_interactionTime;
@property(readonly, nonatomic) _Bool isActive; // @synthesize isActive=_isActive;
- (_Bool)isEqual:(id)arg1;

@end

