//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCSendPreviewViewModel-Protocol.h"
#import "SCSummaryDelegate-Protocol.h"

@class NSString, NSURL, SCURLSummary, SCUserSession, UIImage;
@protocol SCSendPreviewURLViewModelDelegate;

@interface SCSendPreviewURLViewModel : NSObject <SCSummaryDelegate, SCSendPreviewViewModel>
{
    SCUserSession *_userSession;
    NSURL *_url;
    UIImage *_urlMediaInfoImage;
    SCURLSummary *_urlSummary;
    id <SCSendPreviewURLViewModelDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_loadUrlInfo;
@property(retain, nonatomic) id <SCSendPreviewURLViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)fetchThumbnailDidFailForSummary:(id)arg1;
- (void)fetchThumbnailDidLoadForSummary:(id)arg1;
- (void)fetchThumbnailIsLoadingForSummmary:(id)arg1;
- (id)initWithURL:(id)arg1 userSession:(id)arg2;
- (id)mediaView;
- (double)mediaViewAspectRatio;
- (long long)shareType;
- (_Bool)shouldPadMediaView;
- (id)subtitle;
- (id)title;
- (long long)viewStyle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

