//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCShakeBetaLogger : NSObject
{
}

+ (void)logEvent:(unsigned long long)arg1 message:(id)arg2;
+ (void)retrieveLogForTeam:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)writeLogToFileForTeam:(unsigned long long)arg1 baseUrl:(id)arg2 completion:(CDUnknownBlockType)arg3;

@end

