//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, SCSimpleFriendSelectorController;

@protocol SCSimpleFriendSelectorDelegate <NSObject>
- (void)friendSelectorController:(SCSimpleFriendSelectorController *)arg1 didFinishPickingFriendsWithListOfUsers:(NSArray *)arg2 headerTitle:(NSString *)arg3;
@end

