//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SCUserSession;
@protocol SCSnapcodeAnalyticsProviderDelegate;

@interface SCSnapcodeAnalyticsProvider : NSObject
{
    SCUserSession *_userSession;
    id <SCSnapcodeAnalyticsProviderDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <SCSnapcodeAnalyticsProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithUserSession:(id)arg1;
- (void)provideDailyScanAnalyticsForScannableId:(id)arg1 startDate:(id)arg2 endDate:(id)arg3;
- (void)provideTotalScanAnalyticsForScannableId:(id)arg1;

@end

