//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface SCSnapchatterOpenMiniProfileWithUsernameActionDataModelBuilder : NSObject
{
    NSString *_username;
    NSString *_userId;
    NSString *_userDisplayName;
    NSArray *_requestContexts;
    long long _pageType;
    long long _addSourceType;
    long long _viewLocaton;
}

+ (id)snapchatterOpenMiniProfileWithUsernameActionDataModel;
+ (id)snapchatterOpenMiniProfileWithUsernameActionDataModelFromExistingSnapchatterOpenMiniProfileWithUsernameActionDataModel:(id)arg1;
- (void).cxx_destruct;
- (id)build;
- (id)withAddSourceType:(long long)arg1;
- (id)withPageType:(long long)arg1;
- (id)withRequestContexts:(id)arg1;
- (id)withUserDisplayName:(id)arg1;
- (id)withUserId:(id)arg1;
- (id)withUsername:(id)arg1;
- (id)withViewLocaton:(long long)arg1;

@end

