//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView;

@interface SCSnapcodeCollectionCell : UICollectionViewCell
{
    UIImageView *_imageView;
}

- (void).cxx_destruct;
- (void)_highlight;
- (id)_imageSelectColor;
- (void)_unhighlight;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)loadFullScreenImageWithCompletion:(CDUnknownBlockType)arg1;
- (void)prepareForReuse;
- (void)showOverlay:(_Bool)arg1;

@end

