//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCSnapVideoFrameRawData-Protocol.h"

@class NSData, NSString;

@interface SCSnapVideoFrameRawData : NSObject <SCSnapVideoFrameRawData>
{
    long long _frameNum;
    long long _width;
    long long _height;
    long long _bytesPerRow;
    NSData *_rawLumaData;
}

+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long bytesPerRow; // @synthesize bytesPerRow=_bytesPerRow;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)decodeWithFasterDecoder:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
@property(readonly, nonatomic) long long frameNum; // @synthesize frameNum=_frameNum;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) long long height; // @synthesize height=_height;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrameNum:(long long)arg1 width:(long long)arg2 height:(long long)arg3 bytesPerRow:(long long)arg4 rawLumaData:(id)arg5;
- (_Bool)isEqual:(id)arg1;
- (_Bool)preferFasterCoding;
@property(readonly, copy, nonatomic) NSData *rawLumaData; // @synthesize rawLumaData=_rawLumaData;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)setSInt64:(long long)arg1 forUInt64Key:(unsigned long long)arg2;
@property(readonly, nonatomic) long long width; // @synthesize width=_width;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

