//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SCSnapWatermarkOverlayLayout <NSObject>
@property(readonly, nonatomic) struct CGRect subtitleRect;
@property(readonly, nonatomic) struct CGRect titleRect;
- (void)updateContentSize:(struct CGSize)arg1;
@property(readonly, nonatomic) struct CGRect watermarkImageRect;
@property(readonly, nonatomic) struct CGRect watermarkTextRect;
@end

