//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SCSongInfoPlayNowBuilder : NSObject
{
    NSString *_appleMusicURL;
    NSString *_googlePlayMusicURL;
    NSString *_spotifyURL;
}

+ (id)withSongInfoPlayNow:(id)arg1;
- (void).cxx_destruct;
- (id)build;
- (id)setAppleMusicURL:(id)arg1;
- (id)setGooglePlayMusicURL:(id)arg1;
- (id)setSpotifyURL:(id)arg1;

@end

