//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCSpectaclesMalibuRequestMessage.h"

@interface SCSpectaclesNewportRequestMessage : SCSpectaclesMalibuRequestMessage
{
}

+ (unsigned int)_colorIntValueFromLEDColor:(unsigned long long)arg1;
+ (id)addAncsNotificationRule:(id)arg1;
+ (id)contextNotificationWithAnimation:(id)arg1;
+ (id)deviceInfoInitialEnableHevc:(_Bool)arg1 enableLocation:(id)arg2 enableBurstMode:(id)arg3 burstFps:(long long)arg4;
+ (id)deviceInfoUpdate;
+ (id)deviceInfoUpdateLowBattery;
+ (id)peerBondStatus;
+ (id)removeAllAncsNotificationRules;
+ (id)setAncsNotificationsEnabled:(_Bool)arg1;
+ (id)setLocationEnabled:(_Bool)arg1;

@end

