//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCSpectaclesDepthLensesExperimentContext : SCExperimentContext
{
    _Bool _enableDepthLenses;
    _Bool _swipeCarouselEnabled;
}

@property(readonly, nonatomic) _Bool enableDepthLenses; // @synthesize enableDepthLenses=_enableDepthLenses;
- (id)experimentName;
- (void)setupParameters;
@property(readonly, nonatomic) _Bool swipeCarouselEnabled; // @synthesize swipeCarouselEnabled=_swipeCarouselEnabled;

@end

