//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, SCSpectaclesContent, SCSpectaclesNetworkRequest, SCSpectaclesTaskManager;

@protocol SCSpectaclesTaskManagerDelegate <NSObject>
- (void)taskManager:(SCSpectaclesTaskManager *)arg1 didDownloadContent:(SCSpectaclesContent *)arg2 component:(unsigned long long)arg3;
- (void)taskManager:(SCSpectaclesTaskManager *)arg1 sawError:(NSError *)arg2;
- (void)taskManager:(SCSpectaclesTaskManager *)arg1 sendNetworkRequest:(SCSpectaclesNetworkRequest *)arg2 withDelay:(double)arg3;
- (void)taskManagerComplete:(SCSpectaclesTaskManager *)arg1;
- (void)taskManagerHandledResponse:(SCSpectaclesTaskManager *)arg1;
@end

