//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCSpectaclesBaseAnnouncer.h"

#import "SCSpectaclesEventListener-Protocol.h"

@class NSString;

@interface SCSpectaclesEventListenerAnnouncer : SCSpectaclesBaseAnnouncer <SCSpectaclesEventListener>
{
}

- (void)spectaclesDevice:(id)arg1 didCompletedScheduledUpdateWithUserInfo:(id)arg2 error:(id)arg3;
- (void)spectaclesDevice:(id)arg1 didFetchFirmwareUpdateDigest:(id)arg2;
- (void)spectaclesDevice:(id)arg1 didReceiveClientId:(id)arg2 requestAuthzCode:(_Bool)arg3;
- (void)spectaclesDevice:(id)arg1 didReceiveCloudUploadEvent:(unsigned long long)arg2;
- (void)spectaclesDevice:(id)arg1 didReceiveLastCloudUploadTime:(id)arg2;
- (void)spectaclesDevice:(id)arg1 didReceiveShareWifiCredentialsResponseStatus:(unsigned long long)arg2;
- (void)spectaclesDevice:(id)arg1 didReceiveWifiAPList:(id)arg2;
- (void)spectaclesDevice:(id)arg1 didUnpairWithReason:(unsigned long long)arg2;
- (void)spectaclesDevice:(id)arg1 didUpdateInfo:(unsigned long long)arg2;
- (void)spectaclesDevice:(id)arg1 onAlertNotification:(unsigned long long)arg2;
- (void)spectaclesDevice:(id)arg1 onDeviceLogsUpdate:(unsigned long long)arg2;
- (void)spectaclesDevice:(id)arg1 onFirmwareUpdate:(unsigned long long)arg2 progress:(float)arg3;
- (void)spectaclesDeviceDidPair:(id)arg1;
- (void)spectaclesDeviceDidUpdateContentList:(id)arg1;
- (void)spectaclesDeviceDidUpdateState:(id)arg1;
- (void)spectaclesOnBluetoothStateUpdate:(long long)arg1;
- (void)spectaclesOnDeviceForgotten:(id)arg1;
- (void)spectaclesOnPairingStateUpdate:(unsigned long long)arg1 deviceInformation:(id)arg2;
- (void)spectaclesSensorStore:(id)arg1 didAddCalibration:(id)arg2;
- (void)spectaclesTransferSession:(id)arg1 onTransferUpdate:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

