//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCPreferences.h"

#import "SCUserSessionScoped-Protocol.h"

@class EGODatabase, EGODatabaseStatement, NSMutableDictionary, NSMutableSet, NSObject, NSString, SCDocPreferencesFetcher, SCPreferencesObservationGraph, SCQueuePerformer;
@protocol OS_dispatch_queue;

@interface SCSQLitePreferences : SCPreferences <SCUserSessionScoped>
{
    NSString *_filePath;
    _Bool _fileExists;
    SCQueuePerformer *_performer;
    EGODatabase *_database;
    EGODatabaseStatement *_queryValueForKey;
    EGODatabaseStatement *_queryKeysWithPrefix;
    EGODatabaseStatement *_replaceValueForKey;
    EGODatabaseStatement *_deleteWithKey;
    EGODatabaseStatement *_beginTransaction;
    EGODatabaseStatement *_commitTransaction;
    NSObject<OS_dispatch_queue> *_cacheAccessSync;
    NSMutableDictionary *_cachedKeyValues;
    SCPreferencesObservationGraph *_observationGraph;
    NSMutableDictionary *_allBatchChangedObjects;
    _Bool _fastAccessStatsCollected;
    NSMutableDictionary *_fastAccessedData;
    NSMutableSet *_fastAccessStats;
    CDUnknownBlockType _fastAccessStatsBlock;
    _Bool _fastAccessStatsChanged;
    SCDocPreferencesFetcher *_docFetcher;
}

+ (id)_currentPreferences;
+ (void)_setCurrentPreferences:(id)arg1;
- (void).cxx_destruct;
- (id)_beginTransaction;
- (void)_cancelFastAccessStats;
- (void)_checkIfFastAccessStatsChanged;
- (id)_commitTransaction;
- (id)_deleteWithKey;
- (id)_deserializeObject:(id)arg1;
- (id)_docFetcher;
- (id)_keysWithPrefix:(id)arg1;
- (id)_keysWithPrefixFromDB:(id)arg1;
- (id)_objectForKeyFromDB:(id)arg1;
- (void)_pushFastAccessStats;
- (id)_queryKeysWithPrefix;
- (id)_queryValueForKey;
- (void)_readFastAccessKeyValues;
- (void)_removeFastAccessKeyValues;
- (id)_replaceValueForKey;
- (id)_serializeObject:(id)arg1;
- (void)_setObjectDataToDB:(id)arg1 forKey:(id)arg2;
- (void)_setupDatabase;
- (void)_setupDatabaseIfExists;
- (void)_writeFastAccessKeyValuesIfChanged;
- (void)addEntriesFromDictionary:(id)arg1;
- (id)allKeysInNamespace:(id)arg1;
- (id)initWithFilePath:(id)arg1;
- (void)invalidate;
- (id)objectForKey:(id)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)observe:(id)arg1 callbackQueue:(id)arg2 changeHandler:(CDUnknownBlockType)arg3;
- (void)performChanges:(CDUnknownBlockType)arg1 completionQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)synchronize;
- (void)unobserveWithKeys:(id)arg1 observationToken:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

