//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSData, NSMutableArray, NSString, SCSCOREMultiSnapExtension, SCSCORESnapSource, SCSSMSnapCreatorInfo, SCSSMSnapFragmentMetadata, SCSSMSnapMediaInfo, SCSSMSnapPivotInfo;

@interface SCSSMStorySnap : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *attachmentURL; // @dynamic attachmentURL;
@property(copy, nonatomic) NSData *audioStitchData; // @dynamic audioStitchData;
@property(nonatomic) long long creationTimestampMs; // @dynamic creationTimestampMs;
@property(retain, nonatomic) SCSSMSnapCreatorInfo *creatorInfo; // @dynamic creatorInfo;
@property(copy, nonatomic) NSString *displayGeoInfo; // @dynamic displayGeoInfo;
@property(copy, nonatomic) NSString *encryptedGeoData; // @dynamic encryptedGeoData;
@property(nonatomic) long long expirationTimestampMs; // @dynamic expirationTimestampMs;
@property(retain, nonatomic) SCSSMSnapFragmentMetadata *fragmentMetadata; // @dynamic fragmentMetadata;
@property(nonatomic) _Bool hasCreatorInfo; // @dynamic hasCreatorInfo;
@property(nonatomic) _Bool hasFragmentMetadata; // @dynamic hasFragmentMetadata;
@property(nonatomic) _Bool hasMediaInfo; // @dynamic hasMediaInfo;
@property(nonatomic) _Bool hasMultiSnapExtension; // @dynamic hasMultiSnapExtension;
@property(nonatomic) _Bool hasPivotInfo; // @dynamic hasPivotInfo;
@property(nonatomic) _Bool hasSnapSource; // @dynamic hasSnapSource;
@property(nonatomic) _Bool hasSnappablesMetadata; // @dynamic hasSnappablesMetadata;
@property(copy, nonatomic) NSString *lensId; // @dynamic lensId;
@property(retain, nonatomic) SCSSMSnapMediaInfo *mediaInfo; // @dynamic mediaInfo;
@property(retain, nonatomic) SCSCOREMultiSnapExtension *multiSnapExtension; // @dynamic multiSnapExtension;
@property(copy, nonatomic) NSString *originalSnapId; // @dynamic originalSnapId;
@property(retain, nonatomic) SCSSMSnapPivotInfo *pivotInfo; // @dynamic pivotInfo;
@property(copy, nonatomic) NSString *rawSnapId; // @dynamic rawSnapId;
@property(copy, nonatomic) NSData *serializedUnlockablesSnapInfo; // @dynamic serializedUnlockablesSnapInfo;
@property(copy, nonatomic) NSString *sharedStorySubmissionId; // @dynamic sharedStorySubmissionId;
@property(copy, nonatomic) NSString *snapClientId; // @dynamic snapClientId;
@property(retain, nonatomic) SCSCORESnapSource *snapSource; // @dynamic snapSource;
@property(retain, nonatomic) NSMutableArray *subTitlesArray; // @dynamic subTitlesArray;
@property(readonly, nonatomic) unsigned long long subTitlesArray_Count; // @dynamic subTitlesArray_Count;
@property(copy, nonatomic) NSString *title; // @dynamic title;

@end

