//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class SCStoriesLocation;

@interface SCStoriesGeoStoryConfig : NSObject <NSCopying>
{
    long long _privacyType;
    SCStoriesLocation *_center;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) SCStoriesLocation *center; // @synthesize center=_center;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithPrivacyType:(long long)arg1 center:(id)arg2;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) long long privacyType; // @synthesize privacyType=_privacyType;

@end

