//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCStickerRankingFunctions : NSObject
{
}

+ (void)_aggregateStickers:(id)arg1 bitmojis:(id)arg2 stickerCounters:(id)arg3 bitmojiCounters:(id)arg4 tagFrequency:(id)arg5 tag:(id)arg6;
+ (id)_sortStickers:(id)arg1 bitmojis:(id)arg2 numberOfBitmojisShown:(long long)arg3 numberOfStickersShown:(long long)arg4;
+ (void)collectStickerFromSearcher:(id)arg1 fuzzyTags:(id)arg2 tagFrequency:(id)arg3 numberOfBitmojisShown:(long long)arg4 numberOfStickersShown:(long long)arg5 rankingMethod:(long long)arg6 shouldIncludeFriendBitmoji:(_Bool)arg7 completionHandler:(CDUnknownBlockType)arg8;
+ (id)gregorianCalendar;

@end

