//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCTraceEnabled-Protocol.h"

@class NSMutableArray, NSString, SCLazy;

@interface SCStoriesUnarchiver : NSObject <SCTraceEnabled>
{
    _Bool _unarchivingStories;
    NSMutableArray *_storiesUnarchivingWaitingQueue;
    _Bool _shouldUnarchiveStories;
    SCLazy *_storiesDataCoordinator;
    _Bool _shouldUnarchive;
    _Bool _unarchiving;
    _Bool _didFinishUnarchivingStories;
}

- (void).cxx_destruct;
- (void)_notifyStoriesAreUnarchived;
- (void)_snapshotPreLaunchViewedMapWithCompletion:(CDUnknownBlockType)arg1;
- (void)_unarchiveStoriesOnBackgroundQueueWithIsLaunchedToBackground:(_Bool)arg1;
- (void)_unarchiveStoriesSuccess:(id)arg1;
- (void)_unarchivingStoriesWithCompletion:(CDUnknownBlockType)arg1;
- (void)_willUnarchiveStories;
- (void)beginUnarchivingStories;
@property(readonly, nonatomic) _Bool didFinishUnarchivingStories; // @synthesize didFinishUnarchivingStories=_didFinishUnarchivingStories;
- (id)initWithStoriesMetadataProvider:(id)arg1;
- (void)interruptUnarchiving;
@property(readonly, nonatomic) _Bool shouldUnarchive; // @synthesize shouldUnarchive=_shouldUnarchive;
@property(readonly, nonatomic) _Bool unarchiving; // @synthesize unarchiving=_unarchiving;
- (void)waitUntilStoriesAreUnarchived:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

