//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SCStoriesMySnapClusterInfo : NSObject <NSCopying>
{
    NSString *_clusterId;
    NSString *_clusterName;
    NSString *_clusterDisplayName;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *clusterDisplayName; // @synthesize clusterDisplayName=_clusterDisplayName;
@property(readonly, copy, nonatomic) NSString *clusterId; // @synthesize clusterId=_clusterId;
@property(readonly, copy, nonatomic) NSString *clusterName; // @synthesize clusterName=_clusterName;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithClusterId:(id)arg1 clusterName:(id)arg2 clusterDisplayName:(id)arg3;
- (_Bool)isEqual:(id)arg1;

@end

