//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SCQueuePerformer;

@interface SCStartupCaptureHardwareWarmer : NSObject
{
    _Bool _warmupScheduled;
    _Bool _needToScheduleCameraWarmupForHeadlessMode;
    SCQueuePerformer *_captureHardwareWarmerPerformer;
}

- (void).cxx_destruct;
- (void)applicationDidEnterBackground;
- (void)applicationEnterForegroundCheckForCameraWarmupInCaseHeadless;
- (id)init;
- (void)markHeadlessColdStart;
- (void)markHeadlessLaunchNotToCameraScreen;
- (void)warmupCaptureHardwareForNormalColdStart:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;

@end

