//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSDictionary, NSString;

@interface SCStoryAdStreamRequestInfo : NSObject <NSCoding>
{
    NSString *_adUnitId;
    NSDictionary *_targetingParams;
    NSDictionary *_adRequestConfig;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *adRequestConfig; // @synthesize adRequestConfig=_adRequestConfig;
@property(copy, nonatomic) NSString *adUnitId; // @synthesize adUnitId=_adUnitId;
- (void)encodeWithCoder:(id)arg1;
- (long long)firstPositionToRequestForInStream;
- (id)initWithAdUnitId:(id)arg1 withTargetingParams:(id)arg2 withAdRequestConfig:(id)arg3;
- (id)initWithCoder:(id)arg1;
- (long long)minimumSnapsNeededToMakeAdRequest;
- (long long)secondsAdResponsesValidFor;
@property(retain, nonatomic) NSDictionary *targetingParams; // @synthesize targetingParams=_targetingParams;
- (id)streamKey;

@end

