//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SCMessageChatViewModelProps;
@protocol SCChatRenderingMessage;

@protocol SCStackableViewModelProtocol <NSObject>
- (void)addMessage:(id <SCChatRenderingMessage>)arg1 viewModelProps:(SCMessageChatViewModelProps *)arg2;
- (_Bool)canStackNewMessage:(id <SCChatRenderingMessage>)arg1;
- (_Bool)isStackable;
@end

