//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SCStickerState, UIImage;

@interface SCStickerDeepLinkMetadata : NSObject
{
    SCStickerState *_stickerState;
    UIImage *_image;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
- (id)initWithStickerState:(id)arg1 image:(id)arg2;
@property(readonly, nonatomic) SCStickerState *stickerState; // @synthesize stickerState=_stickerState;

@end

