//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SCStickerPackMetadataLoaderSubscriptionToken;
@protocol OS_dispatch_queue, SCStickerPackMetadataLoaderSubscriber;

@interface SCStickerPackMetadataLoaderSubscription : NSObject
{
    id <SCStickerPackMetadataLoaderSubscriber> _subscriber;
    NSObject<OS_dispatch_queue> *_queue;
    NSString *_key;
    SCStickerPackMetadataLoaderSubscriptionToken *_token;
    id <SCStickerPackMetadataLoaderSubscriber> _weakSubscriber;
}

- (void).cxx_destruct;
- (id)initWithSubscriber:(id)arg1 queue:(id)arg2 key:(id)arg3;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) NSString *key; // @synthesize key=_key;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) id <SCStickerPackMetadataLoaderSubscriber> subscriber; // @synthesize subscriber=_subscriber;
@property(readonly, nonatomic) SCStickerPackMetadataLoaderSubscriptionToken *token; // @synthesize token=_token;
@property(readonly, nonatomic) __weak id <SCStickerPackMetadataLoaderSubscriber> weakSubscriber; // @synthesize weakSubscriber=_weakSubscriber;

@end

