//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCTraceEnabled-Protocol.h"

@class NSString, SCBitmojiStickerManager;
@protocol SCBitmojiAvatarProvider, SCPerforming;

@interface SCStickerTagFuzzySearch : NSObject <SCTraceEnabled>
{
    id <SCPerforming> _dispatchPerformer;
    id <SCBitmojiAvatarProvider> _bitmojiAvatarProvider;
    SCBitmojiStickerManager *_bitmojiStickerManager;
}

+ (_Bool)_isOffensiveWord:(id)arg1;
+ (_Bool)_textHasPunctuationsOnly:(id)arg1;
+ (_Bool)isSearchEnabled;
+ (_Bool)isStopWord:(id)arg1;
+ (id)processedTextWithText:(id)arg1;
+ (id)removeDup:(id)arg1;
- (void).cxx_destruct;
- (id)initWithBitmojiAvatarProvider:(id)arg1 bitmojiStickerManager:(id)arg2;
- (void)searchStickersWithFuzzyText:(id)arg1 avatarIds:(id)arg2 bitmojiOnly:(_Bool)arg3 stickerTarget:(long long)arg4 shouldIncludeFriendBitmojiForQuickSend:(_Bool)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (void)searchStickersWithFuzzyText:(id)arg1 stickerTarget:(long long)arg2 shouldIncludeFriendBitmojiForQuickSend:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)searchStickersWithFuzzyTextAndParameter:(id)arg1 stickerTarget:(long long)arg2 avatarIds:(id)arg3 bitmojiOnly:(_Bool)arg4 shouldIncludeFriendBitmojiForQuickSend:(_Bool)arg5 similarity:(double)arg6 numShortList:(long long)arg7 numFuzzyTag:(long long)arg8 completionHandler:(CDUnknownBlockType)arg9;
- (void)searchStickersWithFuzzyTextAndParameter:(id)arg1 stickerTarget:(long long)arg2 shouldIncludeFriendBitmojiForQuickSend:(_Bool)arg3 similarity:(double)arg4 numShortList:(long long)arg5 numFuzzyTag:(long long)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (void)searchStickersWithSingleText:(id)arg1 avatarIds:(id)arg2 bitmojiOnly:(_Bool)arg3 stickerTarget:(long long)arg4 shouldIncludeFriendBitmojiForQuickSend:(_Bool)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (void)searchStickersWithSingleText:(id)arg1 stickerTarget:(long long)arg2 shouldIncludeFriendBitmojiForQuickSend:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

