//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDate, NSString, SCAvatarViewModel;

@interface SCStoryManagementChromeViewModel : NSObject <NSCopying>
{
    NSString *_titleLabelText;
    NSDate *_timestamp;
    long long _chromeViewType;
    SCAvatarViewModel *_avatarViewModel;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) SCAvatarViewModel *avatarViewModel; // @synthesize avatarViewModel=_avatarViewModel;
@property(readonly, nonatomic) long long chromeViewType; // @synthesize chromeViewType=_chromeViewType;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithTitleLabelText:(id)arg1 timestamp:(id)arg2 chromeViewType:(long long)arg3 avatarViewModel:(id)arg4;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, copy, nonatomic) NSString *titleLabelText; // @synthesize titleLabelText=_titleLabelText;

@end

