//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@interface SCSUPImpressionEntry : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) long long endTimestampMsec; // @dynamic endTimestampMsec;
@property(nonatomic) float impTimeSecs; // @dynamic impTimeSecs;
@property(nonatomic) long long numLongImpressions; // @dynamic numLongImpressions;
@property(nonatomic) long long startTimestampMsec; // @dynamic startTimestampMsec;

@end

