//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDate, SCTCallCard, SCTLocalMediaView;

@protocol SCTActiveCallCardDelegate <NSObject>
- (void)callCard:(SCTCallCard *)arg1 didSelectAction:(unsigned long long)arg2;
- (void)callCardDragDismissed:(SCTCallCard *)arg1;
- (NSDate *)callEstablishedDateForCallCard:(SCTCallCard *)arg1;
- (SCTLocalMediaView *)localMediaViewForCallCard:(SCTCallCard *)arg1;
@end

