//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, SCTextChatTableViewCellV2;

@protocol SCTextChatTableViewCellV2Delegate
- (void)textChatTableViewCell:(SCTextChatTableViewCellV2 *)arg1 didTapTag:(NSString *)arg2;
@end

