//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSRunLoop, NSString, NSTimer, SCThrottleTarget;

@interface SCThrottleTimer : NSObject
{
    _Bool _isScheduled;
    _Bool _isThrottled;
    _Bool _repeats;
    double _timeInterval;
    id _userInfo;
    NSRunLoop *_runLoop;
    NSString *_runLoopMode;
    double _tolerance;
    NSTimer *_internalTimer;
    SCThrottleTarget *_target;
}

- (void).cxx_destruct;
- (void)_createTimer;
- (void)_onThrottleTargetDidTrigger:(id)arg1;
- (void)_removeTimer;
- (void)cancel;
- (void)dealloc;
- (void)fire;
- (id)initWithInterval:(double)arg1 target:(id)arg2 selector:(SEL)arg3 userInfo:(id)arg4;
- (id)initWithInterval:(double)arg1 target:(id)arg2 selector:(SEL)arg3 userInfo:(id)arg4 repeats:(_Bool)arg5;
@property(retain, nonatomic) NSTimer *internalTimer; // @synthesize internalTimer=_internalTimer;
@property(nonatomic) _Bool isScheduled; // @synthesize isScheduled=_isScheduled;
@property(nonatomic) _Bool isThrottled; // @synthesize isThrottled=_isThrottled;
@property(nonatomic) _Bool repeats; // @synthesize repeats=_repeats;
- (void)reschedule;
@property(retain, nonatomic) NSRunLoop *runLoop; // @synthesize runLoop=_runLoop;
@property(retain, nonatomic) NSString *runLoopMode; // @synthesize runLoopMode=_runLoopMode;
- (void)schedule;
@property(retain, nonatomic) SCThrottleTarget *target; // @synthesize target=_target;
@property(nonatomic) double timeInterval; // @synthesize timeInterval=_timeInterval;
@property(nonatomic) double tolerance; // @synthesize tolerance=_tolerance;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;

@end

