//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCActiveUserSessionScope, SCBitmojiSelfieServices, SCLazy, SCLoggerServices, SCServicesExposer, SCSnapchatterServices;

@interface SCTodayWidgetEntryPoint : SCEntryPoint
{
    SCLazy *_lazyTodayWidgetService;
    SCActiveUserSessionScope *_activeUserSessionScope;
    SCBitmojiSelfieServices *_bitmojiSelfieServices;
    SCLoggerServices *_loggerServices;
    SCSnapchatterServices *_snapchatterServices;
    SCServicesExposer *_todayWidgetServicesExposer;
}

- (void).cxx_destruct;
- (id)_todayWidgetService;
- (void)_warmupTodayWidgetService;
@property(nonatomic) __weak SCActiveUserSessionScope *activeUserSessionScope; // @synthesize activeUserSessionScope=_activeUserSessionScope;
- (void)begin;
@property(nonatomic) __weak SCBitmojiSelfieServices *bitmojiSelfieServices; // @synthesize bitmojiSelfieServices=_bitmojiSelfieServices;
- (id)end;
@property(nonatomic) __weak SCLoggerServices *loggerServices; // @synthesize loggerServices=_loggerServices;
@property(nonatomic) __weak SCSnapchatterServices *snapchatterServices; // @synthesize snapchatterServices=_snapchatterServices;
@property(retain, nonatomic) SCServicesExposer *todayWidgetServicesExposer; // @synthesize todayWidgetServicesExposer=_todayWidgetServicesExposer;

@end

