//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface SCTransitionState : NSObject
{
    NSString *_state;
    NSString *_trigger;
    NSDate *_trigeredTime;
}

+ (id)newWithState:(id)arg1 triggeredBy:(id)arg2;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
@property(retain) NSString *state; // @synthesize state=_state;
@property(retain) NSDate *trigeredTime; // @synthesize trigeredTime=_trigeredTime;
@property(retain) NSString *trigger; // @synthesize trigger=_trigger;

@end

