//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCProfileTransitionCoordinatorDataSource-Protocol.h"
#import "SCProfileTransitionCoordinatorDelegate-Protocol.h"
#import "SCProfileViewControllerDelegate-Protocol.h"
#import "SCTraceEnabled-Protocol.h"

@class NSString, SCProfileTransitionCoordinator, SCUnifiedProfileViewController, SCUserSession, UIViewController;
@protocol SCUnifiedProfilePresenterDelegate;

@interface SCUnifiedProfilePresenter : NSObject <SCProfileTransitionCoordinatorDataSource, SCProfileTransitionCoordinatorDelegate, SCProfileViewControllerDelegate, SCTraceEnabled>
{
    SCUserSession *_userSession;
    UIViewController *_presentingViewController;
    SCUnifiedProfileViewController *_unifiedProfileViewController;
    SCProfileTransitionCoordinator *_profileTransitionCoordinator;
    unsigned long long _unifiedProfileProfileType;
    NSString *_sourcePageName;
    id <SCUnifiedProfilePresenterDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_didDismissUnifiedProfile;
- (void)_presentSnapchatterProfileWithSnapchatter:(id)arg1 configuration:(id)arg2 replyDelegate:(id)arg3 startChatDelegate:(id)arg4 navigationDelegate:(id)arg5 lifecycleListener:(id)arg6 friendProfilePageActionHandlerDelegate:(id)arg7 openningData:(id)arg8 completion:(CDUnknownBlockType)arg9;
- (void)_presentUnifiedViewController:(id)arg1 profileType:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
@property(nonatomic) __weak id <SCUnifiedProfilePresenterDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dismissProfileViewController:(id)arg1;
- (void)dismissProfileViewController:(id)arg1 animated:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)dismissUnifiedProfile;
- (void)dismissUnifiedProfileAnimated:(_Bool)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)initWithUserSession:(id)arg1 presentingViewController:(id)arg2;
- (void)presentFriendProfileWithUserId:(id)arg1 configuration:(id)arg2 snapchattersDataFetcher:(id)arg3 replyDelegate:(id)arg4 startChatDelegate:(id)arg5 navigationDelegate:(id)arg6 lifecycleListener:(id)arg7 friendProfilePageActionHandlerDelegate:(id)arg8 openningData:(id)arg9 completion:(CDUnknownBlockType)arg10;
- (void)presentGroupProfileWithDataSource:(id)arg1 navigationDelegate:(id)arg2 replyDelegate:(id)arg3 startChatDelegate:(id)arg4 lifecycleListener:(id)arg5 groupProfilePageActionHandlerDelegate:(id)arg6 openningData:(id)arg7 completion:(CDUnknownBlockType)arg8;
- (void)presentGroupProfileWithGroupId:(id)arg1 navigationDelegate:(id)arg2 replyDelegate:(id)arg3 startChatDelegate:(id)arg4 lifecycleListener:(id)arg5 groupProfilePageActionHandlerDelegate:(id)arg6 openningData:(id)arg7 completion:(CDUnknownBlockType)arg8;
- (void)presentNonFriendProfileWithSnapchatter:(id)arg1 configuration:(id)arg2 replyDelegate:(id)arg3 startChatDelegate:(id)arg4 navigationDelegate:(id)arg5 lifecycleListener:(id)arg6 friendProfilePageActionHandlerDelegate:(id)arg7 openningData:(id)arg8 completion:(CDUnknownBlockType)arg9;
- (void)presentSnapchatterProfileWithDataSource:(id)arg1 replyDelegate:(id)arg2 startChatDelegate:(id)arg3 navigationDelegate:(id)arg4 lifecycleListener:(id)arg5 friendProfilePageActionHandlerDelegate:(id)arg6 openningData:(id)arg7 completion:(CDUnknownBlockType)arg8;
- (id)presentedViewControllerWithSwipeTransitionCoordinator:(id)arg1;
- (void)profileViewDidAppear:(id)arg1;
- (void)profileViewDidLoad:(id)arg1;
- (void)profileViewWillAppear:(id)arg1;
- (void)profileViewWillDisappear:(id)arg1;
- (void)transitionCoordinator:(id)arg1 didBeginWithTransitionType:(unsigned long long)arg2;
- (void)transitionCoordinator:(id)arg1 didCancelWithTransitionType:(unsigned long long)arg2;
- (void)transitionCoordinator:(id)arg1 didFinishWithTransitionType:(unsigned long long)arg2;
- (void)transitionCoordinator:(id)arg1 didUpdatePercentVisible:(double)arg2;
- (_Bool)transitionCoordinator:(id)arg1 shouldPerformTransitionWithType:(unsigned long long)arg2 interactive:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

