//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSAttributedString, NSString, SCActionModel, SCUnifiedProfileListCellActionButtonViewModel;

@interface SCUnifiedProfilePrivacyExplainerViewCellViewModel : NSObject <NSCopying>
{
    NSAttributedString *_title;
    NSAttributedString *_subtitle;
    NSString *_leftIconImageAsset;
    SCUnifiedProfileListCellActionButtonViewModel *_rightIconViewModel;
    SCActionModel *_rightIconTapActionModel;
    NSString *_rightIconAccessibilityIdentifier;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 leftIconImageAsset:(id)arg3 rightIconViewModel:(id)arg4 rightIconTapActionModel:(id)arg5 rightIconAccessibilityIdentifier:(id)arg6;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *leftIconImageAsset; // @synthesize leftIconImageAsset=_leftIconImageAsset;
@property(readonly, copy, nonatomic) NSString *rightIconAccessibilityIdentifier; // @synthesize rightIconAccessibilityIdentifier=_rightIconAccessibilityIdentifier;
@property(readonly, copy, nonatomic) SCActionModel *rightIconTapActionModel; // @synthesize rightIconTapActionModel=_rightIconTapActionModel;
@property(readonly, copy, nonatomic) SCUnifiedProfileListCellActionButtonViewModel *rightIconViewModel; // @synthesize rightIconViewModel=_rightIconViewModel;
@property(readonly, copy, nonatomic) NSAttributedString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, copy, nonatomic) NSAttributedString *title; // @synthesize title=_title;

@end

