//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSAttributedString;

@interface SCUnifiedSplitTextViewModel : NSObject <NSCopying>
{
    NSAttributedString *_separatorAttributedString;
    NSArray *_componentViewModels;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *componentViewModels; // @synthesize componentViewModels=_componentViewModels;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithSeparatorAttributedString:(id)arg1 componentViewModels:(id)arg2;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSAttributedString *separatorAttributedString; // @synthesize separatorAttributedString=_separatorAttributedString;

@end

