//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SOJUIdentityVerifyPhoneNumberResponse;

@interface SCUpdatePhoneNumberResponse : NSObject
{
    _Bool _isSuccess;
    _Bool _needsPhoneVerification;
    NSString *_errorMessage;
    NSString *_phoneNumber;
    NSString *_preAuthToken;
    SOJUIdentityVerifyPhoneNumberResponse *_verifyResponse;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(nonatomic) _Bool isSuccess; // @synthesize isSuccess=_isSuccess;
@property(nonatomic) _Bool needsPhoneVerification; // @synthesize needsPhoneVerification=_needsPhoneVerification;
@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(retain, nonatomic) NSString *preAuthToken; // @synthesize preAuthToken=_preAuthToken;
@property(retain, nonatomic) SOJUIdentityVerifyPhoneNumberResponse *verifyResponse; // @synthesize verifyResponse=_verifyResponse;

@end

