//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCVideoTranscodingSessionConfigurationProvider-Protocol.h"

@class NSString, SCVideoTranscodingConfigurationProviderInput;

@interface SCVideoTranscodingSessionDefaultConfigurationProvider : NSObject <SCVideoTranscodingSessionConfigurationProvider>
{
    SCVideoTranscodingConfigurationProviderInput *_input;
    long long _level;
}

- (void).cxx_destruct;
- (id)initWithConfigurationProviderInput:(id)arg1 mediaQualityLevel:(long long)arg2;
- (id)videoTranscodingConfigurationWithMediaSource:(unsigned long long)arg1 mediaDestination:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

