//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSString;

@protocol SCVideoCaptureConfiguration <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSString *activeLensId;
@property(readonly, copy, nonatomic) NSString *captureSessionId;
@property(readonly, nonatomic) _Bool isSnapWithDepth;
@property(readonly, nonatomic) _Bool isSnappable;
@property(readonly, nonatomic) _Bool isStoppingRecording;
@property(readonly, nonatomic) _Bool lensEnabled;
@property(readonly, nonatomic) _Bool lensInitiatedCapture;
@property(readonly, nonatomic) unsigned long long recordingMethod;
@end

