//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCWebpOverlayExperimentContext : SCExperimentContext
{
    _Bool _memoriesOverlayWebp;
    _Bool _snapOverlayWebp;
    double _memoriesOverlayQuality;
    double _snapOverlayQuality;
}

- (id)experimentName;
@property(readonly, nonatomic) double memoriesOverlayQuality; // @synthesize memoriesOverlayQuality=_memoriesOverlayQuality;
@property(readonly, nonatomic) _Bool memoriesOverlayWebp; // @synthesize memoriesOverlayWebp=_memoriesOverlayWebp;
- (void)setupParameters;
@property(readonly, nonatomic) double snapOverlayQuality; // @synthesize snapOverlayQuality=_snapOverlayQuality;
@property(readonly, nonatomic) _Bool snapOverlayWebp; // @synthesize snapOverlayWebp=_snapOverlayWebp;

@end

