//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class SIGActionBarItem, SIGTargetActionDispatcher;

@interface SIGActionBarButton : UIControl
{
    SIGActionBarItem *_item;
    SIGTargetActionDispatcher *_userPressActionDispatcher;
}

+ (id)actionBarButtonWithItem:(id)arg1;
- (void).cxx_destruct;
- (void)_didPressButton;
- (id)initWithItem:(id)arg1;
- (struct CGSize)intrinsicContentSize;

@end

