//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class SIGCell, SIGCellContainer;

@interface SIGCollectionViewCell : UICollectionViewCell
{
    SIGCellContainer *_cellContainer;
    SIGCell *_underlyingCell;
}

+ (double)heightForCellWithStyle:(unsigned long long)arg1 containerStyle:(struct SIGContainerStyle)arg2;
- (void).cxx_destruct;
- (id)contentView;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
- (_Bool)isSelected;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1;
@property(nonatomic) struct SIGContainerStyle style;
@property(readonly, nonatomic) SIGCell *underlyingCell; // @synthesize underlyingCell=_underlyingCell;

@end

