//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol SOJUTalkAuthContext <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSString *conversationId;
@property(readonly, copy, nonatomic) NSString *mac;
@property(readonly, copy, nonatomic) NSString *scopeId;
@property(readonly, copy, nonatomic) NSString *sessionId;
@property(readonly, copy, nonatomic) NSString *sessionType;
@property(readonly, copy, nonatomic) NSString *token;
@property(readonly, copy, nonatomic) NSDictionary *usernameToUserId;
@end

