//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSNumber, NSString;

@protocol SOJURichStoryRichStoryInteractionZoneButtonItem <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSString *deepLinkFallbackAndroidPackageId;
@property(readonly, copy, nonatomic) NSNumber *deepLinkFallbackIosAppId;
@property(readonly, copy, nonatomic) NSString *deepLinkFallbackWebUrl;
@property(readonly, copy, nonatomic) NSString *deepLinkUri;
@property(readonly, copy, nonatomic) NSString *descriptionValue;
@property(readonly, copy, nonatomic) NSString *itemIcon;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, copy, nonatomic) NSString *url;
@end

