//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SOJUGalleryServletGrantSharedSnapSaveRequest-Protocol.h"

@class NSNumber, NSString, SOJUGallerySnapSource;

@interface SOJUGalleryServletGrantSharedSnapSaveRequest : NSObject <SOJUGalleryServletGrantSharedSnapSaveRequest>
{
    SOJUGallerySnapSource *_source;
    NSNumber *_entrySource;
    NSString *_entryExternalId;
}

+ (_Bool)canInitFromProto;
+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)decodeWithFasterDecoder:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
@property(readonly, copy, nonatomic) NSString *entryExternalId; // @synthesize entryExternalId=_entryExternalId;
@property(readonly, copy, nonatomic) NSNumber *entrySource; // @synthesize entrySource=_entrySource;
- (long long)entrySourceEnum;
- (int)entrySourceValue;
@property(readonly) unsigned long long hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;
- (id)initWithSource:(id)arg1 entrySource:(id)arg2 entryExternalId:(id)arg3;
- (_Bool)isEqual:(id)arg1;
- (_Bool)preferFasterCoding;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
@property(readonly, copy, nonatomic) SOJUGallerySnapSource *source; // @synthesize source=_source;
- (id)toDictionary;
- (id)toJson;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

