//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SOJUUnlockablesOndemandSticker-Protocol.h"

@class NSNumber, NSString;

@interface SOJUUnlockablesOndemandSticker : NSObject <SOJUUnlockablesOndemandSticker>
{
    NSString *_type;
    NSString *_emoji;
    NSString *_packId;
    NSString *_stickerId;
    NSNumber *_width;
    NSNumber *_height;
    NSNumber *_posX;
    NSNumber *_posY;
    NSNumber *_rotation;
    NSNumber *_scale;
}

+ (_Bool)canInitFromProto;
+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)decodeWithFasterDecoder:(id)arg1;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSString *emoji; // @synthesize emoji=_emoji;
- (void)encodeWithCoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSNumber *height; // @synthesize height=_height;
- (double)heightValue;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;
- (id)initWithType:(id)arg1 emoji:(id)arg2 packId:(id)arg3 stickerId:(id)arg4 width:(id)arg5 height:(id)arg6 posX:(id)arg7 posY:(id)arg8 rotation:(id)arg9 scale:(id)arg10;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *packId; // @synthesize packId=_packId;
@property(readonly, copy, nonatomic) NSNumber *posX; // @synthesize posX=_posX;
- (int)posXValue;
@property(readonly, copy, nonatomic) NSNumber *posY; // @synthesize posY=_posY;
- (int)posYValue;
- (_Bool)preferFasterCoding;
@property(readonly, copy, nonatomic) NSNumber *rotation; // @synthesize rotation=_rotation;
- (double)rotationValue;
@property(readonly, copy, nonatomic) NSNumber *scale; // @synthesize scale=_scale;
- (double)scaleValue;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
@property(readonly, copy, nonatomic) NSString *stickerId; // @synthesize stickerId=_stickerId;
- (id)toDictionary;
- (id)toJson;
@property(readonly, copy, nonatomic) NSString *type; // @synthesize type=_type;
- (long long)typeEnum;
@property(readonly, copy, nonatomic) NSNumber *width; // @synthesize width=_width;
- (double)widthValue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

