//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSNumber;

@protocol SOJUStoryExtra <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSNumber *screenCaptureRecordingCount;
@property(readonly, copy, nonatomic) NSNumber *screenCaptureShotCount;
@property(readonly, copy, nonatomic) NSNumber *screenshotCount;
@property(readonly, copy, nonatomic) NSNumber *snapSaveCount;
@property(readonly, copy, nonatomic) NSNumber *viewCount;
@end

