//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SOJUUnlockablesOndemandHomeFilterAddress;

@interface SOJUUnlockablesOndemandUpdateHomeAddressRequestBuilder : NSObject
{
    SOJUUnlockablesOndemandHomeFilterAddress *_address;
}

+ (id)withJUUnlockablesOndemandUpdateHomeAddressRequest:(id)arg1;
- (void).cxx_destruct;
- (id)build;
- (id)setAddress:(id)arg1;

@end

