//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSNumber, NSString;

@protocol SOJUUnlockableTrackInfo <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSString *adServeRequestId;
@property(readonly, copy, nonatomic) NSString *adTrackUrl;
@property(readonly, copy, nonatomic) NSString *batchTrackUrl;
@property(readonly, copy, nonatomic) NSString *encryptedSponsoredUnlockableTargetingInfoData;
@property(readonly, copy, nonatomic) NSString *encryptedUserTrackData;
@property(readonly, copy, nonatomic) NSString *jsonTrackUrl;
@property(readonly, copy, nonatomic) NSString *protoTrackUrl;
@property(readonly, copy, nonatomic) NSString *rankingData;
@property(readonly, copy, nonatomic) NSString *rankingId;
@property(readonly, copy, nonatomic) NSString *rawAdData;
@property(readonly, copy, nonatomic) NSNumber *skipTrack;
@end

