//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SOJUIdentitySendToRecipientScore-Protocol.h"

@class NSArray, NSNumber, NSString, SOJUIdentitySendToRecipient;

@interface SOJUIdentitySendToRecipientScore : NSObject <SOJUIdentitySendToRecipientScore>
{
    SOJUIdentitySendToRecipient *_recipient;
    NSNumber *_score;
    NSArray *_serverSideSignals;
}

+ (_Bool)canInitFromProto;
+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)decodeWithFasterDecoder:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;
- (id)initWithRecipient:(id)arg1 score:(id)arg2 serverSideSignals:(id)arg3;
- (_Bool)isEqual:(id)arg1;
- (_Bool)preferFasterCoding;
@property(readonly, copy, nonatomic) SOJUIdentitySendToRecipient *recipient; // @synthesize recipient=_recipient;
@property(readonly, copy, nonatomic) NSNumber *score; // @synthesize score=_score;
- (double)scoreValue;
@property(readonly, copy, nonatomic) NSArray *serverSideSignals; // @synthesize serverSideSignals=_serverSideSignals;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
- (id)toDictionary;
- (id)toJson;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

