//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SportsClusterInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *awayScore; // @dynamic awayScore;
@property(copy, nonatomic) NSString *awayTeam; // @dynamic awayTeam;
@property(copy, nonatomic) NSString *event; // @dynamic event;
@property(copy, nonatomic) NSString *gameStatus; // @dynamic gameStatus;
@property(copy, nonatomic) NSString *homeScore; // @dynamic homeScore;
@property(copy, nonatomic) NSString *homeTeam; // @dynamic homeTeam;
@property(copy, nonatomic) NSString *league; // @dynamic league;
@property(copy, nonatomic) NSString *sport; // @dynamic sport;

@end

