//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (SCCraft)
- (id)sc_craftScaleDownImageToScale:(unsigned long long)arg1;
- (id)sc_craftScaleDownImageToSize:(struct CGSize)arg1;
@end

