//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@protocol SCDismissToRootDelegate;

@interface UIViewController (PopToRoot)
@property(nonatomic) id <SCDismissToRootDelegate> dismissToRootDelegate;
- (_Bool)shouldPopToRootViewController;
- (_Bool)shouldPopToRootViewControllerLater;
- (double)timeBeforeReturningToCamera;
@end

