//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  2 2019 14:24:29).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIView;

@interface UIViewController (Cards)
+ (void)addCardCornersToView:(id)arg1;
+ (void)addCardCornersToView:(id)arg1 inRect:(struct CGRect)arg2;
+ (void)addNGSBottomCornersToView:(id)arg1;
+ (void)addNGSBottomCornersToView:(id)arg1 inRect:(struct CGRect)arg2;
+ (void)addNGSCornersToView:(id)arg1;
+ (void)addNGSCornersToView:(id)arg1 inRect:(struct CGRect)arg2;
+ (void)addNGSCornersToView:(id)arg1 inRect:(struct CGRect)arg2 withEdge:(unsigned long long)arg3 gap:(double)arg4;
+ (id)chatCardGradientColors;
+ (id)memoriesCardGradientColors;
+ (id)storiesCardGradientColors;
- (id)_cardTableView;
- (_Bool)_conformsToCardStylingProtocol;
- (void)_styleCellWithRoundedCorner:(id)arg1;
- (void)_styleCellWithoutRoundedCorner:(id)arg1;
@property(readonly, nonatomic) UIView *sc_cardDimView;
- (void)setSc_dimView:(id)arg1;
- (void)styleCellForCard:(id)arg1 forIndexPath:(id)arg2;
- (void)updateCardBackground:(_Bool)arg1 ngsEnabled:(_Bool)arg2;
@end

